/*
 * FF2 Decompiled Functions - Weapon Skill Growth System
 * Generated by Ghidra headless analysis
 * Program: GameAssembly.dll
 * Image Base: 0x180000000
 * IL2CPP types applied: True
 *
 * Purpose: Understanding FF2's weapon skill growth for screen reader accessibility
 *
 * FF2 Weapon Skill System:
 *   - Each weapon type has independent skill levels (1-16)
 *   - Skill increases through combat usage
 *   - Higher skill = more hits, better accuracy
 *   - Physical/Ability avoidance also level through use
 *
 * SkillLevelTarget enum:
 *   0 = WeaponSword
 *   1 = WeaponKnife
 *   2 = WeaponSpear
 *   3 = WeaponAxe
 *   4 = WeaponCane (Staff)
 *   5 = WeaponBow
 *   6 = WeaponShield
 *   7 = WeaponWrestle (Bare Hands)
 *   8 = PhysicalAvoidance
 *   9 = AbilityAvoidance
 *
 * Key classes:
 *   - StatusUpProvider: Core growth calculation engine
 *   - BattleResultCharacterData: Tracks skill level-ups
 *   - BattleSkillUpInformation: Battle action log for calculations
 */


/====================================================================/
/* BattleResultCharacterData
 ===================================================================/

/********************************************************************/
/* BattleResultCharacterData$$IsGrowthSkillLevel
 * RVA: 0x4A6870
 * Address: 0x1804A6870
 *******************************************************************/


void BattleResultCharacterData_IsGrowthSkillLevel(void)

{
  int iVar1;
  longlong lVar2;
  code *pcVar3;
  char cVar4;
  int iVar5;
  int iVar6;
  undefined8 uVar7;
  longlong lVar8;
  longlong *plVar9;
  int *piVar10;
  longlong unaff_RBP;
  ulonglong uVar11;
  undefined4 *unaff_R12;
  longlong unaff_R13;
  int iVar12;
  ulonglong unaff_R15;
  
  uVar7 = FUN_180d3b4f0();
  iVar12 = (int)unaff_R15;
  if (((*(byte *)(DAT_18223a4d0 + 0x12f) & 2) != 0) && (*(int *)(DAT_18223a4d0 + 0xe0) == iVar12)) {
    il2cpp_runtime_class_init();
  }
  lVar8 = FUN_180b2d070(uVar7,0);
  if (lVar8 == 0) {
    FUN_180237af0();
    pcVar3 = (code *)swi(3);
    (*pcVar3)();
    return;
  }
  lVar8 = FUN_1810956c0(lVar8,0);
  *(longlong *)(unaff_RBP + 0x68) = lVar8;
LAB_1804a68c0:
  if (lVar8 != 0) {
    cVar4 = FUN_1800dcbe0(0,DAT_18223c7c8,lVar8);
    if (cVar4 != '\0') {
      plVar9 = (longlong *)FUN_1800dcbe0(1,DAT_18223c7c8,lVar8);
      if (plVar9 != (longlong *)0x0) {
        if (*(longlong *)(*plVar9 + 0x40) == *(longlong *)(DAT_182274c50 + 0x40))
        goto code_r0x0001804a691a;
        goto LAB_1804a6a67;
      }
      goto LAB_1804a6a6f;
    }
    *unaff_R12 = 0xc9;
    lVar8 = thunk_FUN_180200bb0(lVar8,DAT_18223c790);
    if (lVar8 != 0) {
      FUN_1800dcbe0(0,DAT_18223c790,lVar8);
    }
    if (unaff_R15 == 0) {
      return;
    }
    goto LAB_1804a6a7a;
  }
LAB_1804a6a74:
  FUN_180237af0();
LAB_1804a6a7a:
  FUN_180237ac0();
  pcVar3 = (code *)swi(3);
  (*pcVar3)();
  return;
code_r0x0001804a691a:
  piVar10 = (int *)il2cpp_object_unbox();
  iVar1 = *piVar10;
  if ((iVar1 != 8) && (iVar1 != 9)) {
    uVar11 = unaff_R15 & 0xffffffff;
    *(int *)(unaff_RBP + 0x50) = iVar12;
    if ((*(longlong *)(unaff_R13 + 0x10) != 0) &&
       (lVar2 = *(longlong *)(*(longlong *)(unaff_R13 + 0x10) + 0x58), lVar2 != 0)) {
      FUN_1813c22b0(lVar2,iVar1,unaff_RBP + 0x50,DAT_182258028);
      uVar11 = (ulonglong)*(uint *)(unaff_RBP + 0x50);
    }
    if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    iVar5 = FUN_180382120(1,uVar11,1,0);
    uVar11 = unaff_R15 & 0xffffffff;
    *(int *)(unaff_RBP + 0x60) = iVar12;
    if ((*(longlong *)(unaff_R13 + 0x18) != 0) &&
       (lVar2 = *(longlong *)(*(longlong *)(unaff_R13 + 0x18) + 0x58), lVar2 != 0)) {
      FUN_1813c22b0(lVar2,iVar1,unaff_RBP + 0x60);
      uVar11 = (ulonglong)*(uint *)(unaff_RBP + 0x60);
    }
    if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    iVar6 = FUN_180382120(1,uVar11,1,0);
    if (iVar5 < iVar6) {
      if (*(longlong *)(unaff_R13 + 0x38) == 0) {
        FUN_180237af0();
LAB_1804a6a67:
        FUN_180237720();
LAB_1804a6a6f:
        FUN_180237af0();
        goto LAB_1804a6a74;
      }
      FUN_181483420(*(longlong *)(unaff_R13 + 0x38),iVar1,DAT_1822450b8);
    }
  }
  goto LAB_1804a68c0;
}



/********************************************************************/
/* BattleResultCharacterData$$WeaponSkillLevelUp
 * RVA: 0x4A67E0
 * Address: 0x1804A67E0
 *******************************************************************/


void FUN_1804a67e0(longlong param_1)

{
  int iVar1;
  longlong lVar2;
  code *pcVar3;
  undefined4 uVar4;
  char cVar5;
  int iVar6;
  int iVar7;
  undefined8 uVar8;
  longlong lVar9;
  longlong *plVar10;
  int *piVar11;
  undefined4 local_res8 [2];
  undefined4 local_res18 [2];
  longlong local_res20;
  
  if (DAT_181f6f52d == '\0') {
    thunk_FUN_1801fef70(DAT_1817e546c);
    DAT_181f6f52d = '\x01';
  }
  local_res8[0] = 0;
  local_res18[0] = 0;
  if (*(longlong *)(param_1 + 0x38) != 0) {
    FUN_180f7d9e0(*(longlong *)(param_1 + 0x38),DAT_182245078);
    uVar8 = DAT_182247bf8;
    if (((*(byte *)(DAT_18223ca00 + 0x12f) & 2) != 0) && (*(int *)(DAT_18223ca00 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar8 = FUN_180d3b4f0(uVar8,0);
    if (((*(byte *)(DAT_18223a4d0 + 0x12f) & 2) != 0) && (*(int *)(DAT_18223a4d0 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar9 = FUN_180b2d070(uVar8,0);
    if (lVar9 != 0) {
      lVar9 = FUN_1810956c0(lVar9,0);
      local_res20 = lVar9;
LAB_1804a68c0:
      if (lVar9 != 0) {
        cVar5 = FUN_1800dcbe0(0,DAT_18223c7c8,lVar9);
        if (cVar5 == '\0') {
          lVar9 = thunk_FUN_180200bb0(lVar9,DAT_18223c790);
          if (lVar9 != 0) {
            FUN_1800dcbe0(0,DAT_18223c790,lVar9);
          }
          return;
        }
        plVar10 = (longlong *)FUN_1800dcbe0(1,DAT_18223c7c8,lVar9);
        if (plVar10 != (longlong *)0x0) {
          if (*(longlong *)(*plVar10 + 0x40) == *(longlong *)(DAT_182274c50 + 0x40))
          goto code_r0x0001804a691a;
          goto LAB_1804a6a67;
        }
        goto LAB_1804a6a6f;
      }
LAB_1804a6a74:
      FUN_180237af0();
      FUN_180237ac0(0,0);
      pcVar3 = (code *)swi(3);
      (*pcVar3)();
      return;
    }
  }
  FUN_180237af0();
  pcVar3 = (code *)swi(3);
  (*pcVar3)();
  return;
code_r0x0001804a691a:
  piVar11 = (int *)il2cpp_object_unbox();
  iVar1 = *piVar11;
  if ((iVar1 != 8) && (iVar1 != 9)) {
    local_res8[0] = 0;
    if ((*(longlong *)(param_1 + 0x10) != 0) &&
       (lVar2 = *(longlong *)(*(longlong *)(param_1 + 0x10) + 0x58), lVar2 != 0)) {
      FUN_1813c22b0(lVar2,iVar1,local_res8,DAT_182258028);
    }
    uVar4 = local_res8[0];
    if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    iVar6 = FUN_180382120(1,uVar4,1,0);
    local_res18[0] = 0;
    if ((*(longlong *)(param_1 + 0x18) != 0) &&
       (lVar2 = *(longlong *)(*(longlong *)(param_1 + 0x18) + 0x58), lVar2 != 0)) {
      FUN_1813c22b0(lVar2,iVar1,local_res18);
    }
    uVar4 = local_res18[0];
    if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    iVar7 = FUN_180382120(1,uVar4,1,0);
    if (iVar6 < iVar7) {
      if (*(longlong *)(param_1 + 0x38) == 0) {
        FUN_180237af0();
LAB_1804a6a67:
        FUN_180237720();
LAB_1804a6a6f:
        FUN_180237af0();
        goto LAB_1804a6a74;
      }
      FUN_181483420(*(longlong *)(param_1 + 0x38),iVar1,DAT_1822450b8);
    }
  }
  goto LAB_1804a68c0;
}



/********************************************************************/
/* BattleResultCharacterData$$get_IsWeaponSkillLevelUp
 * RVA: 0x4130B0
 * Address: 0x1804130B0
 *******************************************************************/


undefined BattleResultCharacterData_get_IsWeaponSkillLevelUp(longlong param_1)

{
  return *(undefined *)(param_1 + 0x24);
}



/====================================================================/
/* BattleResultProvider
 ===================================================================/

/********************************************************************/
/* BattleResultProvider$$Genelate
 * RVA: 0x379320
 * Address: 0x180379320
 *******************************************************************/


longlong BattleResultProvider_Genelate
                   (undefined8 param_1,longlong param_2,int param_3,int param_4,ulonglong param_5,
                   undefined8 param_6)

{
  code *pcVar1;
  int *piVar2;
  char cVar3;
  undefined4 uVar4;
  int iVar5;
  uint uVar6;
  int iVar7;
  undefined8 uVar8;
  longlong lVar9;
  ulonglong uVar10;
  longlong lVar11;
  longlong lVar12;
  ulonglong uVar13;
  undefined8 uVar14;
  longlong lVar15;
  undefined2 uVar16;
  longlong *plVar17;
  longlong lVar18;
  int iStackX_20;
  int aiStack_f8 [4];
  int iStack_e8;
  int *piStack_e0;
  longlong lStack_d8;
  uint uStack_d0;
  longlong lStack_c8;
  longlong lStack_c0;
  longlong lStack_b8;
  ulonglong uStack_b0;
  int *piStack_a8;
  ulonglong uStack_a0;
  undefined8 uStack_98;
  longlong lStack_90;
  longlong lStack_88;
  undefined8 uStack_80;
  undefined8 uStack_78;
  undefined8 uStack_70;
  undefined4 uStack_50;
  undefined4 uStack_4c;
  undefined4 uStack_48;
  undefined4 uStack_44;
  undefined8 uStack_40;
  
  if (DAT_181f6e86a == '\0') {
    thunk_FUN_1801fef70(DAT_1817e54e0);
    DAT_181f6e86a = '\x01';
  }
  uVar13 = 0;
  uStack_98 = 0;
  uStack_80 = 0;
  uStack_78 = 0;
  uStack_70 = 0;
  uStack_b0 = 0;
  piStack_e0 = aiStack_f8;
  iStack_e8 = -1;
  piStack_a8 = piStack_e0;
  if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  uVar8 = FUN_1810e8a40(DAT_182263388);
  lVar15 = param_5;
  lVar9 = FUN_1804d7ab0(param_5,uVar8,0);
  uVar10 = thunk_FUN_180203bc0(DAT_18227ae60);
  param_5 = uVar10;
  FUN_180f858b0(uVar10,DAT_182246e18);
  if (lVar9 == 0) {
LAB_180379ca3:
    FUN_180237af0();
LAB_180379ca9:
    FUN_180237af0();
  }
  else {
    lVar18 = 0x20;
    iStackX_20 = param_4;
    while( true ) {
      uVar6 = (uint)uVar13;
      if ((int)*(uint *)(lVar9 + 0x18) <= (int)uVar6) break;
      if (*(uint *)(lVar9 + 0x18) <= uVar6) {
        FUN_180d2bc30(0);
      }
      lVar12 = *(longlong *)(lVar18 + *(longlong *)(lVar9 + 0x10));
      if (lVar15 == 0) goto LAB_180379ca3;
      if (*(uint *)(lVar15 + 0x18) <= uVar6) {
        FUN_180d2bc30(0);
      }
      lVar11 = *(longlong *)(lVar18 + *(longlong *)(lVar15 + 0x10));
      if ((lVar11 == 0) || (iVar5 = *(int *)(lVar11 + 0x14), lVar12 == 0)) goto LAB_180379ca3;
      if (*(int *)(lVar12 + 0x18) == 5) {
        if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar11 = FUN_1808ac390(0);
        if (lVar11 == 0) goto LAB_180379ca3;
        uVar4 = FUN_1808ac020(lVar11,*(undefined4 *)(lVar12 + 0x38),0);
        *(undefined4 *)(lVar12 + 0x38) = uVar4;
        lVar11 = FUN_1808ac390(0);
        if (lVar11 == 0) goto LAB_180379ca3;
        iVar5 = FUN_1808ac020(lVar11,iVar5,0);
        iStackX_20 = param_4 + *(int *)(lVar12 + 0x38);
        param_4 = iStackX_20;
      }
      if (iVar5 == 0) {
        uVar13 = (ulonglong)(uVar6 + 1);
        lVar18 = lVar18 + 8;
        uVar10 = param_5;
      }
      else {
        lVar12 = FUN_1800dd030(lVar15,uVar13,DAT_18222d498);
        if (lVar12 == 0) goto LAB_180379ca3;
        uVar4 = *(undefined4 *)(lVar12 + 0x10);
        uVar8 = thunk_FUN_180203bc0(DAT_18227af10);
        FUN_1804ab310(uVar8,uVar4,iVar5);
        uVar10 = param_5;
        if (param_5 == 0) goto LAB_180379ca3;
        FUN_1814cc490(param_5,uVar8);
        uVar13 = (ulonglong)(uVar6 + 1);
        lVar18 = lVar18 + 8;
        param_4 = iStackX_20;
      }
    }
    if (((*(byte *)(DAT_18223a4e8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18223a4e8 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uStack_98 = FUN_180d59ee0(0);
    uVar6 = FUN_180d59e30(&uStack_98,0);
    uVar13 = (ulonglong)uVar6;
    uStack_d0 = uVar6;
    lVar15 = thunk_FUN_180203bc0(DAT_18225e948);
    lStack_d8 = lVar15;
    FUN_1804a6cd0(lVar15,0);
    lStack_c0 = lVar15;
    if (lVar15 == 0) goto LAB_180379ca3;
    *(ulonglong *)(lVar15 + 0x28) = uVar10;
    thunk_FUN_180234e20((ulonglong *)(lVar15 + 0x28),uVar10);
    *(int *)(lVar15 + 0x18) = param_3;
    *(int *)(lVar15 + 0x14) = param_4;
    *(uint *)(lVar15 + 0x38) = uVar6;
    lVar15 = thunk_FUN_180203bc0(DAT_18227f4c8);
    lStack_c8 = lVar15;
    FUN_180f858b0(lVar15,DAT_182245b78);
    lStack_b8 = lVar15;
    if (param_2 == 0) goto LAB_180379ca3;
    uVar13 = FUN_1800dcbe0(0,DAT_182269c18,param_2);
    uStack_a0 = uVar13;
    while (iVar5 = 0, uVar13 != 0) {
      cVar3 = FUN_1800dcbe0(0,DAT_18223c7c8,uVar13);
      piVar2 = piStack_e0;
      if (cVar3 == '\0') {
        iStack_e8 = 0;
        *piStack_e0 = 0x183;
        lVar9 = lStack_d8;
        FUN_1800dcbe0(0,DAT_18223c790,uVar13);
        uVar13 = uStack_b0;
        if (uStack_b0 != 0) goto LAB_180379cb5;
        if (*piVar2 == 0x183) {
          iVar5 = -1;
          iStack_e8 = -1;
        }
        lStack_b8 = CONCAT44(lStack_b8._4_4_,iVar5);
        if (lVar15 == 0) goto LAB_180379ca3;
        iVar7 = *(int *)(lVar15 + 0x18);
        *(int *)(lVar9 + 0x24) = iVar7;
        if (iVar7 == 0) {
          iVar7 = 1;
        }
        param_5 = CONCAT44(param_5._4_4_,param_3 / iVar7);
        lVar9 = thunk_FUN_180203bc0(DAT_18227f5c0,(longlong)param_3 % (longlong)iVar7 & 0xffffffff);
        FUN_180268140(lVar9,0);
        lStack_90 = lVar9;
        if (((*(byte *)(DAT_182278de8 + 0x12f) & 2) != 0) && (*(int *)(DAT_182278de8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar18 = FUN_180790970(0);
        if (lVar18 == 0) goto LAB_180379ca3;
        lVar18 = *(longlong *)(lVar18 + 0x10);
        lStack_88 = lVar18;
        uVar10 = FUN_1800dcbe0(0,DAT_182269c18,param_2);
        lVar12 = lStack_d8;
        uStack_a0 = uVar10;
        goto LAB_1803798f0;
      }
      lVar9 = FUN_1800dcbe0(0,DAT_182269bd0,uVar13);
      uVar16 = 0;
      if ((lVar9 != 0) && (*(longlong *)(lVar9 + 0x78) != 0)) {
        uVar8 = *(undefined8 *)(*(longlong *)(lVar9 + 0x78) + 0x88);
        if (((*(byte *)(DAT_18225e928 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225e928 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar15 = *(longlong *)(*(longlong *)(DAT_18225e928 + 0xb8) + 8);
        if (lVar15 == 0) {
          if (((*(byte *)(DAT_18225e928 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225e928 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar14 = **(undefined8 **)(DAT_18225e928 + 0xb8);
          lVar15 = thunk_FUN_180203bc0(DAT_18227c3f8);
          FUN_1802a4990(lVar15,uVar14,DAT_182270c58);
          plVar17 = (longlong *)(*(longlong *)(DAT_18225e928 + 0xb8) + 8);
          *plVar17 = lVar15;
          thunk_FUN_180234e20(plVar17,lVar15);
        }
        cVar3 = FUN_180a7a480(uVar8,lVar15,DAT_18224c0c0);
        param_5 = param_5 & 0xffffffffffff0000;
        FUN_18108dff0(&param_5,cVar3 == '\0',DAT_182229650);
        lVar15 = lStack_c8;
        uVar16 = (undefined2)param_5;
      }
      cVar3 = (char)uVar16;
      if ((char)((ushort)uVar16 >> 8) == '\0') {
        cVar3 = '\0';
      }
      if (cVar3 != '\0') {
        if (lVar15 == 0) goto LAB_180379ca9;
        FUN_1814cc490(lVar15,lVar9,DAT_182245b30);
      }
    }
  }
  FUN_180237af0();
LAB_180379cb5:
  FUN_180237ac0(uVar13,0);
LAB_180379cc0:
  FUN_180237af0();
LAB_180379cc5:
  FUN_180237af0();
LAB_180379cca:
  FUN_180237af0();
LAB_180379ccf:
  FUN_180237af0();
LAB_180379cd4:
  FUN_180237af0();
LAB_180379cd9:
  FUN_180237af0();
LAB_180379cdf:
  FUN_180237ac0(uVar13,0);
LAB_180379cea:
  FUN_180237af0();
LAB_180379cef:
  FUN_180237af0();
LAB_180379cf4:
  uVar4 = FUN_180237af0();
  FUN_180237ac0(uVar4,0);
  pcVar1 = (code *)swi(3);
  lVar15 = (*pcVar1)();
  return lVar15;
LAB_1803798f0:
  if (uVar10 != 0) {
    cVar3 = FUN_1800dcbe0(0,DAT_18223c7c8,uVar10);
    uVar13 = uStack_b0;
    piVar2 = piStack_e0;
    if (cVar3 == '\0') {
      iVar7 = iVar5 + 1;
      piStack_e0[(longlong)(int)lStack_b8 + 1] = 0x260;
      iStack_e8 = iVar7;
      FUN_1800dcbe0(0,DAT_18223c790,uVar10);
      if (uVar13 != 0) goto LAB_180379cdf;
      if (((iVar7 != -1) && (piVar2[iVar7] == 0x260)) && (-1 < iVar7)) {
        iVar7 = iVar5;
      }
      uVar8 = thunk_FUN_180203bc0(DAT_18227f4c8);
      FUN_180f858b0(uVar8,DAT_182245b78);
      if (((*(byte *)(DAT_18227e2b0 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e2b0 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar15 = FUN_1805e5510(0);
      if ((lVar15 == 0) || (lVar15 = FUN_1805e4920(lVar15,0,0), lVar15 == 0)) goto LAB_180379ca3;
      FUN_1813a5750(&uStack_50,lVar15,DAT_182235db0);
      uStack_80 = CONCAT44(uStack_4c,uStack_50);
      uStack_78 = CONCAT44(uStack_44,uStack_48);
      uStack_70 = uStack_40;
      goto LAB_180379b80;
    }
    uVar13 = FUN_1800dcbe0(0,DAT_182269bd0,uVar10);
    cVar3 = FUN_1814cc980(lVar15,uVar13,DAT_18224ec78);
    if (cVar3 == '\0') {
      uVar8 = thunk_FUN_180203bc0(DAT_1822798c0);
      FUN_18067dd80(uVar8,uVar13,0);
      uVar14 = thunk_FUN_180203bc0(DAT_18225e908);
      FUN_1804a6a90(uVar14,uVar13,uVar8,0);
      lVar12 = lStack_d8;
      if (*(longlong *)(lStack_d8 + 0x30) == 0) goto LAB_180379cc0;
      FUN_1814cc490(*(longlong *)(lStack_d8 + 0x30),uVar14,DAT_182246f30);
      lVar15 = lStack_c8;
    }
    else {
      lVar15 = thunk_FUN_180203bc0(DAT_1822798c0);
      FUN_18067dd80(lVar15,uVar13,0);
      if (lVar15 == 0) goto LAB_180379cd4;
      iVar7 = FUN_18067f490(lVar15,0);
      FUN_18067fab0(lVar15,(int)param_5 + iVar7,0);
      if (lVar18 == 0) goto LAB_180379ccf;
      uVar8 = FUN_1800fc4a0(1,DAT_182278da0,lVar18,lVar15,uStack_d0,param_6);
      uVar14 = thunk_FUN_180203bc0(DAT_18225e908);
      FUN_1804a6a90(uVar14,uVar13,uVar8,0);
      if (*(longlong *)(lStack_d8 + 0x30) == 0) goto LAB_180379cca;
      FUN_1814cc490(*(longlong *)(lStack_d8 + 0x30),uVar14,DAT_182246f30);
      if (lVar9 == 0) goto LAB_180379cc5;
      FUN_18061e350(lVar9,uVar8,0);
      lVar15 = lStack_c8;
      lVar12 = lStack_d8;
    }
    goto LAB_1803798f0;
  }
  goto LAB_180379cd9;
LAB_180379b80:
  do {
    cVar3 = FUN_180a42760(&uStack_80,DAT_1822527e8);
    uVar8 = uStack_70;
    if (cVar3 == '\0') {
      piStack_e0[(longlong)iVar7 + 1] = 0x2d5;
      FUN_1802698f0(&uStack_80,DAT_18224c520);
      *(undefined *)(lVar12 + 0x10) = 1;
      return lVar12;
    }
    cVar3 = FUN_180a7b440(param_2,uStack_70,DAT_18224a9a0);
  } while (cVar3 != '\0');
  lVar15 = thunk_FUN_180203bc0(DAT_1822798c0);
  FUN_18067dd80(lVar15,uVar8,0);
  if (lVar15 == 0) goto LAB_180379cf4;
  iVar5 = FUN_18067f490(lVar15,0);
  FUN_18067fab0(lVar15,(int)param_5 + iVar5,0);
  if (lVar18 == 0) goto LAB_180379cef;
  uVar8 = FUN_1800fc4a0(1,DAT_182278da0,lVar18,lVar15,uStack_d0,0);
  if (lVar9 == 0) goto LAB_180379cea;
  FUN_18061e350(lVar9,uVar8,0);
  goto LAB_180379b80;
}



/====================================================================/
/* BattleSkillUpInformation
 ===================================================================/

/********************************************************************/
/* BattleSkillUpInformation$$get_AP
 * RVA: 0x31E230
 * Address: 0x18031E230
 *******************************************************************/


undefined4 BattleSkillUpInformation_get_AP(longlong param_1)

{
  return *(undefined4 *)(param_1 + 0x1c);
}



/********************************************************************/
/* BattleSkillUpInformation$$get_BattleActLogDataList
 * RVA: 0x272330
 * Address: 0x180272330
 *******************************************************************/


undefined8 FUN_180272330(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x10);
}



/********************************************************************/
/* BattleSkillUpInformation$$get_MagicPoint
 * RVA: 0x298C00
 * Address: 0x180298C00
 *******************************************************************/


undefined4 FUN_180298c00(longlong param_1)

{
  return *(undefined4 *)(param_1 + 0x20);
}



/********************************************************************/
/* BattleSkillUpInformation$$get_MonsterAverageRank
 * RVA: 0x29C1A0
 * Address: 0x18029C1A0
 *******************************************************************/


undefined4 BattleSkillUpInformation_get_MonsterAverageRank(longlong param_1)

{
  return *(undefined4 *)(param_1 + 0x18);
}



/====================================================================/
/* StatusUpProvider
 ===================================================================/

/********************************************************************/
/* StatusUpProvider$$.cctor
 * RVA: 0x478370
 * Address: 0x180478370
 *******************************************************************/


void FUN_180478370(void)

{
  code *pcVar1;
  longlong lVar2;
  longlong *plVar3;
  
  if (DAT_181f6f2fd == '\0') {
    thunk_FUN_1801fef70(DAT_18176c524);
    DAT_181f6f2fd = '\x01';
  }
  lVar2 = thunk_FUN_180203bc0(DAT_18225d000);
  FUN_1812c6a20(lVar2,DAT_182257e38);
  if (lVar2 != 0) {
    FUN_1812b1b00(lVar2,1,0,DAT_182257e28);
    FUN_1812b1b00(lVar2,5,1,DAT_182257e28);
    FUN_1812b1b00(lVar2,6,2,DAT_182257e28);
    FUN_1812b1b00(lVar2,8,3,DAT_182257e28);
    FUN_1812b1b00(lVar2,10,4,DAT_182257e28);
    FUN_1812b1b00(lVar2,0xc,5,DAT_182257e28);
    FUN_1812b1b00(lVar2,0x2b,7,DAT_182257e28);
    plVar3 = *(longlong **)(DAT_18225d108 + 0xb8);
    *plVar3 = lVar2;
    thunk_FUN_180234e20(plVar3,lVar2);
    lVar2 = thunk_FUN_180203bc0(DAT_18227f6f0);
    FUN_1812c6a20(lVar2,DAT_182255c98);
    if (lVar2 != 0) {
      FUN_1812b1b00(lVar2,4,0x2d,DAT_182255bd0);
      FUN_1812b1b00(lVar2,8,0x19,DAT_182255bd0);
      FUN_1812b1b00(lVar2,9,0xf,DAT_182255bd0);
      FUN_1812b1b00(lVar2,6,0xff,DAT_182255bd0);
      FUN_1812b1b00(lVar2,5,9,DAT_182255bd0);
      FUN_1812b1b00(lVar2,0xe,9,DAT_182255bd0);
      FUN_1812b1b00(lVar2,2,9,DAT_182255bd0);
      FUN_1812b1b00(lVar2,3,9,DAT_182255bd0);
      plVar3 = (longlong *)(*(longlong *)(DAT_18225d108 + 0xb8) + 8);
      *plVar3 = lVar2;
      thunk_FUN_180234e20(plVar3,lVar2);
      lVar2 = thunk_FUN_180203bc0(DAT_18227f6f0);
      FUN_1812c6a20(lVar2,DAT_182255c98);
      if (lVar2 != 0) {
        FUN_1812b1b00(lVar2,4,1,DAT_182255bd0);
        FUN_1812b1b00(lVar2,8,1,DAT_182255bd0);
        FUN_1812b1b00(lVar2,9,1,DAT_182255bd0);
        FUN_1812b1b00(lVar2,6,1,DAT_182255bd0);
        FUN_1812b1b00(lVar2,5,1,DAT_182255bd0);
        FUN_1812b1b00(lVar2,0xe,1,DAT_182255bd0);
        plVar3 = (longlong *)(*(longlong *)(DAT_18225d108 + 0xb8) + 0x10);
        *plVar3 = lVar2;
        thunk_FUN_180234e20(plVar3,lVar2);
        return;
      }
    }
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* StatusUpProvider$$CalcAdditionalParameterValue
 * RVA: 0x474A00
 * Address: 0x180474A00
 *******************************************************************/


ulonglong FUN_180474a00(undefined8 param_1,int param_2,int param_3,int param_4,char param_5)

{
  longlong lVar1;
  bool bVar2;
  code *pcVar3;
  int iVar4;
  ulonglong uVar5;
  int local_res10 [2];
  uint local_18 [4];
  
  if (DAT_181f6f2fb == '\0') {
    thunk_FUN_1801fef70(DAT_18176c414);
    DAT_181f6f2fb = '\x01';
  }
  local_res10[0] = 0;
  if (((*(byte *)(DAT_18225d108 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d108 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_18225d108);
  }
  lVar1 = *(longlong *)(*(longlong *)(DAT_18225d108 + 0xb8) + 8);
  if (lVar1 != 0) {
    FUN_1813c22b0(lVar1,param_2,local_res10,DAT_182256af0);
    if ((param_2 != 6) && (param_4 < local_res10[0])) {
      local_res10[0] = param_4;
    }
    iVar4 = FUN_180facee0(0,local_res10[0] + 1,0);
    if (param_5 == '\0') {
      bVar2 = iVar4 < param_3;
    }
    else {
      bVar2 = param_3 <= iVar4;
    }
    if (!bVar2) {
      return 0;
    }
    local_18[0] = 0;
    if (((*(byte *)(DAT_18225d108 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d108 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18225d108);
    }
    lVar1 = *(longlong *)(*(longlong *)(DAT_18225d108 + 0xb8) + 0x10);
    if (lVar1 != 0) {
      FUN_1813c22b0(lVar1,param_2,local_18,DAT_182256af0);
      return (ulonglong)local_18[0];
    }
  }
  FUN_180237af0();
  pcVar3 = (code *)swi(3);
  uVar5 = (*pcVar3)();
  return uVar5;
}



/********************************************************************/
/* StatusUpProvider$$Execution
 * RVA: 0x477620
 * Address: 0x180477620
 *******************************************************************/


longlong StatusUpProvider_Execution
                   (longlong param_1,undefined8 param_2,int param_3,longlong param_4)

{
  code *pcVar1;
  int iVar2;
  int iVar3;
  undefined4 uVar4;
  longlong lVar5;
  longlong lVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  undefined8 uVar9;
  longlong *plVar10;
  
  if (DAT_181f6f2f2 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c4d8);
    DAT_181f6f2f2 = '\x01';
  }
  lVar5 = thunk_FUN_180203bc0(DAT_18225d1a8);
  FUN_180268140(lVar5,0);
  if (lVar5 != 0) {
    *(undefined8 *)(lVar5 + 0x10) = param_2;
    thunk_FUN_180234e20(lVar5 + 0x10,param_2);
    lVar6 = *(longlong *)(lVar5 + 0x10);
    if (param_4 == 0) {
      return lVar6;
    }
    if (lVar6 != 0) {
      iVar2 = FUN_18067f930(lVar6,0);
      if ((*(longlong *)(lVar5 + 0x10) != 0) &&
         (plVar10 = *(longlong **)(*(longlong *)(lVar5 + 0x10) + 0x78), plVar10 != (longlong *)0x0))
      {
        iVar3 = (**(code **)(*plVar10 + 0x1c0))(plVar10,*(undefined8 *)(*plVar10 + 0x1c8));
        FUN_180facea0(iVar3 * iVar2 * param_3,0);
        if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar4 = FUN_180383970(DAT_1822570d8,0);
        *(undefined4 *)(param_1 + 0x10) = uVar4;
        uVar4 = FUN_180383970(DAT_182275b98,0);
        *(undefined4 *)(param_1 + 0x14) = uVar4;
        uVar4 = *(undefined4 *)(param_4 + 0x18);
        uVar7 = *(undefined8 *)(param_4 + 0x10);
        if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar6 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 8);
        if (lVar6 == 0) {
          if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar8 = **(undefined8 **)(DAT_18225d198 + 0xb8);
          lVar6 = thunk_FUN_180203bc0(DAT_18227b6a0);
          FUN_1802a4990(lVar6,uVar8,DAT_18226fe88,DAT_1822342f0);
          plVar10 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 8);
          *plVar10 = lVar6;
          thunk_FUN_180234e20(plVar10,lVar6);
        }
        uVar7 = FUN_1803fd610(uVar7,lVar6,DAT_18223dba0);
        uVar8 = thunk_FUN_180203bc0(DAT_18227b6a0);
        FUN_1802a4990(uVar8,lVar5,DAT_18226fb30,DAT_1822342f0);
        uVar8 = FUN_1803fd610(uVar7,uVar8,DAT_18223dba0);
        FUN_180476c30(param_1,*(undefined8 *)(lVar5 + 0x10),uVar8,uVar4,0);
        FUN_180475d80(param_1,*(undefined8 *)(lVar5 + 0x10),uVar8,uVar4,0);
        uVar7 = *(undefined8 *)(param_4 + 0x10);
        if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar6 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x10);
        if (lVar6 == 0) {
          if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar9 = **(undefined8 **)(DAT_18225d198 + 0xb8);
          lVar6 = thunk_FUN_180203bc0(DAT_18227b6a0);
          FUN_1802a4990(lVar6,uVar9,DAT_18226fe38,DAT_1822342f0);
          plVar10 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x10);
          *plVar10 = lVar6;
          thunk_FUN_180234e20(plVar10,lVar6);
        }
        uVar7 = FUN_1803fd610(uVar7,lVar6,DAT_18223dba0);
        uVar9 = thunk_FUN_180203bc0(DAT_18227b6a0);
        FUN_1802a4990(uVar9,lVar5,DAT_18226fb10,DAT_1822342f0);
        uVar9 = FUN_1803fd610(uVar7,uVar9,DAT_18223dba0);
        FUN_180a7a340(uVar7,DAT_18224c5b8);
        if (*(longlong *)(lVar5 + 0x10) != 0) {
          iVar2 = FUN_18067f8f0(*(longlong *)(lVar5 + 0x10),0);
          FUN_180476980(param_1,*(undefined8 *)(lVar5 + 0x10),uVar9,uVar4,
                        iVar2 == *(int *)(param_4 + 0x24),0);
          FUN_1804759a0(param_1,*(undefined8 *)(lVar5 + 0x10),uVar9,uVar4,0);
          FUN_1804751f0(param_1,*(undefined8 *)(lVar5 + 0x10),uVar8,0);
          return *(longlong *)(lVar5 + 0x10);
        }
      }
    }
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  lVar5 = (*pcVar1)();
  return lVar5;
}



/********************************************************************/
/* StatusUpProvider$$ExecutionParameterUp
 * RVA: 0x4751F0
 * Address: 0x1804751F0
 *******************************************************************/


void FUN_1804751f0(undefined8 param_1,longlong param_2,undefined8 param_3)

{
  undefined8 uVar1;
  code *pcVar2;
  undefined4 uVar3;
  undefined4 uVar4;
  int iVar5;
  int iVar6;
  int iVar7;
  longlong lVar8;
  longlong lVar9;
  longlong *plVar10;
  
  if (DAT_181f6f2f8 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c458);
    DAT_181f6f2f8 = '\x01';
  }
  if (((*(byte *)(DAT_18227b858 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227b858 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar8 = FUN_1804818f0(0);
  if ((param_2 != 0) && (uVar3 = FUN_18067fa90(param_2,0), lVar8 != 0)) {
    uVar3 = FUN_1804816d0(lVar8,uVar3,0);
    lVar8 = FUN_1804818f0(0);
    uVar4 = FUN_18067fa90(param_2,0);
    if (lVar8 != 0) {
      iVar5 = FUN_180481740(lVar8,uVar4,0);
      if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
        il2cpp_runtime_class_init(DAT_18225d198);
      }
      lVar8 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x70);
      if (lVar8 == 0) {
        if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18225d198);
        }
        uVar1 = **(undefined8 **)(DAT_18225d198 + 0xb8);
        lVar8 = thunk_FUN_180203bc0(DAT_18225d078);
        FUN_1802a4990(lVar8,uVar1,DAT_1822297f8,DAT_1822342c0);
        plVar10 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x70);
        *plVar10 = lVar8;
        thunk_FUN_180234e20(plVar10,lVar8);
      }
      iVar6 = FUN_180bb0f00(param_3,lVar8,DAT_182278438);
      FUN_180474b40(param_1,param_2,uVar3,0);
      FUN_180474ed0(param_1,param_2,iVar6 + iVar5,0);
      if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar8 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x78);
      if (lVar8 == 0) {
        if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar1 = **(undefined8 **)(DAT_18225d198 + 0xb8);
        lVar8 = thunk_FUN_180203bc0(DAT_18227b6a0);
        FUN_1802a4990(lVar8,uVar1,DAT_18226fe28,DAT_1822342f0);
        plVar10 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x78);
        *plVar10 = lVar8;
        thunk_FUN_180234e20(plVar10,lVar8);
      }
      uVar3 = FUN_180bb05a0(param_3,lVar8,DAT_18227a070);
      if (*(longlong *)(param_2 + 0x78) != 0) {
        iVar5 = FUN_180a1e3e0(*(longlong *)(param_2 + 0x78),0);
        if (DAT_181f6f2c4 == '\0') {
          thunk_FUN_1801fef70(DAT_1817deee8);
          DAT_181f6f2c4 = '\x01';
        }
        if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        iVar6 = FUN_180383970(DAT_182275ea8,0);
        if (iVar5 < iVar6) {
          uVar3 = FUN_180474a00(param_1,4,uVar3,iVar5,0,0);
          lVar8 = *(longlong *)(param_2 + 0x78);
          if (lVar8 == 0) goto LAB_180475994;
          iVar5 = FUN_180a20430(lVar8,0);
          if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          lVar9 = FUN_1808ac390(0);
          if (lVar9 == 0) goto LAB_180475994;
          iVar6 = FUN_1808ac2e0(lVar9,uVar3,0);
          FUN_180a211f0(lVar8,iVar6 + iVar5,0);
        }
        if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar8 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x80);
        if (lVar8 == 0) {
          if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar1 = **(undefined8 **)(DAT_18225d198 + 0xb8);
          lVar8 = thunk_FUN_180203bc0(DAT_18227b6a0);
          FUN_1802a4990(lVar8,uVar1,DAT_18226fde0,DAT_1822342f0);
          plVar10 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x80);
          *plVar10 = lVar8;
          thunk_FUN_180234e20(plVar10,lVar8);
        }
        uVar3 = FUN_180bb05a0(param_3,lVar8,DAT_18227a070);
        if (*(longlong *)(param_2 + 0x78) != 0) {
          iVar5 = FUN_180a1de90(*(longlong *)(param_2 + 0x78),0);
          if (DAT_181f6f2c4 == '\0') {
            thunk_FUN_1801fef70(DAT_1817deee8);
            DAT_181f6f2c4 = '\x01';
          }
          if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          iVar6 = FUN_180383970(DAT_182275e58,0);
          if (iVar5 < iVar6) {
            uVar3 = FUN_180474a00(param_1,8,uVar3,iVar5,0,0);
            lVar8 = *(longlong *)(param_2 + 0x78);
            if (lVar8 == 0) goto LAB_180475994;
            iVar5 = FUN_180a20340(lVar8,0);
            if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18227e218 + 0xe0) == 0)) {
              il2cpp_runtime_class_init();
            }
            lVar9 = FUN_1808ac390(0);
            if (lVar9 == 0) goto LAB_180475994;
            iVar6 = FUN_1808ac2e0(lVar9,uVar3,0);
            FUN_180a21100(lVar8,iVar6 + iVar5,0);
          }
          if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          lVar8 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x88);
          if (lVar8 == 0) {
            if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
              il2cpp_runtime_class_init();
            }
            uVar1 = **(undefined8 **)(DAT_18225d198 + 0xb8);
            lVar8 = thunk_FUN_180203bc0(DAT_18227b6a0);
            FUN_1802a4990(lVar8,uVar1,DAT_18226fdb0,DAT_1822342f0);
            plVar10 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x88);
            *plVar10 = lVar8;
            thunk_FUN_180234e20(plVar10,lVar8);
          }
          uVar3 = FUN_180bb05a0(param_3,lVar8,DAT_18227a070);
          if (*(longlong *)(param_2 + 0x78) != 0) {
            iVar5 = FUN_180a1e4d0(*(longlong *)(param_2 + 0x78),0);
            if (DAT_181f6f2c4 == '\0') {
              thunk_FUN_1801fef70(DAT_1817deee8);
              DAT_181f6f2c4 = '\x01';
            }
            if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18227e378 + 0xe0) == 0)) {
              il2cpp_runtime_class_init();
            }
            iVar6 = FUN_180383970(DAT_182275e20,0);
            if (iVar5 < iVar6) {
              uVar3 = FUN_180474a00(param_1,9,uVar3,iVar5,0,0);
              lVar8 = *(longlong *)(param_2 + 0x78);
              if (lVar8 == 0) goto LAB_180475994;
              iVar5 = FUN_180a20450(lVar8,0);
              if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18227e218 + 0xe0) == 0)) {
                il2cpp_runtime_class_init();
              }
              lVar9 = FUN_1808ac390(0);
              if (lVar9 == 0) goto LAB_180475994;
              iVar6 = FUN_1808ac2e0(lVar9,uVar3,0);
              FUN_180a21210(lVar8,iVar6 + iVar5,0);
            }
            plVar10 = *(longlong **)(param_2 + 0x78);
            if (plVar10 != (longlong *)0x0) {
              iVar5 = (**(code **)(*plVar10 + 0x270))(plVar10,0,*(undefined8 *)(*plVar10 + 0x278));
              if (DAT_181f6f2c4 == '\0') {
                thunk_FUN_1801fef70(DAT_1817deee8);
                DAT_181f6f2c4 = '\x01';
              }
              if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18227e378 + 0xe0) == 0)) {
                il2cpp_runtime_class_init();
              }
              iVar6 = FUN_180383970(DAT_182275b60,0);
              if (*(longlong *)(param_2 + 0x78) != 0) {
                iVar7 = FUN_180a1d880(*(longlong *)(param_2 + 0x78),0);
                if (iVar6 <= iVar7) {
                  return;
                }
                uVar3 = FUN_180474a00(param_1,6,(int)((iVar5 >> 0x1f & 3U) + iVar5) >> 2,0,0,0);
                lVar8 = *(longlong *)(param_2 + 0x78);
                if (lVar8 != 0) {
                  iVar5 = FUN_180a20220(lVar8,0);
                  if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) &&
                     (*(int *)(DAT_18227e218 + 0xe0) == 0)) {
                    il2cpp_runtime_class_init();
                  }
                  lVar9 = FUN_1808ac390(0);
                  if (lVar9 != 0) {
                    iVar6 = FUN_1808ac2e0(lVar9,uVar3,0);
                    FUN_180a20fe0(lVar8,iVar6 + iVar5,0);
                    return;
                  }
                }
              }
            }
          }
        }
      }
    }
  }
LAB_180475994:
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/********************************************************************/
/* StatusUpProvider$$ExecutionParameterUpHp
 * RVA: 0x474B40
 * Address: 0x180474B40
 *******************************************************************/


void FUN_180474b40(undefined8 param_1,longlong param_2,int param_3)

{
  longlong *plVar1;
  code *pcVar2;
  bool bVar3;
  int iVar4;
  int iVar5;
  undefined4 uVar6;
  longlong lVar7;
  longlong lVar8;
  int local_res18 [4];
  
  if (DAT_181f6f2f9 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c428);
    DAT_181f6f2f9 = '\x01';
  }
  local_res18[0] = 0;
  if (param_3 < 1) {
LAB_180474c1a:
    bVar3 = false;
    if (((*(byte *)(DAT_18227e2b0 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e2b0 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar7 = FUN_1805e5510(0);
    if ((lVar7 == 0) || (*(longlong *)(lVar7 + 0xa8) == 0)) goto LAB_180474ec7;
    if (*(char *)(*(longlong *)(lVar7 + 0xa8) + 0x20) == '\0') {
      return;
    }
    if (param_2 == 0) goto LAB_180474ec7;
    iVar4 = *(int *)(param_2 + 0x98) + 1;
    if (iVar4 < 10) {
      iVar5 = 0;
      if (SBORROW4(iVar4,10) != *(int *)(param_2 + 0x98) + -9 < 0) {
        iVar5 = iVar4;
      }
      *(int *)(param_2 + 0x98) = iVar5;
      return;
    }
    *(undefined4 *)(param_2 + 0x98) = 0;
  }
  else {
    if (((*(byte *)(DAT_18225d108 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d108 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18225d108);
    }
    lVar7 = *(longlong *)(*(longlong *)(DAT_18225d108 + 0xb8) + 8);
    if (((lVar7 == 0) || (FUN_1813c22b0(lVar7,2,local_res18,DAT_182256af0), param_2 == 0)) ||
       (plVar1 = *(longlong **)(param_2 + 0x78), plVar1 == (longlong *)0x0)) goto LAB_180474ec7;
    iVar4 = (**(code **)(*plVar1 + 0x180))(plVar1,*(undefined8 *)(*plVar1 + 0x188));
    iVar5 = FUN_180facee0(0,local_res18[0] + 1,0);
    if (iVar5 < iVar4 / param_3) goto LAB_180474c1a;
    bVar3 = true;
  }
  plVar1 = *(longlong **)(param_2 + 0x78);
  if (plVar1 != (longlong *)0x0) {
    uVar6 = (**(code **)(*plVar1 + 0x1b0))(plVar1,*(undefined8 *)(*plVar1 + 0x1b8));
    if (((*(byte *)(DAT_18222f490 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f490 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar6 = FUN_180f99de0(uVar6,99);
    if (DAT_181f6f2c4 == '\0') {
      thunk_FUN_1801fef70(DAT_1817deee8);
      DAT_181f6f2c4 = '\x01';
    }
    if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    iVar4 = FUN_180383970(DAT_182275f10,0);
    if (*(longlong *)(param_2 + 0x78) != 0) {
      iVar5 = FUN_180a1e190(*(longlong *)(param_2 + 0x78),0);
      if (iVar5 < iVar4) {
        lVar7 = *(longlong *)(param_2 + 0x78);
        if (lVar7 == 0) goto LAB_180474ec7;
        iVar4 = FUN_180a203f0(lVar7,0);
        if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar8 = FUN_1808ac390(0);
        if (lVar8 == 0) goto LAB_180474ec7;
        iVar5 = FUN_1808ac2e0(lVar8,uVar6,0);
        FUN_180a211b0(lVar7,iVar5 + iVar4,0);
      }
      if (!bVar3) {
        return;
      }
      if (DAT_181f6f2c4 == '\0') {
        thunk_FUN_1801fef70(DAT_1817deee8);
        DAT_181f6f2c4 = '\x01';
      }
      if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      iVar4 = FUN_180383970(DAT_182275e78,0);
      if (*(longlong *)(param_2 + 0x78) != 0) {
        iVar5 = FUN_180a1e580(*(longlong *)(param_2 + 0x78),0);
        if (iVar4 <= iVar5) {
          return;
        }
        if (((*(byte *)(DAT_18225d108 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d108 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18225d108);
        }
        lVar7 = *(longlong *)(*(longlong *)(DAT_18225d108 + 0xb8) + 0x10);
        if (lVar7 != 0) {
          uVar6 = FUN_1814145c0(lVar7,5,DAT_182227260);
          lVar7 = *(longlong *)(param_2 + 0x78);
          if (lVar7 != 0) {
            iVar4 = FUN_180a20470(lVar7,0);
            if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18227e218 + 0xe0) == 0)) {
              il2cpp_runtime_class_init();
            }
            lVar8 = FUN_1808ac390(0);
            if (lVar8 != 0) {
              iVar5 = FUN_1808ac2e0(lVar8,uVar6,0);
              FUN_180a21230(lVar7,iVar5 + iVar4,0);
              return;
            }
          }
        }
      }
    }
  }
LAB_180474ec7:
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/********************************************************************/
/* StatusUpProvider$$ExecutionParameterUpMp
 * RVA: 0x474ED0
 * Address: 0x180474ED0
 *******************************************************************/


void FUN_180474ed0(undefined8 param_1,longlong param_2,int param_3)

{
  longlong lVar1;
  longlong *plVar2;
  code *pcVar3;
  int iVar4;
  int iVar5;
  undefined4 uVar6;
  longlong lVar7;
  int local_res18 [2];
  
  if (DAT_181f6f2fa == '\0') {
    thunk_FUN_1801fef70(DAT_18176c444);
    DAT_181f6f2fa = '\x01';
  }
  if (param_3 < 1) {
    return;
  }
  local_res18[0] = 0;
  if (((*(byte *)(DAT_18225d108 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d108 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_18225d108);
  }
  lVar1 = *(longlong *)(*(longlong *)(DAT_18225d108 + 0xb8) + 8);
  if (((lVar1 != 0) && (FUN_1813c22b0(lVar1,3,local_res18,DAT_182256af0), param_2 != 0)) &&
     (plVar2 = *(longlong **)(param_2 + 0x78), plVar2 != (longlong *)0x0)) {
    iVar4 = (**(code **)(*plVar2 + 400))(plVar2,*(undefined8 *)(*plVar2 + 0x198));
    iVar5 = FUN_180facee0(0,local_res18[0] + 1,0);
    if (iVar5 < iVar4 / param_3) {
      return;
    }
    plVar2 = *(longlong **)(param_2 + 0x78);
    if (plVar2 != (longlong *)0x0) {
      uVar6 = (**(code **)(*plVar2 + 0x240))(plVar2,*(undefined8 *)(*plVar2 + 0x248));
      if (((*(byte *)(DAT_18222f490 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f490 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      uVar6 = FUN_180f99de0(uVar6,99);
      if (DAT_181f6f2c4 == '\0') {
        thunk_FUN_1801fef70(DAT_1817deee8);
        DAT_181f6f2c4 = '\x01';
      }
      if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      iVar4 = FUN_180383970(DAT_182275ec8,0);
      if (*(longlong *)(param_2 + 0x78) != 0) {
        iVar5 = FUN_180a1e330(*(longlong *)(param_2 + 0x78),0);
        if (iVar5 < iVar4) {
          lVar1 = *(longlong *)(param_2 + 0x78);
          if (lVar1 == 0) goto LAB_1804751e1;
          iVar4 = FUN_180a20410(lVar1,0);
          if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          lVar7 = FUN_1808ac390(0);
          if (lVar7 == 0) goto LAB_1804751e1;
          iVar5 = FUN_1808ac2e0(lVar7,uVar6,0);
          FUN_180a211d0(lVar1,iVar5 + iVar4,0);
        }
        if (DAT_181f6f2c4 == '\0') {
          thunk_FUN_1801fef70(DAT_1817deee8);
          DAT_181f6f2c4 = '\x01';
        }
        if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        iVar4 = FUN_180383970(DAT_182275d10,0);
        if (*(longlong *)(param_2 + 0x78) != 0) {
          iVar5 = FUN_180a1e0a0(*(longlong *)(param_2 + 0x78),0);
          if (iVar4 <= iVar5) {
            return;
          }
          if (((*(byte *)(DAT_18225d108 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d108 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_18225d108);
          }
          lVar1 = *(longlong *)(*(longlong *)(DAT_18225d108 + 0xb8) + 0x10);
          if (lVar1 != 0) {
            uVar6 = FUN_1814145c0(lVar1,0xe,DAT_182227260);
            lVar1 = *(longlong *)(param_2 + 0x78);
            if (lVar1 != 0) {
              iVar4 = FUN_180a203d0(lVar1,0);
              if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18227e218 + 0xe0) == 0)) {
                il2cpp_runtime_class_init();
              }
              lVar7 = FUN_1808ac390(0);
              if (lVar7 != 0) {
                iVar5 = FUN_1808ac2e0(lVar7,uVar6,0);
                FUN_180a21190(lVar1,iVar5 + iVar4,0);
                return;
              }
            }
          }
        }
      }
    }
  }
LAB_1804751e1:
  FUN_180237af0();
  pcVar3 = (code *)swi(3);
  (*pcVar3)();
  return;
}



/********************************************************************/
/* StatusUpProvider$$ExecutionSkillUpAbilityAvoidance
 * RVA: 0x4759A0
 * Address: 0x1804759A0
 *******************************************************************/


void FUN_1804759a0(longlong param_1,longlong param_2,undefined8 param_3,int param_4)

{
  undefined8 uVar1;
  code *pcVar2;
  int iVar3;
  int iVar4;
  undefined4 uVar5;
  longlong lVar6;
  undefined8 uVar7;
  longlong *plVar8;
  int iVar9;
  int local_res18 [2];
  
  if (DAT_181f6f2f7 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c47c);
    DAT_181f6f2f7 = '\x01';
  }
  if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar6 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x58);
  if (lVar6 == 0) {
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar7 = **(undefined8 **)(DAT_18225d198 + 0xb8);
    lVar6 = thunk_FUN_180203bc0(DAT_18227b6a0);
    FUN_1802a4990(lVar6,uVar7,DAT_18226fd88,DAT_1822342f0);
    plVar8 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x58);
    *plVar8 = lVar6;
    thunk_FUN_180234e20(plVar8,lVar6);
  }
  uVar7 = FUN_1803fd610(param_3,lVar6,DAT_18223dba0);
  if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_18225d198);
  }
  lVar6 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x60);
  if (lVar6 == 0) {
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18225d198);
    }
    uVar1 = **(undefined8 **)(DAT_18225d198 + 0xb8);
    lVar6 = thunk_FUN_180203bc0(DAT_18227b6a0);
    FUN_1802a4990(lVar6,uVar1,DAT_18226fd40,DAT_1822342f0);
    plVar8 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x60);
    *plVar8 = lVar6;
    thunk_FUN_180234e20(plVar8,lVar6);
  }
  uVar7 = FUN_1803fd610(uVar7,lVar6,DAT_18223dba0);
  if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_18225d198);
  }
  lVar6 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x68);
  if (lVar6 == 0) {
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18225d198);
    }
    uVar1 = **(undefined8 **)(DAT_18225d198 + 0xb8);
    lVar6 = thunk_FUN_180203bc0(DAT_18227b6a0);
    FUN_1802a4990(lVar6,uVar1,DAT_18226fd20,DAT_1822342f0);
    plVar8 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x68);
    *plVar8 = lVar6;
    thunk_FUN_180234e20(plVar8,lVar6);
  }
  uVar7 = FUN_1803fd610(uVar7,lVar6,DAT_18223dba0);
  iVar3 = FUN_180bb03c0(uVar7,DAT_18227a098);
  if (iVar3 != 0) {
    local_res18[0] = 0;
    if ((param_2 != 0) && (*(longlong *)(param_2 + 0x58) != 0)) {
      FUN_1813c22b0(*(longlong *)(param_2 + 0x58),9,local_res18,DAT_182258028);
      plVar8 = *(longlong **)(param_2 + 0x78);
      iVar9 = local_res18[0] / 100 + 1;
      if (plVar8 != (longlong *)0x0) {
        iVar4 = (**(code **)(*plVar8 + 0x2d0))(plVar8,*(undefined8 *)(*plVar8 + 0x2d8));
        if ((*(int *)(param_1 + 0x14) <= iVar9) || (*(int *)(param_1 + 0x14) <= iVar4)) {
          return;
        }
        if (((*(byte *)(DAT_18222f490 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f490 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar5 = FUN_180f99dd0((iVar3 - iVar9) + param_4 + 4,0,0);
        if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar6 = FUN_1808ac390(0);
        if (lVar6 != 0) {
          iVar3 = FUN_1808ac180(lVar6,uVar5,0);
          if (100 < local_res18[0] % 100 + iVar3) {
            iVar3 = 100 - local_res18[0] % 100;
          }
          local_res18[0] = local_res18[0] + iVar3;
          if (*(longlong *)(param_2 + 0x58) != 0) {
            FUN_1812c9b00(*(longlong *)(param_2 + 0x58),9,local_res18[0],DAT_182259798);
            return;
          }
        }
      }
    }
    FUN_180237af0();
    pcVar2 = (code *)swi(3);
    (*pcVar2)();
    return;
  }
  return;
}



/********************************************************************/
/* StatusUpProvider$$ExecutionSkillUpPhysicalAvoidance
 * RVA: 0x476980
 * Address: 0x180476980
 *******************************************************************/


void FUN_180476980(longlong param_1,longlong param_2,undefined8 param_3,int param_4,char param_5)

{
  code *pcVar1;
  int iVar2;
  int iVar3;
  undefined4 uVar4;
  longlong lVar5;
  undefined8 uVar6;
  longlong *plVar7;
  int iVar8;
  int local_res18 [2];
  
  if (DAT_181f6f2f6 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c49c);
    DAT_181f6f2f6 = '\x01';
  }
  if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar5 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x50);
  if (lVar5 == 0) {
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar6 = **(undefined8 **)(DAT_18225d198 + 0xb8);
    lVar5 = thunk_FUN_180203bc0(DAT_18227b6a0);
    FUN_1802a4990(lVar5,uVar6,DAT_18226fc90,DAT_1822342f0);
    plVar7 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x50);
    *plVar7 = lVar5;
    thunk_FUN_180234e20(plVar7,lVar5);
  }
  uVar6 = FUN_1803fd610(param_3,lVar5,DAT_18223dba0);
  iVar2 = FUN_180bb03c0(uVar6,DAT_18227a098);
  if (param_5 == '\0') {
    local_res18[0] = 0;
    if ((param_2 != 0) && (*(longlong *)(param_2 + 0x58) != 0)) {
      FUN_1813c22b0(*(longlong *)(param_2 + 0x58),8,local_res18,DAT_182258028);
      plVar7 = *(longlong **)(param_2 + 0x78);
      iVar8 = local_res18[0] / 100 + 1;
      if (plVar7 != (longlong *)0x0) {
        iVar3 = (**(code **)(*plVar7 + 0x310))(plVar7,*(undefined8 *)(*plVar7 + 0x318));
        if (*(int *)(param_1 + 0x10) <= iVar8) {
          return;
        }
        if (*(int *)(param_1 + 0x10) <= iVar3) {
          return;
        }
        if (((*(byte *)(DAT_18222f490 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f490 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar4 = FUN_180f99dd0((iVar2 - iVar8) + param_4 + -3,0,0);
        if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar5 = FUN_1808ac390(0);
        if (lVar5 != 0) {
          iVar2 = FUN_1808ac2e0(lVar5,uVar4,0);
          if (100 < local_res18[0] % 100 + iVar2) {
            iVar2 = 100 - local_res18[0] % 100;
          }
          lVar5 = *(longlong *)(param_2 + 0x58);
          iVar2 = local_res18[0] + iVar2;
          local_res18[0] = iVar2;
          if (lVar5 != 0) goto LAB_180476bc6;
        }
      }
    }
  }
  else if ((param_2 != 0) && (lVar5 = *(longlong *)(param_2 + 0x58), lVar5 != 0)) {
    iVar2 = FUN_1813c8070(lVar5,8,DAT_182228338);
    iVar2 = iVar2 + 1;
LAB_180476bc6:
    FUN_1812c9b00(lVar5,8,iVar2,DAT_182259798);
    return;
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* StatusUpProvider$$ExecutionSkillUpWeapon
 * RVA: 0x476C30
 * Address: 0x180476C30
 *******************************************************************/


void FUN_180476c30(undefined8 param_1,longlong param_2,undefined8 param_3,int param_4)

{
  code *pcVar1;
  int *piVar2;
  char cVar3;
  char cVar4;
  char cVar5;
  byte bVar6;
  undefined4 uVar7;
  int iVar8;
  int iVar9;
  ulonglong uVar10;
  longlong lVar11;
  longlong lVar12;
  longlong lVar13;
  undefined8 uVar14;
  ulonglong *puVar15;
  longlong *plVar16;
  int iVar17;
  bool bVar18;
  int local_res18 [2];
  int local_res20;
  int local_e8 [4];
  int local_d8;
  int local_d4;
  int local_d0;
  int local_cc;
  int *local_c8;
  undefined4 local_c0;
  longlong local_b8;
  longlong local_b0;
  int *local_a8;
  longlong local_a0;
  undefined8 local_98;
  undefined8 uStack_90;
  ulonglong local_88;
  undefined8 uStack_80;
  undefined4 local_68;
  undefined4 uStack_64;
  undefined4 uStack_60;
  undefined4 uStack_5c;
  ulonglong local_58;
  undefined8 uStack_50;
  
  local_res20 = param_4;
  if (DAT_181f6f2f3 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c4b8);
    DAT_181f6f2f3 = '\x01';
  }
  local_res18[0] = 0;
  local_d4 = 0;
  local_d0 = 0;
  local_cc = 0;
  local_98 = 0;
  uStack_90 = 0;
  local_88 = 0;
  uStack_80 = 0;
  local_d8 = 0;
  local_c8 = local_e8;
  local_c0 = 0xffffffff;
  local_a8 = local_c8;
  if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  uVar10 = *(ulonglong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x18);
  if (uVar10 == 0) {
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar14 = **(undefined8 **)(DAT_18225d198 + 0xb8);
    uVar10 = thunk_FUN_180203bc0(DAT_18227b6a0);
    FUN_1802a4990(uVar10,uVar14,DAT_18226fc58,DAT_1822342f0);
    puVar15 = (ulonglong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x18);
    *puVar15 = uVar10;
    thunk_FUN_180234e20(puVar15,uVar10);
  }
  lVar11 = FUN_1803fd610(param_3,uVar10,DAT_18223dba0);
  lVar12 = FUN_180237760(DAT_18223be18,2);
  lVar13 = thunk_FUN_180203bc0(DAT_18227f6f0);
  FUN_1812c6a20(lVar13,DAT_182255c98);
  local_b0 = lVar13;
  if (lVar11 == 0) {
LAB_18047761a:
    FUN_180237af0();
    pcVar1 = (code *)swi(3);
    (*pcVar1)();
    return;
  }
  lVar11 = FUN_1800dcbe0(0,DAT_18225d148,lVar11);
  local_b8 = lVar11;
  while (lVar11 != 0) {
    cVar3 = FUN_1800dcbe0(0,DAT_18223c7c8,lVar11);
    piVar2 = local_c8;
    if (cVar3 == '\0') {
      iVar17 = 0;
      local_c0 = 0;
      *local_c8 = 0x1e3;
      FUN_1800dcbe0(0,DAT_18223c790,lVar11);
      if (*piVar2 == 0x1e3) {
        iVar17 = -1;
      }
      if (lVar13 == 0) goto LAB_18047761a;
      FUN_1813b50f0(&local_68,lVar13,DAT_182241ba8);
      local_98 = CONCAT44(uStack_64,local_68);
      uStack_90 = CONCAT44(uStack_5c,uStack_60);
      local_88 = local_58;
      uStack_80 = uStack_50;
      goto LAB_1804773b0;
    }
    lVar11 = FUN_1800dcbe0(0,DAT_18225d128,lVar11);
    local_a0 = lVar11;
    if (lVar11 == 0) goto LAB_1804775e7;
    uVar7 = FUN_1804779f0(param_1,*(undefined8 *)(lVar11 + 0x20),0);
    if (lVar12 == 0) goto LAB_1804775e2;
    if (*(int *)(lVar12 + 0x18) == 0) {
      uVar14 = thunk_FUN_1801f53e0();
      FUN_180237ac0(uVar14,0);
LAB_1804775a6:
      uVar14 = thunk_FUN_1801f53e0();
      FUN_180237ac0(uVar14,0);
LAB_1804775b5:
      FUN_180237af0();
LAB_1804775ba:
      uVar14 = thunk_FUN_1801f53e0();
      FUN_180237ac0(uVar14,0);
LAB_1804775c9:
      uVar14 = thunk_FUN_1801f53e0();
      FUN_180237ac0(uVar14,0);
      goto LAB_1804775d8;
    }
    *(undefined4 *)(lVar12 + 0x20) = uVar7;
    uVar7 = FUN_1804779f0(param_1,*(undefined8 *)(lVar11 + 0x28),0);
    if (*(uint *)(lVar12 + 0x18) < 2) goto LAB_1804775a6;
    *(undefined4 *)(lVar12 + 0x24) = uVar7;
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar11 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x20);
    if (lVar11 == 0) {
      if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      uVar14 = **(undefined8 **)(DAT_18225d198 + 0xb8);
      lVar11 = thunk_FUN_180203bc0(DAT_18227ba58);
      FUN_1802a4990(lVar11,uVar14,DAT_18226fc48,DAT_18222f8d8);
      plVar16 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x20);
      *plVar16 = lVar11;
      thunk_FUN_180234e20(plVar16,lVar11);
    }
    cVar3 = FUN_180b93a20(lVar12,lVar11,DAT_18224c848);
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar11 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x28);
    if (lVar11 == 0) {
      if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      uVar14 = **(undefined8 **)(DAT_18225d198 + 0xb8);
      lVar11 = thunk_FUN_180203bc0(DAT_18227ba58);
      FUN_1802a4990(lVar11,uVar14,DAT_18226fc08,DAT_18222f8d8);
      plVar16 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x28);
      *plVar16 = lVar11;
      thunk_FUN_180234e20(plVar16,lVar11);
    }
    cVar4 = FUN_180b93a20(lVar12,lVar11,DAT_18224c848);
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar11 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x30);
    if (lVar11 == 0) {
      if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      uVar14 = **(undefined8 **)(DAT_18225d198 + 0xb8);
      lVar11 = thunk_FUN_180203bc0(DAT_18227ba58);
      FUN_1802a4990(lVar11,uVar14,DAT_18226fbe8,DAT_18222f8d8);
      plVar16 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x30);
      *plVar16 = lVar11;
      thunk_FUN_180234e20(plVar16,lVar11);
    }
    cVar5 = FUN_180a79040(lVar12,lVar11,DAT_18224ad80);
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar11 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x38);
    if (lVar11 == 0) {
      if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      uVar14 = **(undefined8 **)(DAT_18225d198 + 0xb8);
      lVar11 = thunk_FUN_180203bc0(DAT_18227ba58);
      FUN_1802a4990(lVar11,uVar14,DAT_18226fbb8,DAT_18222f8d8);
      plVar16 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x38);
      *plVar16 = lVar11;
      thunk_FUN_180234e20(plVar16,lVar11);
    }
    bVar6 = FUN_180a79040(lVar12,lVar11,DAT_18224ad80);
    uVar10 = (ulonglong)bVar6;
    if (cVar3 != '\0') {
      local_d4 = 0;
      if (lVar13 != 0) {
        FUN_1813c22b0(lVar13,7,&local_d4,DAT_182256af0);
        local_d4 = local_d4 + 1;
        FUN_1812c9b00(lVar13,7,local_d4,DAT_182255a70);
        goto LAB_180477183;
      }
      goto LAB_1804775b5;
    }
LAB_180477183:
    uVar14 = FUN_18075d910(*(undefined8 *)(local_a0 + 0x18),DAT_18223ac80);
    lVar11 = thunk_FUN_180200bb0(uVar14,DAT_1822764b8);
    local_res18[0] = 0;
    if (lVar11 == 0) goto LAB_1804775dd;
    cVar3 = FUN_1800dcbe0(1,DAT_1822764b8,lVar11);
    if (cVar3 != '\0') {
      if (*(int *)(lVar12 + 0x18) != 0) {
        local_res18[0] = *(int *)(lVar12 + 0x20);
        goto LAB_18047720f;
      }
      goto LAB_1804775c9;
    }
    cVar3 = FUN_1800dcbe0(2,DAT_1822764b8,lVar11);
    if (cVar3 != '\0') {
      if (1 < *(uint *)(lVar12 + 0x18)) {
        local_res18[0] = *(int *)(lVar12 + 0x24);
        goto LAB_18047720f;
      }
      goto LAB_1804775ba;
    }
LAB_18047720f:
    lVar11 = local_b8;
    if (cVar5 != '\0' || cVar4 != '\0') goto LAB_180477261;
    if (cVar4 == '\0') {
      if ((cVar5 == '\0') && (bVar6 == 0)) goto LAB_180477261;
      bVar18 = cVar5 == '\0';
    }
    else {
      bVar18 = false;
    }
    if (((bVar18 & bVar6) != 0) && (cVar3 = FUN_18033cf90(local_res18,7), cVar3 == '\0')) {
LAB_180477261:
      local_d0 = 0;
      if (lVar13 == 0) {
LAB_1804775d8:
        FUN_180237af0();
LAB_1804775dd:
        FUN_180237af0();
LAB_1804775e2:
        FUN_180237af0();
LAB_1804775e7:
        FUN_180237af0();
        break;
      }
      FUN_1813c22b0(lVar13,local_res18[0],&local_d0,DAT_182256af0);
      local_d0 = local_d0 + 1;
      FUN_1812c9b00(lVar13,local_res18[0],local_d0,DAT_182255a70);
      lVar11 = local_b8;
      cVar3 = '\0';
      if (local_res18[0] != 6) {
        cVar3 = cVar5;
      }
      if (cVar3 != '\0') {
        local_cc = 0;
        FUN_1813c22b0(lVar13,6,&local_cc,DAT_182256af0);
        local_cc = local_cc + 1;
        FUN_1812c9b00();
      }
    }
  }
  FUN_180237af0();
  FUN_180237ac0(uVar10,0);
LAB_1804775fd:
  FUN_180237af0();
LAB_180477602:
  FUN_180237af0();
LAB_180477607:
  FUN_180237af0();
LAB_18047760c:
  uVar7 = FUN_180237af0();
  FUN_180237ac0(uVar7,0);
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
LAB_1804773b0:
  do {
    do {
      cVar3 = FUN_180bbb0a0(&local_98,DAT_18225ba78);
      uVar10 = local_88;
      if (cVar3 == '\0') {
        local_c8[(longlong)iVar17 + 1] = 0x2a0;
        FUN_1802698f0(&local_98,DAT_182262070);
        return;
      }
      local_d8 = 0;
      if (param_2 == 0) goto LAB_18047760c;
      if (*(longlong *)(param_2 + 0x58) == 0) goto LAB_180477607;
      FUN_1813c22b0(*(longlong *)(param_2 + 0x58),local_88 & 0xffffffff,&local_d8,DAT_182258028);
      iVar9 = local_d8;
      if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      iVar8 = FUN_180383110(1,iVar9,1,0);
      iVar9 = local_d8;
    } while (iVar8 < 1);
    if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    iVar9 = FUN_180382120(1,iVar9,1,0);
    iVar9 = ((int)(uVar10 >> 0x20) - iVar9) + local_res20;
    if (((*(byte *)(DAT_18222f490 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f490 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    iVar9 = FUN_180f99dd0(iVar9 + 10,0,0);
  } while (iVar9 < 0xb);
  if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar11 = FUN_1808ac390(0);
  if (lVar11 == 0) goto LAB_180477602;
  iVar9 = FUN_1808ac0d0(lVar11,iVar9,0);
  iVar9 = local_d8 + iVar9;
  local_d8 = iVar9;
  if (((*(byte *)(DAT_18222f490 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f490 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  local_d8 = FUN_180f99de0(iVar9,iVar8,0);
  if (*(longlong *)(param_2 + 0x58) == 0) goto LAB_1804775fd;
  FUN_1812c9b00(*(longlong *)(param_2 + 0x58),uVar10 & 0xffffffff,local_d8,DAT_182259798);
  goto LAB_1804773b0;
}



/********************************************************************/
/* StatusUpProvider$$GetSkillUpWeaponTarget
 * RVA: 0x4779F0
 * Address: 0x1804779F0
 *******************************************************************/


ulonglong FUN_1804779f0(undefined8 param_1,longlong param_2)

{
  longlong lVar1;
  code *pcVar2;
  int iVar3;
  undefined4 uVar4;
  ulonglong uVar5;
  longlong lVar6;
  uint local_res10 [6];
  
  if (DAT_181f6f2f4 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c4e4);
    DAT_181f6f2f4 = '\x01';
  }
  local_res10[0] = 7;
  if (param_2 == 0) {
    return 7;
  }
  lVar6 = *(longlong *)(param_2 + 0x50);
  if (lVar6 == 0) {
    if (*(longlong *)(param_2 + 0x58) != 0) {
      iVar3 = FUN_180a185d0(*(longlong *)(param_2 + 0x58),0);
      if (iVar3 != 0) {
        return 6;
      }
LAB_180477aa7:
      return (ulonglong)local_res10[0];
    }
  }
  else {
    if (((*(byte *)(DAT_18225d108 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d108 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18225d108);
      lVar6 = *(longlong *)(param_2 + 0x50);
    }
    lVar1 = **(longlong **)(DAT_18225d108 + 0xb8);
    if ((lVar6 != 0) && (uVar4 = FUN_180a18040(lVar6,0), lVar1 != 0)) {
      FUN_1813c22b0(lVar1,uVar4,local_res10,DAT_182257918);
      goto LAB_180477aa7;
    }
  }
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  uVar5 = (*pcVar2)();
  return uVar5;
}

