/*
 * FF2 Decompiled Functions - Magic/Ability System
 * Generated by Ghidra headless analysis
 * Program: GameAssembly.dll
 * Image Base: 0x180000000
 * IL2CPP types applied: True
 *
 * Purpose: Understanding FF2's unique spell growth system for screen reader accessibility
 *
 * FF2 Magic System:
 *   - Spells level up through usage (similar to weapon skills)
 *   - Each spell has 16 levels, increasing power and MP cost
 *   - Spell proficiency tracked per-character
 *
 * Key classes:
 *   - OwnedAbility: Player's spell instance with skill level
 *   - Ability: Master data for spell properties
 *   - StatusUpProvider: Handles all skill growth after battle
 *   - JobInfomationData: Spell level progression tables
 *   - BattleResultCharacterData: Battle result tracking
 */


/====================================================================/
/* Ability
 ===================================================================/

/********************************************************************/
/* Ability$$ctor_masterLine
 * RVA: 0xEE8F60
 * Address: 0x180EE8F60
 *******************************************************************/


void FUN_180ee8f60(undefined8 param_1,undefined8 param_2)

{
  if (DAT_181f77438 == '\0') {
    thunk_FUN_1801fef70(DAT_1817e7588);
    DAT_181f77438 = '\x01';
  }
  FUN_180268140(param_1,0);
  if (((*(byte *)(DAT_182274810 + 0x12f) & 2) != 0) && (*(int *)(DAT_182274810 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_182274810);
  }
  FUN_1804c6560(param_1,*(longlong *)(DAT_182274810 + 0xb8) + 8,DAT_18225ddd0);
  FUN_18107df80(param_1,*(longlong *)(DAT_182274810 + 0xb8) + 8,param_2,0);
  return;
}



/********************************************************************/
/* Ability$$get_AbilityGroupId
 * RVA: 0xA18040
 * Address: 0x180A18040
 *******************************************************************/


ulonglong FUN_180a18040(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237af0();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (3 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x2c);
  }
  uVar3 = thunk_FUN_1801f53e0();
  FUN_180237ac0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_AbilityLv
 * RVA: 0xA17FC0
 * Address: 0x180A17FC0
 *******************************************************************/


ulonglong FUN_180a17fc0(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237af0();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (2 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x28);
  }
  uVar3 = thunk_FUN_1801f53e0();
  FUN_180237ac0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_Id
 * RVA: 0xA17D10
 * Address: 0x180A17D10
 *******************************************************************/


ulonglong FUN_180a17d10(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237af0();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (*(int *)(lVar1 + 0x18) != 0) {
    return (ulonglong)*(uint *)(lVar1 + 0x20);
  }
  uVar3 = thunk_FUN_1801f53e0();
  FUN_180237ac0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_StandardValue
 * RVA: 0xA267B0
 * Address: 0x180A267B0
 *******************************************************************/


ulonglong FUN_180a267b0(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237af0();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (9 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x44);
  }
  uVar3 = thunk_FUN_1801f53e0();
  FUN_180237ac0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_TypeId
 * RVA: 0xA18000
 * Address: 0x180A18000
 *******************************************************************/


ulonglong FUN_180a18000(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237af0();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (4 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x30);
  }
  uVar3 = thunk_FUN_1801f53e0();
  FUN_180237ac0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/********************************************************************/
/* Ability$$get_UseValue
 * RVA: 0xA18610
 * Address: 0x180A18610
 *******************************************************************/


ulonglong FUN_180a18610(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    FUN_180237af0();
    pcVar2 = (code *)swi(3);
    uVar4 = (*pcVar2)();
    return uVar4;
  }
  if (8 < *(uint *)(lVar1 + 0x18)) {
    return (ulonglong)*(uint *)(lVar1 + 0x40);
  }
  uVar3 = thunk_FUN_1801f53e0();
  FUN_180237ac0(uVar3,0);
  pcVar2 = (code *)swi(3);
  uVar4 = (*pcVar2)();
  return uVar4;
}



/====================================================================/
/* BattleResultCharacterData
 ===================================================================/

/********************************************************************/
/* BattleResultCharacterData$$AbilityLevelUp
 * RVA: 0x4A5D40
 * Address: 0x1804A5D40
 *******************************************************************/


ulonglong FUN_1804a5d40(longlong param_1)

{
  longlong lVar1;
  code *pcVar2;
  char cVar3;
  undefined4 uVar4;
  int iVar5;
  longlong lVar6;
  longlong lVar7;
  ulonglong uVar8;
  int iVar9;
  int iVar10;
  int iVar11;
  byte local_res8;
  int local_c8 [4];
  int *local_b8;
  longlong local_b0;
  longlong local_a8;
  undefined4 local_a0;
  undefined4 uStack_9c;
  undefined4 uStack_98;
  undefined4 uStack_94;
  longlong local_90;
  undefined8 local_88;
  undefined8 uStack_80;
  longlong local_78;
  undefined4 local_70;
  undefined4 uStack_6c;
  undefined4 uStack_68;
  undefined4 uStack_64;
  longlong local_60;
  
  if (DAT_181f6f52c == '\0') {
    thunk_FUN_1801fef70(DAT_1817e5418);
    DAT_181f6f52c = '\x01';
  }
  local_88 = 0;
  uStack_80 = 0;
  local_78 = 0;
  local_res8 = 0;
  local_b8 = local_c8;
  if (*(longlong *)(param_1 + 0x10) != 0) {
    lVar7 = *(longlong *)(*(longlong *)(param_1 + 0x10) + 0x18);
    if (*(longlong *)(param_1 + 0x18) != 0) {
      lVar1 = *(longlong *)(*(longlong *)(param_1 + 0x18) + 0x18);
      local_b0 = lVar1;
      lVar6 = thunk_FUN_180203bc0(DAT_182239560);
      FUN_180f858b0(lVar6,DAT_18223d008);
      local_a8 = lVar6;
      if (lVar7 != 0) {
        FUN_1813a5750(&local_70,lVar7,DAT_182235e20);
        local_a0 = local_70;
        uStack_9c = uStack_6c;
        uStack_98 = uStack_68;
        uStack_94 = uStack_64;
        local_90 = local_60;
        while (cVar3 = FUN_180a42760(&local_a0,DAT_182252828), cVar3 != '\0') {
          if (local_90 == 0) goto LAB_1804a6176;
          uVar4 = FUN_18067aea0(local_90,0);
          if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar4 = FUN_180382120(1,uVar4,1,0);
          if (lVar6 == 0) goto LAB_1804a6170;
          FUN_181483420(lVar6,uVar4,DAT_18223cf90);
        }
        iVar11 = 0;
        iVar9 = 0;
        local_c8[0] = 0x5e;
        FUN_1802698f0(&local_a0,DAT_18224c570);
        if (local_c8[0] == 0x5e) {
          iVar9 = -1;
        }
        lVar7 = thunk_FUN_180203bc0(DAT_182239560);
        FUN_180f858b0(lVar7,DAT_18223d008);
        local_b0 = lVar7;
        if (lVar1 != 0) {
          FUN_1813a5750(&local_70,lVar1,DAT_182235e20);
          local_a0 = local_70;
          uStack_9c = uStack_6c;
          uStack_98 = uStack_68;
          uStack_94 = uStack_64;
          local_90 = local_60;
          while (cVar3 = FUN_180a42760(&local_a0,DAT_182252828), cVar3 != '\0') {
            if (local_90 == 0) goto LAB_1804a6189;
            uVar4 = FUN_18067aea0(local_90,0);
            if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_182279950 + 0xe0) == 0)) {
              il2cpp_runtime_class_init();
            }
            uVar4 = FUN_180382120(1,uVar4,1,0);
            if (lVar7 == 0) goto LAB_1804a6184;
            FUN_181483420(lVar7,uVar4,DAT_18223cf90);
          }
          iVar10 = iVar9 + 1;
          local_c8[(longlong)iVar9 + 1] = 0xa4;
          FUN_1802698f0(&local_a0,DAT_18224c570);
          if (((iVar10 != -1) && (local_c8[iVar10] == 0xa4)) && (-1 < iVar10)) {
            iVar10 = iVar9;
          }
          if (lVar6 != 0) {
            FUN_1813f4310(&local_70,lVar6,DAT_182232b30);
            local_78 = local_60;
            do {
              cVar3 = FUN_180a424e0(&local_88,DAT_18224fcb0);
              if (cVar3 == '\0') {
                local_c8[(longlong)iVar10 + 1] = 0xea;
                uVar8 = FUN_1802698f0(&local_88,DAT_1822492a0);
LAB_1804a6133:
                if ((iVar10 + 1 == -1) || (uVar8 = (ulonglong)(iVar10 + 1), local_c8[uVar8] != 0xec)
                   ) {
                  uVar8 = uVar8 & 0xffffffffffffff00;
                }
                else {
                  uVar8 = (ulonglong)local_res8;
                }
                return uVar8;
              }
              iVar9 = (int)local_78;
              iVar5 = FUN_180759a80(lVar7,iVar11,DAT_18223c1b0);
              if (iVar9 < iVar5) {
                local_res8 = 1;
                local_c8[(longlong)iVar10 + 1] = 0xec;
                uVar8 = FUN_1802698f0(&local_88,DAT_1822492a0);
                goto LAB_1804a6133;
              }
              iVar11 = iVar11 + 1;
            } while( true );
          }
        }
      }
    }
  }
  FUN_180237af0();
LAB_1804a6170:
  FUN_180237af0();
LAB_1804a6176:
  uVar4 = FUN_180237af0();
  FUN_180237ac0(uVar4,0);
LAB_1804a6184:
  FUN_180237af0();
LAB_1804a6189:
  uVar4 = FUN_180237af0();
  FUN_180237ac0(uVar4,0);
  pcVar2 = (code *)swi(3);
  uVar8 = (*pcVar2)();
  return uVar8;
}



/********************************************************************/
/* BattleResultCharacterData$$get_IsAbilityLevelUp
 * RVA: 0x4A6C90
 * Address: 0x1804A6C90
 *******************************************************************/


undefined BattleResultCharacterData_get_IsAbilityLevelUp(longlong param_1)

{
  return *(undefined *)(param_1 + 0x23);
}



/********************************************************************/
/* BattleResultCharacterData$$set_IsAbilityLevelUp
 * RVA: 0x4A6CB0
 * Address: 0x1804A6CB0
 *******************************************************************/


void BattleResultCharacterData_set_IsAbilityLevelUp(longlong param_1,undefined param_2)

{
  *(undefined *)(param_1 + 0x23) = param_2;
  return;
}



/====================================================================/
/* BattleResultProvider
 ===================================================================/

/********************************************************************/
/* BattleResultProvider$$Genelate
 * RVA: 0x379320
 * Address: 0x180379320
 *******************************************************************/


longlong BattleResultProvider_Genelate
                   (undefined8 param_1,longlong param_2,int param_3,int param_4,ulonglong param_5,
                   undefined8 param_6)

{
  code *pcVar1;
  int *piVar2;
  char cVar3;
  undefined4 uVar4;
  int iVar5;
  uint uVar6;
  int iVar7;
  undefined8 uVar8;
  longlong lVar9;
  ulonglong uVar10;
  longlong lVar11;
  longlong lVar12;
  ulonglong uVar13;
  undefined8 uVar14;
  longlong lVar15;
  undefined2 uVar16;
  longlong *plVar17;
  longlong lVar18;
  int iStackX_20;
  int aiStack_f8 [4];
  int iStack_e8;
  int *piStack_e0;
  longlong lStack_d8;
  uint uStack_d0;
  longlong lStack_c8;
  longlong lStack_c0;
  longlong lStack_b8;
  ulonglong uStack_b0;
  int *piStack_a8;
  ulonglong uStack_a0;
  undefined8 uStack_98;
  longlong lStack_90;
  longlong lStack_88;
  undefined8 uStack_80;
  undefined8 uStack_78;
  undefined8 uStack_70;
  undefined4 uStack_50;
  undefined4 uStack_4c;
  undefined4 uStack_48;
  undefined4 uStack_44;
  undefined8 uStack_40;
  
  if (DAT_181f6e86a == '\0') {
    thunk_FUN_1801fef70(DAT_1817e54e0);
    DAT_181f6e86a = '\x01';
  }
  uVar13 = 0;
  uStack_98 = 0;
  uStack_80 = 0;
  uStack_78 = 0;
  uStack_70 = 0;
  uStack_b0 = 0;
  piStack_e0 = aiStack_f8;
  iStack_e8 = -1;
  piStack_a8 = piStack_e0;
  if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  uVar8 = FUN_1810e8a40(DAT_182263388);
  lVar15 = param_5;
  lVar9 = FUN_1804d7ab0(param_5,uVar8,0);
  uVar10 = thunk_FUN_180203bc0(DAT_18227ae60);
  param_5 = uVar10;
  FUN_180f858b0(uVar10,DAT_182246e18);
  if (lVar9 == 0) {
LAB_180379ca3:
    FUN_180237af0();
LAB_180379ca9:
    FUN_180237af0();
  }
  else {
    lVar18 = 0x20;
    iStackX_20 = param_4;
    while( true ) {
      uVar6 = (uint)uVar13;
      if ((int)*(uint *)(lVar9 + 0x18) <= (int)uVar6) break;
      if (*(uint *)(lVar9 + 0x18) <= uVar6) {
        FUN_180d2bc30(0);
      }
      lVar12 = *(longlong *)(lVar18 + *(longlong *)(lVar9 + 0x10));
      if (lVar15 == 0) goto LAB_180379ca3;
      if (*(uint *)(lVar15 + 0x18) <= uVar6) {
        FUN_180d2bc30(0);
      }
      lVar11 = *(longlong *)(lVar18 + *(longlong *)(lVar15 + 0x10));
      if ((lVar11 == 0) || (iVar5 = *(int *)(lVar11 + 0x14), lVar12 == 0)) goto LAB_180379ca3;
      if (*(int *)(lVar12 + 0x18) == 5) {
        if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar11 = FUN_1808ac390(0);
        if (lVar11 == 0) goto LAB_180379ca3;
        uVar4 = FUN_1808ac020(lVar11,*(undefined4 *)(lVar12 + 0x38),0);
        *(undefined4 *)(lVar12 + 0x38) = uVar4;
        lVar11 = FUN_1808ac390(0);
        if (lVar11 == 0) goto LAB_180379ca3;
        iVar5 = FUN_1808ac020(lVar11,iVar5,0);
        iStackX_20 = param_4 + *(int *)(lVar12 + 0x38);
        param_4 = iStackX_20;
      }
      if (iVar5 == 0) {
        uVar13 = (ulonglong)(uVar6 + 1);
        lVar18 = lVar18 + 8;
        uVar10 = param_5;
      }
      else {
        lVar12 = FUN_1800dd030(lVar15,uVar13,DAT_18222d498);
        if (lVar12 == 0) goto LAB_180379ca3;
        uVar4 = *(undefined4 *)(lVar12 + 0x10);
        uVar8 = thunk_FUN_180203bc0(DAT_18227af10);
        FUN_1804ab310(uVar8,uVar4,iVar5);
        uVar10 = param_5;
        if (param_5 == 0) goto LAB_180379ca3;
        FUN_1814cc490(param_5,uVar8);
        uVar13 = (ulonglong)(uVar6 + 1);
        lVar18 = lVar18 + 8;
        param_4 = iStackX_20;
      }
    }
    if (((*(byte *)(DAT_18223a4e8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18223a4e8 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uStack_98 = FUN_180d59ee0(0);
    uVar6 = FUN_180d59e30(&uStack_98,0);
    uVar13 = (ulonglong)uVar6;
    uStack_d0 = uVar6;
    lVar15 = thunk_FUN_180203bc0(DAT_18225e948);
    lStack_d8 = lVar15;
    FUN_1804a6cd0(lVar15,0);
    lStack_c0 = lVar15;
    if (lVar15 == 0) goto LAB_180379ca3;
    *(ulonglong *)(lVar15 + 0x28) = uVar10;
    thunk_FUN_180234e20((ulonglong *)(lVar15 + 0x28),uVar10);
    *(int *)(lVar15 + 0x18) = param_3;
    *(int *)(lVar15 + 0x14) = param_4;
    *(uint *)(lVar15 + 0x38) = uVar6;
    lVar15 = thunk_FUN_180203bc0(DAT_18227f4c8);
    lStack_c8 = lVar15;
    FUN_180f858b0(lVar15,DAT_182245b78);
    lStack_b8 = lVar15;
    if (param_2 == 0) goto LAB_180379ca3;
    uVar13 = FUN_1800dcbe0(0,DAT_182269c18,param_2);
    uStack_a0 = uVar13;
    while (iVar5 = 0, uVar13 != 0) {
      cVar3 = FUN_1800dcbe0(0,DAT_18223c7c8,uVar13);
      piVar2 = piStack_e0;
      if (cVar3 == '\0') {
        iStack_e8 = 0;
        *piStack_e0 = 0x183;
        lVar9 = lStack_d8;
        FUN_1800dcbe0(0,DAT_18223c790,uVar13);
        uVar13 = uStack_b0;
        if (uStack_b0 != 0) goto LAB_180379cb5;
        if (*piVar2 == 0x183) {
          iVar5 = -1;
          iStack_e8 = -1;
        }
        lStack_b8 = CONCAT44(lStack_b8._4_4_,iVar5);
        if (lVar15 == 0) goto LAB_180379ca3;
        iVar7 = *(int *)(lVar15 + 0x18);
        *(int *)(lVar9 + 0x24) = iVar7;
        if (iVar7 == 0) {
          iVar7 = 1;
        }
        param_5 = CONCAT44(param_5._4_4_,param_3 / iVar7);
        lVar9 = thunk_FUN_180203bc0(DAT_18227f5c0,(longlong)param_3 % (longlong)iVar7 & 0xffffffff);
        FUN_180268140(lVar9,0);
        lStack_90 = lVar9;
        if (((*(byte *)(DAT_182278de8 + 0x12f) & 2) != 0) && (*(int *)(DAT_182278de8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar18 = FUN_180790970(0);
        if (lVar18 == 0) goto LAB_180379ca3;
        lVar18 = *(longlong *)(lVar18 + 0x10);
        lStack_88 = lVar18;
        uVar10 = FUN_1800dcbe0(0,DAT_182269c18,param_2);
        lVar12 = lStack_d8;
        uStack_a0 = uVar10;
        goto LAB_1803798f0;
      }
      lVar9 = FUN_1800dcbe0(0,DAT_182269bd0,uVar13);
      uVar16 = 0;
      if ((lVar9 != 0) && (*(longlong *)(lVar9 + 0x78) != 0)) {
        uVar8 = *(undefined8 *)(*(longlong *)(lVar9 + 0x78) + 0x88);
        if (((*(byte *)(DAT_18225e928 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225e928 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar15 = *(longlong *)(*(longlong *)(DAT_18225e928 + 0xb8) + 8);
        if (lVar15 == 0) {
          if (((*(byte *)(DAT_18225e928 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225e928 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar14 = **(undefined8 **)(DAT_18225e928 + 0xb8);
          lVar15 = thunk_FUN_180203bc0(DAT_18227c3f8);
          FUN_1802a4990(lVar15,uVar14,DAT_182270c58);
          plVar17 = (longlong *)(*(longlong *)(DAT_18225e928 + 0xb8) + 8);
          *plVar17 = lVar15;
          thunk_FUN_180234e20(plVar17,lVar15);
        }
        cVar3 = FUN_180a7a480(uVar8,lVar15,DAT_18224c0c0);
        param_5 = param_5 & 0xffffffffffff0000;
        FUN_18108dff0(&param_5,cVar3 == '\0',DAT_182229650);
        lVar15 = lStack_c8;
        uVar16 = (undefined2)param_5;
      }
      cVar3 = (char)uVar16;
      if ((char)((ushort)uVar16 >> 8) == '\0') {
        cVar3 = '\0';
      }
      if (cVar3 != '\0') {
        if (lVar15 == 0) goto LAB_180379ca9;
        FUN_1814cc490(lVar15,lVar9,DAT_182245b30);
      }
    }
  }
  FUN_180237af0();
LAB_180379cb5:
  FUN_180237ac0(uVar13,0);
LAB_180379cc0:
  FUN_180237af0();
LAB_180379cc5:
  FUN_180237af0();
LAB_180379cca:
  FUN_180237af0();
LAB_180379ccf:
  FUN_180237af0();
LAB_180379cd4:
  FUN_180237af0();
LAB_180379cd9:
  FUN_180237af0();
LAB_180379cdf:
  FUN_180237ac0(uVar13,0);
LAB_180379cea:
  FUN_180237af0();
LAB_180379cef:
  FUN_180237af0();
LAB_180379cf4:
  uVar4 = FUN_180237af0();
  FUN_180237ac0(uVar4,0);
  pcVar1 = (code *)swi(3);
  lVar15 = (*pcVar1)();
  return lVar15;
LAB_1803798f0:
  if (uVar10 != 0) {
    cVar3 = FUN_1800dcbe0(0,DAT_18223c7c8,uVar10);
    uVar13 = uStack_b0;
    piVar2 = piStack_e0;
    if (cVar3 == '\0') {
      iVar7 = iVar5 + 1;
      piStack_e0[(longlong)(int)lStack_b8 + 1] = 0x260;
      iStack_e8 = iVar7;
      FUN_1800dcbe0(0,DAT_18223c790,uVar10);
      if (uVar13 != 0) goto LAB_180379cdf;
      if (((iVar7 != -1) && (piVar2[iVar7] == 0x260)) && (-1 < iVar7)) {
        iVar7 = iVar5;
      }
      uVar8 = thunk_FUN_180203bc0(DAT_18227f4c8);
      FUN_180f858b0(uVar8,DAT_182245b78);
      if (((*(byte *)(DAT_18227e2b0 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e2b0 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar15 = FUN_1805e5510(0);
      if ((lVar15 == 0) || (lVar15 = FUN_1805e4920(lVar15,0,0), lVar15 == 0)) goto LAB_180379ca3;
      FUN_1813a5750(&uStack_50,lVar15,DAT_182235db0);
      uStack_80 = CONCAT44(uStack_4c,uStack_50);
      uStack_78 = CONCAT44(uStack_44,uStack_48);
      uStack_70 = uStack_40;
      goto LAB_180379b80;
    }
    uVar13 = FUN_1800dcbe0(0,DAT_182269bd0,uVar10);
    cVar3 = FUN_1814cc980(lVar15,uVar13,DAT_18224ec78);
    if (cVar3 == '\0') {
      uVar8 = thunk_FUN_180203bc0(DAT_1822798c0);
      FUN_18067dd80(uVar8,uVar13,0);
      uVar14 = thunk_FUN_180203bc0(DAT_18225e908);
      FUN_1804a6a90(uVar14,uVar13,uVar8,0);
      lVar12 = lStack_d8;
      if (*(longlong *)(lStack_d8 + 0x30) == 0) goto LAB_180379cc0;
      FUN_1814cc490(*(longlong *)(lStack_d8 + 0x30),uVar14,DAT_182246f30);
      lVar15 = lStack_c8;
    }
    else {
      lVar15 = thunk_FUN_180203bc0(DAT_1822798c0);
      FUN_18067dd80(lVar15,uVar13,0);
      if (lVar15 == 0) goto LAB_180379cd4;
      iVar7 = FUN_18067f490(lVar15,0);
      FUN_18067fab0(lVar15,(int)param_5 + iVar7,0);
      if (lVar18 == 0) goto LAB_180379ccf;
      uVar8 = FUN_1800fc4a0(1,DAT_182278da0,lVar18,lVar15,uStack_d0,param_6);
      uVar14 = thunk_FUN_180203bc0(DAT_18225e908);
      FUN_1804a6a90(uVar14,uVar13,uVar8,0);
      if (*(longlong *)(lStack_d8 + 0x30) == 0) goto LAB_180379cca;
      FUN_1814cc490(*(longlong *)(lStack_d8 + 0x30),uVar14,DAT_182246f30);
      if (lVar9 == 0) goto LAB_180379cc5;
      FUN_18061e350(lVar9,uVar8,0);
      lVar15 = lStack_c8;
      lVar12 = lStack_d8;
    }
    goto LAB_1803798f0;
  }
  goto LAB_180379cd9;
LAB_180379b80:
  do {
    cVar3 = FUN_180a42760(&uStack_80,DAT_1822527e8);
    uVar8 = uStack_70;
    if (cVar3 == '\0') {
      piStack_e0[(longlong)iVar7 + 1] = 0x2d5;
      FUN_1802698f0(&uStack_80,DAT_18224c520);
      *(undefined *)(lVar12 + 0x10) = 1;
      return lVar12;
    }
    cVar3 = FUN_180a7b440(param_2,uStack_70,DAT_18224a9a0);
  } while (cVar3 != '\0');
  lVar15 = thunk_FUN_180203bc0(DAT_1822798c0);
  FUN_18067dd80(lVar15,uVar8,0);
  if (lVar15 == 0) goto LAB_180379cf4;
  iVar5 = FUN_18067f490(lVar15,0);
  FUN_18067fab0(lVar15,(int)param_5 + iVar5,0);
  if (lVar18 == 0) goto LAB_180379cef;
  uVar8 = FUN_1800fc4a0(1,DAT_182278da0,lVar18,lVar15,uStack_d0,0);
  if (lVar9 == 0) goto LAB_180379cea;
  FUN_18061e350(lVar9,uVar8,0);
  goto LAB_180379b80;
}



/====================================================================/
/* BattleSkillUpInformation
 ===================================================================/

/********************************************************************/
/* BattleSkillUpInformation$$get_MonsterAverageRank
 * RVA: 0x29C1A0
 * Address: 0x18029C1A0
 *******************************************************************/


undefined4 BattleSkillUpInformation_get_MonsterAverageRank(longlong param_1)

{
  return *(undefined4 *)(param_1 + 0x18);
}



/====================================================================/
/* JobInfomationData
 ===================================================================/

/********************************************************************/
/* JobInfomationData$$CreateGroup
 * RVA: 0x414260
 * Address: 0x180414260
 *******************************************************************/


longlong FUN_180414260(undefined8 param_1,ulonglong param_2)

{
  code *pcVar1;
  char cVar2;
  longlong lVar3;
  longlong lVar4;
  longlong lVar5;
  undefined8 uVar6;
  ulonglong uVar7;
  uint uVar8;
  ulonglong uVar10;
  ulonglong local_res20;
  ulonglong uVar9;
  
  param_2 = param_2 & 0xffffffff;
  if (DAT_181f6eefc == '\0') {
    thunk_FUN_1801fef70(DAT_1817e9c10);
    DAT_181f6eefc = '\x01';
  }
  lVar3 = thunk_FUN_180203bc0(DAT_182239560);
  FUN_180f858b0(lVar3,DAT_18223d008);
  if (lVar3 != 0) {
    FUN_181483420(lVar3,param_2,DAT_18223cf90);
    uVar10 = 0;
    uVar9 = uVar10;
    while( true ) {
      if (DAT_181f6eefb == '\0') {
        thunk_FUN_1801fef70(DAT_1817e9cc4);
        DAT_181f6eefb = '\x01';
      }
      lVar4 = thunk_FUN_180203bc0(DAT_182247d18);
      FUN_1802698f0(lVar4,0);
      if (lVar4 == 0) break;
      *(int *)(lVar4 + 0x10) = (int)param_2;
      if (((*(byte *)(DAT_18227cdc8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227cdc8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar5 = FUN_18086da70(0);
      if (lVar5 == 0) break;
      lVar5 = *(longlong *)(lVar5 + 0x78);
      uVar7 = uVar10;
      if (lVar5 != 0) {
        uVar6 = thunk_FUN_180203bc0(DAT_18227cda0);
        FUN_1802a4990(uVar6,lVar4,DAT_182265610,DAT_182231570);
        lVar5 = FUN_1803fd610(lVar5,uVar6,DAT_18223ca38);
        if ((lVar5 != 0) && (lVar5 = FUN_18075d910(lVar5,DAT_182239f90), lVar5 != 0)) {
          local_res20 = 0;
          FUN_180f44000(&local_res20,*(undefined4 *)(lVar5 + 0x14),DAT_1822295d0);
          uVar7 = local_res20;
        }
      }
      param_2 = uVar7 & 0xffffffff;
      if ((char)(uVar7 >> 0x20) == '\0') {
        param_2 = uVar10;
      }
      if (((int)param_2 == 0) &&
         (param_2 = (ulonglong)*(uint *)(lVar4 + 0x10), *(uint *)(lVar4 + 0x10) == 0)) {
        return lVar3;
      }
      cVar2 = FUN_181483690(lVar3,param_2,DAT_18224e380);
      if (cVar2 == '\0') {
        FUN_181483420(lVar3,param_2,DAT_18223cf90);
      }
      uVar8 = (int)uVar9 + 1;
      uVar9 = (ulonglong)uVar8;
      if (0xf < (int)uVar8) {
        return lVar3;
      }
    }
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  lVar3 = (*pcVar1)();
  return lVar3;
}



/********************************************************************/
/* JobInfomationData$$GetNextLevelAbilityId
 * RVA: 0x414440
 * Address: 0x180414440
 *******************************************************************/


ulonglong FUN_180414440(undefined8 param_1,undefined4 param_2)

{
  code *pcVar1;
  longlong lVar2;
  longlong lVar3;
  undefined8 uVar4;
  ulonglong uVar5;
  ulonglong local_res20;
  
  if (DAT_181f6eefb == '\0') {
    thunk_FUN_1801fef70(DAT_1817e9cc4);
    DAT_181f6eefb = '\x01';
  }
  lVar2 = thunk_FUN_180203bc0(DAT_182247d18);
  FUN_1802698f0(lVar2,0);
  if (lVar2 == 0) {
LAB_180414565:
    FUN_180237af0();
    pcVar1 = (code *)swi(3);
    uVar5 = (*pcVar1)();
    return uVar5;
  }
  *(undefined4 *)(lVar2 + 0x10) = param_2;
  if (((*(byte *)(DAT_18227cdc8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227cdc8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar3 = FUN_18086da70(0);
  if (lVar3 == 0) goto LAB_180414565;
  lVar3 = *(longlong *)(lVar3 + 0x78);
  if (lVar3 != 0) {
    uVar4 = thunk_FUN_180203bc0(DAT_18227cda0);
    FUN_1802a4990(uVar4,lVar2,DAT_182265610,DAT_182231570);
    lVar3 = FUN_1803fd610(lVar3,uVar4,DAT_18223ca38);
    if ((lVar3 != 0) && (lVar3 = FUN_18075d910(lVar3,DAT_182239f90), lVar3 != 0)) {
      local_res20 = 0;
      FUN_180f44000(&local_res20,*(undefined4 *)(lVar3 + 0x14),DAT_1822295d0);
      goto LAB_180414542;
    }
  }
  local_res20 = 0;
LAB_180414542:
  uVar5 = local_res20 & 0xffffffff;
  if ((char)(local_res20 >> 0x20) == '\0') {
    uVar5 = 0;
  }
  if ((int)uVar5 == 0) {
    uVar5 = (ulonglong)*(uint *)(lVar2 + 0x10);
  }
  return uVar5;
}



/********************************************************************/
/* JobInfomationData$$SetSkillLevel
 * RVA: 0x414810
 * Address: 0x180414810
 *******************************************************************/


void JobInfomationData_SetSkillLevel(longlong param_1,longlong *param_2)

{
  code *pcVar1;
  ulonglong uVar2;
  char cVar3;
  undefined4 uVar4;
  longlong lVar5;
  undefined4 uStackX_c;
  undefined4 uStack_60;
  undefined4 uStack_5c;
  undefined4 uStack_58;
  undefined4 uStack_54;
  ulonglong uStack_50;
  undefined8 uStack_48;
  undefined4 uStack_40;
  undefined4 uStack_3c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  ulonglong uStack_30;
  undefined8 uStack_28;
  
  if (DAT_181f6eefa == '\0') {
    thunk_FUN_1801fef70(DAT_1817e9cf8);
    DAT_181f6eefa = '\x01';
  }
  lVar5 = *(longlong *)(param_1 + 0x10);
  if ((*param_2 != 0) && (uVar4 = FUN_18067fa90(*param_2,0), lVar5 != 0)) {
    cVar3 = FUN_1812b1d40(lVar5,uVar4,DAT_182256f40);
    if (cVar3 == '\0') {
      return;
    }
    lVar5 = *(longlong *)(param_1 + 0x10);
    if (((*param_2 != 0) && (uVar4 = FUN_18067fa90(*param_2,0), lVar5 != 0)) &&
       (lVar5 = FUN_181414680(lVar5,uVar4,DAT_182227520), lVar5 != 0)) {
      FUN_1813b50f0(&uStack_40,lVar5,DAT_182241ba8);
      uStack_60 = uStack_40;
      uStack_5c = uStack_3c;
      uStack_58 = uStack_38;
      uStack_54 = uStack_34;
      uStack_50 = uStack_30;
      uStack_48 = uStack_28;
LAB_1804148f0:
      cVar3 = FUN_180bbb0a0(&uStack_60,DAT_18225ba78);
      uVar2 = uStack_50;
      if (cVar3 == '\0') {
        FUN_1802698f0(&uStack_60,DAT_182262070);
        return;
      }
      if (*param_2 == 0) goto LAB_1804149e5;
      lVar5 = *(longlong *)(*param_2 + 0x58);
      if (lVar5 != 0) goto code_r0x000180414929;
      goto LAB_1804149e0;
    }
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
code_r0x000180414929:
  cVar3 = FUN_1812b1d40(lVar5,uStack_50 & 0xffffffff,DAT_182258048);
  if (cVar3 != '\0') {
    if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uStackX_c = (undefined4)(uVar2 >> 0x20);
    uVar4 = FUN_180382600(uStackX_c,1);
    if (*param_2 != 0) {
      lVar5 = *(longlong *)(*param_2 + 0x58);
      if (lVar5 != 0) {
        FUN_1812c9b00(lVar5,uVar2 & 0xffffffff,uVar4,DAT_182259798);
        goto LAB_1804148f0;
      }
      FUN_180237af0();
    }
    FUN_180237af0();
LAB_1804149e0:
    FUN_180237af0();
LAB_1804149e5:
    uVar4 = FUN_180237af0();
    FUN_180237ac0(uVar4,0);
    pcVar1 = (code *)swi(3);
    (*pcVar1)();
    return;
  }
  goto LAB_1804148f0;
}



/====================================================================/
/* OwnedAbility
 ===================================================================/

/********************************************************************/
/* OwnedAbility$$get_Ability
 * RVA: 0x272330
 * Address: 0x180272330
 *******************************************************************/


undefined8 FUN_180272330(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x10);
}



/********************************************************************/
/* OwnedAbility$$get_Content
 * RVA: 0x268150
 * Address: 0x180268150
 *******************************************************************/


undefined8 FUN_180268150(longlong param_1)

{
  return *(undefined8 *)(param_1 + 0x18);
}



/********************************************************************/
/* OwnedAbility$$get_MesIdDescription
 * RVA: 0x67AE00
 * Address: 0x18067AE00
 *******************************************************************/


longlong FUN_18067ae00(longlong param_1)

{
  longlong lVar1;
  
  if (DAT_181f71d5a == '\0') {
    thunk_FUN_1801fef70(DAT_181776c90);
    DAT_181f71d5a = '\x01';
  }
  if ((*(longlong *)(param_1 + 0x18) != 0) &&
     (lVar1 = FUN_180a24710(*(longlong *)(param_1 + 0x18),0), lVar1 != 0)) {
    return lVar1;
  }
  return **(longlong **)(DAT_18223c718 + 0xb8);
}



/********************************************************************/
/* OwnedAbility$$get_MesIdName
 * RVA: 0x67AE50
 * Address: 0x18067AE50
 *******************************************************************/


longlong FUN_18067ae50(longlong param_1)

{
  longlong lVar1;
  
  if (DAT_181f71d59 == '\0') {
    thunk_FUN_1801fef70(DAT_181776ca8);
    DAT_181f71d59 = '\x01';
  }
  if ((*(longlong *)(param_1 + 0x18) != 0) &&
     (lVar1 = FUN_180a22000(*(longlong *)(param_1 + 0x18),0), lVar1 != 0)) {
    return lVar1;
  }
  return **(longlong **)(DAT_18223c718 + 0xb8);
}



/********************************************************************/
/* OwnedAbility$$get_SkillLevel
 * RVA: 0x67AEA0
 * Address: 0x18067AEA0
 *******************************************************************/


ulonglong FUN_18067aea0(longlong param_1)

{
  ulonglong uVar1;
  
  uVar1 = *(ulonglong *)(param_1 + 0x20);
  if (uVar1 != 0) {
    return (ulonglong)*(uint *)(uVar1 + 0x18);
  }
  return uVar1;
}



/********************************************************************/
/* OwnedAbility$$set_SkillLevel
 * RVA: 0x67AF70
 * Address: 0x18067AF70
 *******************************************************************/


void FUN_18067af70(longlong param_1,undefined4 param_2)

{
  if (*(longlong *)(param_1 + 0x20) != 0) {
    *(undefined4 *)(*(longlong *)(param_1 + 0x20) + 0x18) = param_2;
  }
  return;
}



/====================================================================/
/* StatusUpProvider
 ===================================================================/

/********************************************************************/
/* StatusUpProvider$$Execution
 * RVA: 0x477620
 * Address: 0x180477620
 *******************************************************************/


longlong StatusUpProvider_Execution
                   (longlong param_1,undefined8 param_2,int param_3,longlong param_4)

{
  code *pcVar1;
  int iVar2;
  int iVar3;
  undefined4 uVar4;
  longlong lVar5;
  longlong lVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  undefined8 uVar9;
  longlong *plVar10;
  
  if (DAT_181f6f2f2 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c4d8);
    DAT_181f6f2f2 = '\x01';
  }
  lVar5 = thunk_FUN_180203bc0(DAT_18225d1a8);
  FUN_180268140(lVar5,0);
  if (lVar5 != 0) {
    *(undefined8 *)(lVar5 + 0x10) = param_2;
    thunk_FUN_180234e20(lVar5 + 0x10,param_2);
    lVar6 = *(longlong *)(lVar5 + 0x10);
    if (param_4 == 0) {
      return lVar6;
    }
    if (lVar6 != 0) {
      iVar2 = FUN_18067f930(lVar6,0);
      if ((*(longlong *)(lVar5 + 0x10) != 0) &&
         (plVar10 = *(longlong **)(*(longlong *)(lVar5 + 0x10) + 0x78), plVar10 != (longlong *)0x0))
      {
        iVar3 = (**(code **)(*plVar10 + 0x1c0))(plVar10,*(undefined8 *)(*plVar10 + 0x1c8));
        FUN_180facea0(iVar3 * iVar2 * param_3,0);
        if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar4 = FUN_180383970(DAT_1822570d8,0);
        *(undefined4 *)(param_1 + 0x10) = uVar4;
        uVar4 = FUN_180383970(DAT_182275b98,0);
        *(undefined4 *)(param_1 + 0x14) = uVar4;
        uVar4 = *(undefined4 *)(param_4 + 0x18);
        uVar7 = *(undefined8 *)(param_4 + 0x10);
        if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar6 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 8);
        if (lVar6 == 0) {
          if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar8 = **(undefined8 **)(DAT_18225d198 + 0xb8);
          lVar6 = thunk_FUN_180203bc0(DAT_18227b6a0);
          FUN_1802a4990(lVar6,uVar8,DAT_18226fe88,DAT_1822342f0);
          plVar10 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 8);
          *plVar10 = lVar6;
          thunk_FUN_180234e20(plVar10,lVar6);
        }
        uVar7 = FUN_1803fd610(uVar7,lVar6,DAT_18223dba0);
        uVar8 = thunk_FUN_180203bc0(DAT_18227b6a0);
        FUN_1802a4990(uVar8,lVar5,DAT_18226fb30,DAT_1822342f0);
        uVar8 = FUN_1803fd610(uVar7,uVar8,DAT_18223dba0);
        FUN_180476c30(param_1,*(undefined8 *)(lVar5 + 0x10),uVar8,uVar4,0);
        FUN_180475d80(param_1,*(undefined8 *)(lVar5 + 0x10),uVar8,uVar4,0);
        uVar7 = *(undefined8 *)(param_4 + 0x10);
        if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar6 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x10);
        if (lVar6 == 0) {
          if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar9 = **(undefined8 **)(DAT_18225d198 + 0xb8);
          lVar6 = thunk_FUN_180203bc0(DAT_18227b6a0);
          FUN_1802a4990(lVar6,uVar9,DAT_18226fe38,DAT_1822342f0);
          plVar10 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x10);
          *plVar10 = lVar6;
          thunk_FUN_180234e20(plVar10,lVar6);
        }
        uVar7 = FUN_1803fd610(uVar7,lVar6,DAT_18223dba0);
        uVar9 = thunk_FUN_180203bc0(DAT_18227b6a0);
        FUN_1802a4990(uVar9,lVar5,DAT_18226fb10,DAT_1822342f0);
        uVar9 = FUN_1803fd610(uVar7,uVar9,DAT_18223dba0);
        FUN_180a7a340(uVar7,DAT_18224c5b8);
        if (*(longlong *)(lVar5 + 0x10) != 0) {
          iVar2 = FUN_18067f8f0(*(longlong *)(lVar5 + 0x10),0);
          FUN_180476980(param_1,*(undefined8 *)(lVar5 + 0x10),uVar9,uVar4,
                        iVar2 == *(int *)(param_4 + 0x24),0);
          FUN_1804759a0(param_1,*(undefined8 *)(lVar5 + 0x10),uVar9,uVar4,0);
          FUN_1804751f0(param_1,*(undefined8 *)(lVar5 + 0x10),uVar8,0);
          return *(longlong *)(lVar5 + 0x10);
        }
      }
    }
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  lVar5 = (*pcVar1)();
  return lVar5;
}



/********************************************************************/
/* StatusUpProvider$$ExecutionSkillUpMagic
 * RVA: 0x475D80
 * Address: 0x180475D80
 *******************************************************************/


/* WARNING: Restarted to delay deadcode elimination for space: stack */

void FUN_180475d80(undefined8 param_1,longlong param_2,undefined8 param_3,int param_4)

{
  code *pcVar1;
  char cVar2;
  undefined4 uVar3;
  int iVar4;
  int iVar5;
  int iVar6;
  uint uVar7;
  undefined4 uVar8;
  undefined4 uVar9;
  longlong lVar10;
  longlong lVar11;
  undefined8 *puVar12;
  ulonglong uVar13;
  undefined8 uVar14;
  longlong lVar15;
  longlong lVar16;
  longlong lVar17;
  ulonglong uVar18;
  ushort uVar19;
  longlong *plVar20;
  int iVar21;
  int iVar22;
  int *piVar23;
  int local_res18;
  int local_108 [4];
  ulonglong local_f8;
  int *local_f0;
  int local_e8 [2];
  undefined8 local_e0;
  longlong *local_d8;
  int *local_d0;
  undefined8 local_c8;
  undefined8 uStack_c0;
  longlong local_b8;
  longlong local_b0;
  undefined8 local_a8;
  undefined8 uStack_a0;
  longlong local_98;
  undefined8 uStack_90;
  undefined4 local_88;
  undefined4 uStack_84;
  undefined4 uStack_80;
  undefined4 uStack_7c;
  longlong local_78;
  undefined8 uStack_70;
  undefined local_50 [8];
  longlong local_48;
  
  if (DAT_181f6f2f5 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c480);
    DAT_181f6f2f5 = '\x01';
  }
  uVar18 = 0;
  local_e8[0] = 0;
  local_a8 = 0;
  uStack_a0 = 0;
  local_98 = 0;
  uStack_90 = 0;
  local_c8 = 0;
  uStack_c0 = 0;
  local_b8 = 0;
  local_f8 = 0;
  local_f0 = local_108;
  local_d0 = local_108;
  if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar10 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x40);
  if (lVar10 == 0) {
    if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) && (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    uVar14 = **(undefined8 **)(DAT_18225d198 + 0xb8);
    lVar10 = thunk_FUN_180203bc0(DAT_18227b6a0);
    FUN_1802a4990(lVar10,uVar14,DAT_18226fce0,DAT_1822342f0);
    plVar20 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x40);
    *plVar20 = lVar10;
    thunk_FUN_180234e20(plVar20,lVar10);
  }
  lVar10 = FUN_1803fd610(param_3,lVar10,DAT_18223dba0);
  lVar11 = thunk_FUN_180203bc0(DAT_18227f6f0);
  FUN_1812c6a20(lVar11,DAT_182255c98);
  local_e0 = lVar11;
  if (lVar10 == 0) {
LAB_180476976:
    FUN_180237af0();
    pcVar1 = (code *)swi(3);
    (*pcVar1)();
    return;
  }
  plVar20 = (longlong *)FUN_1800dcbe0(0,DAT_18225d148,lVar10);
  local_d8 = plVar20;
  while (plVar20 != (longlong *)0x0) {
    cVar2 = FUN_1800dcbe0(0,DAT_18223c7c8,plVar20);
    if (cVar2 == '\0') {
      local_res18 = 0;
      local_108[0] = 0x9d;
      FUN_1800dcbe0(0,DAT_18223c790,plVar20);
      iVar21 = 0;
      if (local_108[0] == 0x9d) {
        local_res18 = -1;
        iVar21 = -1;
      }
      if (lVar11 == 0) goto LAB_180476976;
      FUN_1813b50f0(&local_88,lVar11,DAT_182241ba8);
      local_a8 = CONCAT44(uStack_84,local_88);
      uStack_a0 = CONCAT44(uStack_7c,uStack_80);
      local_98 = local_78;
      uStack_90 = uStack_70;
      piVar23 = local_108;
      iVar22 = local_res18;
      goto LAB_1804760e5;
    }
    lVar10 = *plVar20;
    uVar19 = 0;
    if (*(ushort *)(lVar10 + 0x126) != 0) {
      do {
        if (*(longlong *)(*(longlong *)(lVar10 + 0xb0) + (ulonglong)uVar19 * 0x10) == DAT_18225d128)
        {
          puVar12 = (undefined8 *)
                    (((ulonglong)
                      *(uint *)(*(longlong *)(lVar10 + 0xb0) + 8 + (ulonglong)uVar19 * 0x10) + 0x13)
                     * 0x10 + lVar10);
          goto LAB_180475f85;
        }
        uVar19 = uVar19 + 1;
      } while (uVar19 < *(ushort *)(lVar10 + 0x126));
    }
    puVar12 = (undefined8 *)FUN_1801f5470(plVar20,DAT_18225d128,0);
LAB_180475f85:
    lVar10 = (*(code *)*puVar12)(plVar20,puVar12[1]);
    uVar13 = uVar18;
    if (((lVar10 != 0) && (*(longlong *)(lVar10 + 0x10) != 0)) &&
       (lVar10 = *(longlong *)(*(longlong *)(lVar10 + 0x10) + 0x48), lVar10 != 0)) {
      uVar13 = FUN_18075d910(lVar10,DAT_18223b700);
    }
    if (uVar13 != 0) {
      uVar3 = FUN_180a17d10(uVar13,0);
      local_e8[0] = 0;
      if (lVar11 == 0) {
        FUN_180237af0();
        break;
      }
      FUN_1813c22b0(lVar11,uVar3,local_e8,DAT_182256af0);
      local_e8[0] = local_e8[0] + 1;
      FUN_1812c9b00(lVar11,uVar3,local_e8[0],DAT_182255a70);
    }
  }
  FUN_180237af0();
  FUN_180237ac0(0,0);
LAB_18047691e:
  FUN_180237af0();
LAB_180476923:
  FUN_180237af0();
LAB_180476928:
  FUN_180237af0();
LAB_18047692d:
  FUN_180237af0();
LAB_180476932:
  FUN_180237af0();
  uVar13 = uVar18;
LAB_180476937:
  FUN_180237af0();
LAB_18047693d:
  FUN_180237ac0(uVar13,0);
  uVar18 = uVar13;
LAB_180476947:
  FUN_180237af0();
  uVar13 = uVar18;
LAB_18047694c:
  FUN_180237af0();
LAB_180476951:
  FUN_180237af0();
LAB_180476956:
  FUN_180237af0();
LAB_18047695b:
  FUN_180237af0();
  uVar18 = uVar13;
LAB_180476960:
  FUN_180237af0();
LAB_180476965:
  FUN_180237af0();
  goto LAB_18047696b;
LAB_1804760e5:
  local_res18 = iVar22;
  cVar2 = FUN_180bbb0a0(&local_a8,DAT_18225ba78);
  lVar10 = local_98;
  if (cVar2 != '\0') {
    local_e0 = local_98;
    plVar20 = (longlong *)thunk_FUN_180203bc0(DAT_18225d0c0);
    local_d8 = plVar20;
    FUN_180268140(plVar20,0);
    if (plVar20 == (longlong *)0x0) goto LAB_180476965;
    *(int *)(plVar20 + 2) = (int)lVar10;
    iVar22 = local_res18;
    iVar21 = local_res18;
    if ((param_2 != 0) && (lVar10 = *(longlong *)(param_2 + 0x18), local_b0 = lVar10, lVar10 != 0))
    {
      uVar14 = thunk_FUN_180203bc0(DAT_18227ce90);
      FUN_1802a4990(uVar14,plVar20,DAT_18226fac8,DAT_1822330c8);
      lVar10 = FUN_1803fd610(lVar10,uVar14,DAT_18223d570);
      if ((lVar10 != 0) &&
         (lVar10 = FUN_18075d910(lVar10,DAT_18223b1b8), piVar23 = local_f0, lVar10 != 0)) {
        iVar4 = FUN_18067aea0(lVar10,0);
        if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        iVar5 = FUN_180383110(1,iVar4,1,0);
        piVar23 = local_f0;
        if (0 < iVar5) {
          if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          iVar6 = FUN_180382120(1,iVar4,1,0);
          iVar6 = local_e0._4_4_ - iVar6;
          if (((*(byte *)(DAT_18222f490 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f490 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar3 = FUN_180f99dd0(iVar6 + param_4 + 2,0,0);
          if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          lVar11 = FUN_1808ac390(0);
          if (lVar11 == 0) goto LAB_180476960;
          iVar6 = FUN_1808ac180(lVar11,uVar3,0);
          uVar7 = FUN_180f99de0(iVar6 + iVar4,iVar5,0);
          uVar13 = (ulonglong)uVar7;
          FUN_18067af70(lVar10,uVar7,0);
          uVar18 = local_f8;
          piVar23 = local_f0;
          if (iVar5 <= (int)uVar7) {
            lVar11 = thunk_FUN_180203bc0(DAT_18225d080);
            FUN_180268140(lVar11,0);
            if (((*(byte *)(DAT_18227cdc8 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18227cdc8 + 0xe0) == 0)) {
              il2cpp_runtime_class_init();
            }
            lVar15 = FUN_18086da70(0);
            if (lVar15 == 0) goto LAB_18047695b;
            lVar15 = *(longlong *)(lVar15 + 0x78);
            if (lVar15 == 0) {
LAB_180476386:
              lVar15 = 0;
            }
            else {
              uVar14 = thunk_FUN_180203bc0(DAT_18227cda0);
              FUN_1802a4990(uVar14,local_d8,DAT_18226fa70,DAT_182231570);
              lVar15 = FUN_1803fd610(lVar15,uVar14,DAT_18223ca38);
              if ((lVar15 == 0) || (lVar15 = FUN_18075d910(lVar15,DAT_182239f90), lVar15 == 0))
              goto LAB_180476386;
              local_e0 = 0;
              FUN_180f44000(&local_e0,*(undefined4 *)(lVar15 + 0x14),DAT_1822295d0);
              lVar15 = local_e0;
            }
            iVar4 = (int)lVar15;
            if ((char)((ulonglong)lVar15 >> 0x20) == '\0') {
              iVar4 = 0;
            }
            if (lVar11 == 0) goto LAB_180476956;
            *(int *)(lVar11 + 0x10) = iVar4;
            uVar18 = local_f8;
            piVar23 = local_f0;
            if (iVar4 != 0) {
              if (((*(byte *)(DAT_18227f820 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18227f820 + 0xe0) == 0)) {
                il2cpp_runtime_class_init();
              }
              lVar15 = FUN_1810e8a40(DAT_182263760);
              if (lVar15 == 0) goto LAB_180476951;
              lVar16 = FUN_1808dfd60(lVar15,*(undefined4 *)(lVar11 + 0x10),DAT_182274918);
              lVar15 = FUN_180a7fdc0(lVar15,DAT_18223fa58);
              if (lVar15 == 0) {
LAB_180476534:
                lVar11 = 0;
              }
              else {
                if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) &&
                   (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
                  il2cpp_runtime_class_init();
                }
                lVar17 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x48);
                if (lVar17 == 0) {
                  if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) &&
                     (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
                    il2cpp_runtime_class_init();
                  }
                  uVar14 = **(undefined8 **)(DAT_18225d198 + 0xb8);
                  lVar17 = thunk_FUN_180203bc0(DAT_182273c30);
                  FUN_1802a4990(lVar17,uVar14,DAT_18226fcc0,DAT_182230908);
                  plVar20 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x48);
                  *plVar20 = lVar17;
                  thunk_FUN_180234e20(plVar20,lVar17);
                }
                lVar15 = FUN_1803fc530(lVar15,lVar17,DAT_18223c560);
                if (lVar15 == 0) goto LAB_180476534;
                uVar14 = thunk_FUN_180203bc0(DAT_182273c30);
                FUN_1802a4990(uVar14,lVar11,DAT_18226fa30,DAT_182230908);
                lVar11 = FUN_1803fc530(lVar15,uVar14,DAT_18223c560);
                if (lVar11 == 0) goto LAB_180476534;
                FUN_18075d500(local_50,lVar11,DAT_182239b48);
                lVar11 = local_48;
              }
              uVar18 = local_f8;
              piVar23 = local_f0;
              if ((lVar16 != 0) && (lVar11 != 0)) {
                if (*(longlong *)(lVar10 + 0x18) == 0) goto LAB_18047694c;
                uVar3 = FUN_180a17d10(*(longlong *)(lVar10 + 0x18),0);
                uVar8 = FUN_180a17d10(lVar11,0);
                uVar18 = thunk_FUN_180203bc0(DAT_182272e58);
                FUN_18067acf0(uVar18,lVar16,lVar11,uVar13,0);
                lVar11 = local_b0;
                uVar9 = FUN_1813a58d0(local_b0,lVar10,DAT_18227e648);
                FUN_1813a9f00(lVar11,lVar10,DAT_18224eca0);
                FUN_1814d0830(lVar11,uVar9,uVar18,DAT_182245cb8);
                lVar10 = *(longlong *)(param_2 + 0x40);
                if (lVar10 != 0) {
                  uVar7 = FUN_1813a58d0(lVar10,uVar3,DAT_18227c690);
                  if (uVar7 < 0x80000000) {
                    FUN_1813a9f00(lVar10,uVar3,DAT_18224e350);
                    FUN_181487a90(lVar10,uVar7,uVar8,DAT_18223cec8);
                  }
                  else {
                    FUN_181483420(lVar10,uVar8,DAT_18223cf90);
                  }
                }
                lVar10 = *(longlong *)(param_2 + 0x48);
                if (lVar10 != 0) {
                  uVar7 = FUN_1813a58d0(lVar10,uVar3,DAT_18227c690);
                  if (uVar7 < 0x80000000) {
                    FUN_1813a9f00(lVar10,uVar3,DAT_18224e350);
                    FUN_181487a90(lVar10,uVar7,uVar8,DAT_18223cec8);
                  }
                  else {
                    FUN_181483420(lVar10,uVar8,DAT_18223cf90);
                  }
                }
                if (*(longlong *)(param_2 + 0x10) == 0) goto LAB_180476947;
                FUN_1813a5750(&local_88,*(longlong *)(param_2 + 0x10),DAT_182236160);
                plVar20 = local_d8;
                local_c8 = CONCAT44(uStack_84,local_88);
                uStack_c0 = CONCAT44(uStack_7c,uStack_80);
                local_b8 = local_78;
                while (cVar2 = FUN_180a42760(&local_c8,DAT_182252ba8), lVar10 = local_b8,
                      piVar23 = local_f0, uVar13 = local_f8, cVar2 != '\0') {
                  uVar13 = uVar18;
                  if (*(longlong *)(param_2 + 0x50) == 0) goto LAB_180476937;
                  uVar14 = FUN_1812bdac0(*(longlong *)(param_2 + 0x50),DAT_182240cd0);
                  cVar2 = FUN_180a7b440(uVar14,lVar10,DAT_18224a9f8);
                  if (cVar2 != '\0') {
                    if (*(longlong *)(param_2 + 0x50) == 0) goto LAB_180476932;
                    uVar14 = FUN_1813f1900(*(longlong *)(param_2 + 0x50),lVar10,DAT_1822284f8);
                    lVar11 = plVar20[3];
                    if (lVar11 == 0) {
                      lVar11 = thunk_FUN_180203bc0(DAT_18227ce90);
                      FUN_1802a4990(lVar11,plVar20,DAT_18226fa48,DAT_1822330c8);
                      plVar20[3] = lVar11;
                      thunk_FUN_180234e20(plVar20 + 3,lVar11);
                    }
                    uVar14 = FUN_1803fd610(uVar14,lVar11,DAT_18223d570);
                    uVar14 = FUN_18075d910(uVar14,DAT_18223b1b8);
                    if (*(longlong *)(param_2 + 0x50) == 0) goto LAB_18047692d;
                    lVar11 = FUN_1813f1900(*(longlong *)(param_2 + 0x50),lVar10,DAT_1822284f8);
                    if (lVar11 == 0) goto LAB_180476928;
                    uVar3 = FUN_1813a58d0(lVar11,uVar14,DAT_18227e648);
                    if (*(longlong *)(param_2 + 0x50) == 0) goto LAB_180476923;
                    lVar11 = FUN_1813f1900(*(longlong *)(param_2 + 0x50),lVar10,DAT_1822284f8);
                    if (lVar11 != 0) {
                      FUN_1813a9f00(lVar11,uVar14,DAT_18224eca0);
                    }
                    if (*(longlong *)(param_2 + 0x50) == 0) goto LAB_18047691e;
                    lVar10 = FUN_1813f1900(*(longlong *)(param_2 + 0x50),lVar10,DAT_1822284f8);
                    if (lVar10 != 0) {
                      FUN_1814d0830(lVar10,uVar3,uVar18,DAT_182245cb8);
                    }
                  }
                }
                iVar22 = local_res18 + 1;
                local_f0[iVar22] = 0x458;
                FUN_1802698f0(&local_c8,DAT_18224c950);
                if (uVar13 != 0) goto LAB_18047693d;
                uVar18 = uVar13;
                iVar21 = iVar22;
                if (((iVar22 != -1) && (piVar23[iVar22] == 0x458)) && (-1 < iVar22)) {
                  iVar22 = local_res18;
                  iVar21 = local_res18;
                }
              }
            }
          }
        }
      }
    }
    goto LAB_1804760e5;
  }
  piVar23[iVar21 + 1] = 0x474;
  FUN_1802698f0(&local_a8,DAT_182262070);
  if (uVar18 == 0) {
    return;
  }
LAB_18047696b:
  FUN_180237ac0(uVar18,0);
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* StatusUpProvider$$SkillUpAbilityUsedInMenu
 * RVA: 0x477AC0
 * Address: 0x180477AC0
 *******************************************************************/


undefined8 FUN_180477ac0(undefined8 param_1,undefined4 param_2,undefined8 param_3)

{
  code *pcVar1;
  char cVar2;
  int iVar3;
  int iVar4;
  int iVar5;
  undefined4 uVar6;
  undefined4 uVar7;
  undefined4 uVar8;
  uint uVar9;
  longlong lVar10;
  longlong *plVar11;
  undefined8 *puVar12;
  undefined8 uVar13;
  undefined8 uVar14;
  longlong lVar15;
  longlong lVar16;
  longlong lVar17;
  ulonglong uVar18;
  ulonglong uVar19;
  longlong lVar20;
  undefined8 uVar21;
  longlong lVar22;
  ushort uVar23;
  ulonglong uVar24;
  undefined4 local_88 [4];
  ulonglong local_78;
  undefined8 local_70;
  undefined4 uStack_68;
  undefined4 uStack_64;
  undefined8 local_60;
  undefined4 *local_58;
  undefined4 local_48;
  undefined4 uStack_44;
  undefined4 uStack_40;
  undefined4 uStack_3c;
  undefined8 local_38;
  
  if (DAT_181f6f2fc == '\0') {
    thunk_FUN_1801fef70(DAT_18176c508);
    DAT_181f6f2fc = '\x01';
  }
  local_58 = local_88;
  lVar10 = thunk_FUN_180203bc0(DAT_18225d020);
  FUN_180268140(lVar10,0);
  if (lVar10 != 0) {
    *(undefined4 *)(lVar10 + 0x10) = param_2;
    *(undefined8 *)(lVar10 + 0x18) = param_3;
    thunk_FUN_180234e20((undefined8 *)(lVar10 + 0x18),param_3);
    if (((*(byte *)(DAT_18227e2b0 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e2b0 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    plVar11 = (longlong *)FUN_1805e5510(0);
    if (plVar11 != (longlong *)0x0) {
      lVar15 = *plVar11;
      uVar24 = 0;
      uVar23 = 0;
      if (*(ushort *)(lVar15 + 0x126) != 0) {
        do {
          if (*(longlong *)(*(longlong *)(lVar15 + 0xb0) + (ulonglong)uVar23 * 0x10) ==
              DAT_1822798e8) {
            puVar12 = (undefined8 *)
                      (((ulonglong)
                        *(uint *)(*(longlong *)(lVar15 + 0xb0) + 8 + (ulonglong)uVar23 * 0x10) +
                       0x13) * 0x10 + lVar15);
            goto LAB_180477bd9;
          }
          uVar23 = uVar23 + 1;
        } while (uVar23 < *(ushort *)(lVar15 + 0x126));
      }
      puVar12 = (undefined8 *)FUN_1801f5470(plVar11,DAT_1822798e8,0);
LAB_180477bd9:
      uVar13 = (*(code *)*puVar12)(plVar11,puVar12[1]);
      uVar14 = thunk_FUN_180203bc0(DAT_18227f3d8);
      FUN_1802a4990(uVar14,lVar10,DAT_18226f9f0,DAT_182232f70);
      uVar13 = FUN_1803fd610(uVar13,uVar14,DAT_18223d520);
      lVar15 = FUN_18075d910(uVar13,DAT_18223b110);
      if ((lVar15 == 0) || (lVar22 = *(longlong *)(lVar15 + 0x18), lVar22 == 0)) {
        return 0;
      }
      uVar13 = thunk_FUN_180203bc0(DAT_18227ce90);
      FUN_1802a4990(uVar13,lVar10,DAT_18226f9d0,DAT_1822330c8);
      lVar16 = FUN_1803fd610(lVar22,uVar13,DAT_18223d570);
      if (lVar16 == 0) {
        return 0;
      }
      lVar16 = FUN_18075d910(lVar16,DAT_18223b1b8);
      if (lVar16 == 0) {
        return 0;
      }
      iVar3 = FUN_18067aea0(lVar16,0);
      if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      iVar4 = FUN_180383110(1,iVar3,1,0);
      if (iVar4 < 1) {
        return 0;
      }
      if (((*(byte *)(DAT_18227e218 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e218 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar17 = FUN_1808ac390(0);
      if (lVar17 != 0) {
        iVar5 = FUN_1808ac180(lVar17,2);
        if (((*(byte *)(DAT_18222f490 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f490 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        iVar3 = FUN_180f99de0(iVar3 + iVar5,iVar4,0);
        FUN_18067af70(lVar16,iVar3,0);
        if (iVar3 < iVar4) {
          return 0;
        }
        if (((*(byte *)(DAT_18227cdc8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227cdc8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar17 = FUN_18086da70(0);
        if (lVar17 != 0) {
          lVar17 = *(longlong *)(lVar17 + 0x78);
          uVar18 = uVar24;
          if (lVar17 != 0) {
            uVar13 = thunk_FUN_180203bc0(DAT_18227cda0);
            FUN_1802a4990(uVar13,lVar10,DAT_18226f958,DAT_182231570);
            lVar17 = FUN_1803fd610(lVar17,uVar13,DAT_18223ca38);
            if ((lVar17 != 0) && (lVar17 = FUN_18075d910(lVar17,DAT_182239f90), lVar17 != 0)) {
              local_78 = 0;
              FUN_180f44000(&local_78,*(undefined4 *)(lVar17 + 0x14),DAT_1822295d0);
              uVar18 = local_78;
            }
          }
          uVar19 = uVar18 & 0xffffffff;
          if ((char)(uVar18 >> 0x20) == '\0') {
            uVar19 = uVar24;
          }
          *(int *)(lVar10 + 0x20) = (int)uVar19;
          if ((int)uVar19 == 0) {
            return 1;
          }
          if (((*(byte *)(DAT_18227f820 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f820 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          lVar17 = FUN_1810e8a40(DAT_182263760);
          if (lVar17 != 0) {
            local_78 = FUN_1808dfd60(lVar17,*(undefined4 *)(lVar10 + 0x20),DAT_182274918);
            lVar17 = FUN_180a7fdc0(lVar17,DAT_18223fa58);
            if (lVar17 == 0) {
LAB_180477fd2:
              lVar17 = 0;
            }
            else {
              if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
                il2cpp_runtime_class_init();
              }
              lVar20 = *(longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x90);
              if (lVar20 == 0) {
                if (((*(byte *)(DAT_18225d198 + 0x12f) & 2) != 0) &&
                   (*(int *)(DAT_18225d198 + 0xe0) == 0)) {
                  il2cpp_runtime_class_init();
                }
                uVar13 = **(undefined8 **)(DAT_18225d198 + 0xb8);
                lVar20 = thunk_FUN_180203bc0(DAT_182273c30);
                FUN_1802a4990(lVar20,uVar13,DAT_18226fb78,DAT_182230908);
                plVar11 = (longlong *)(*(longlong *)(DAT_18225d198 + 0xb8) + 0x90);
                *plVar11 = lVar20;
                thunk_FUN_180234e20(plVar11,lVar20);
              }
              lVar17 = FUN_1803fc530(lVar17,lVar20,DAT_18223c560);
              if (lVar17 == 0) goto LAB_180477fd2;
              uVar13 = thunk_FUN_180203bc0(DAT_182273c30);
              FUN_1802a4990(uVar13,lVar10,DAT_18226f998,DAT_182230908);
              lVar17 = FUN_1803fc530(lVar17,uVar13,DAT_18223c560);
              if (lVar17 == 0) goto LAB_180477fd2;
              FUN_18075d500(&local_70,lVar17,DAT_182239b48);
              lVar17 = CONCAT44(uStack_64,uStack_68);
            }
            if ((local_78 == 0) || (lVar17 == 0)) {
              return 1;
            }
            if (*(longlong *)(lVar16 + 0x18) != 0) {
              uVar6 = FUN_180a17d10(*(longlong *)(lVar16 + 0x18),0);
              uVar7 = FUN_180a17d10(lVar17,0);
              local_70 = thunk_FUN_180203bc0(DAT_182272e58);
              FUN_18067acf0(local_70,local_78,lVar17,iVar3,0);
              uVar8 = FUN_1813a58d0(lVar22,lVar16,DAT_18227e648);
              FUN_1813a9f00(lVar22,lVar16,DAT_18224eca0);
              uVar13 = local_70;
              FUN_1814d0830(lVar22,uVar8,local_70,DAT_182245cb8);
              lVar22 = *(longlong *)(lVar15 + 0x40);
              if (lVar22 != 0) {
                uVar9 = FUN_1813a58d0(lVar22,uVar6,DAT_18227c690);
                if (uVar9 < 0x80000000) {
                  FUN_1813a9f00(lVar22,uVar6,DAT_18224e350);
                  FUN_181487a90(lVar22,uVar9,uVar7,DAT_18223cec8);
                }
                else {
                  FUN_181483420(lVar22,uVar7,DAT_18223cf90);
                }
              }
              lVar22 = *(longlong *)(lVar15 + 0x48);
              if (lVar22 != 0) {
                uVar9 = FUN_1813a58d0(lVar22,uVar6,DAT_18227c690);
                if (uVar9 < 0x80000000) {
                  FUN_1813a9f00(lVar22,uVar6,DAT_18224e350);
                  FUN_181487a90(lVar22,uVar9,uVar7,DAT_18223cec8);
                }
                else {
                  FUN_181483420(lVar22,uVar7,DAT_18223cf90);
                }
              }
              if (*(longlong *)(lVar15 + 0x10) != 0) {
                FUN_1813a5750(&local_70,*(longlong *)(lVar15 + 0x10),DAT_182236160);
                local_48 = (undefined4)local_70;
                uStack_44 = local_70._4_4_;
                uStack_40 = uStack_68;
                uStack_3c = uStack_64;
                local_38 = local_60;
                while( true ) {
                  do {
                    cVar2 = FUN_180a42760(&local_48,DAT_182252ba8);
                    uVar14 = local_38;
                    if (cVar2 == '\0') {
                      *local_58 = 0x374;
                      FUN_1802698f0(&local_48,DAT_18224c950);
                      return 1;
                    }
                    if (*(longlong *)(lVar15 + 0x50) == 0) goto LAB_180478359;
                    uVar21 = FUN_1812bdac0(*(longlong *)(lVar15 + 0x50),DAT_182240cd0);
                    cVar2 = FUN_180a7b440(uVar21,uVar14,DAT_18224a9f8);
                  } while (cVar2 == '\0');
                  if (*(longlong *)(lVar15 + 0x50) == 0) break;
                  uVar21 = FUN_1813f1900(*(longlong *)(lVar15 + 0x50),uVar14,DAT_1822284f8);
                  lVar22 = *(longlong *)(lVar10 + 0x28);
                  if (lVar22 == 0) {
                    lVar22 = thunk_FUN_180203bc0(DAT_18227ce90);
                    FUN_1802a4990(lVar22,lVar10,DAT_18226f920,DAT_1822330c8);
                    *(longlong *)(lVar10 + 0x28) = lVar22;
                    thunk_FUN_180234e20(lVar10 + 0x28,lVar22);
                  }
                  uVar21 = FUN_1803fd610(uVar21,lVar22,DAT_18223d570);
                  uVar21 = FUN_18075d910(uVar21,DAT_18223b1b8);
                  if (*(longlong *)(lVar15 + 0x50) == 0) goto LAB_18047834f;
                  lVar22 = FUN_1813f1900(*(longlong *)(lVar15 + 0x50),uVar14,DAT_1822284f8);
                  if (lVar22 == 0) goto LAB_18047834a;
                  uVar6 = FUN_1813a58d0(lVar22,uVar21,DAT_18227e648);
                  if (*(longlong *)(lVar15 + 0x50) == 0) goto LAB_180478345;
                  lVar22 = FUN_1813f1900(*(longlong *)(lVar15 + 0x50),uVar14,DAT_1822284f8);
                  if (lVar22 != 0) {
                    FUN_1813a9f00(lVar22,uVar21,DAT_18224eca0);
                  }
                  if (*(longlong *)(lVar15 + 0x50) == 0) goto LAB_18047833f;
                  lVar22 = FUN_1813f1900(*(longlong *)(lVar15 + 0x50),uVar14,DAT_1822284f8);
                  if (lVar22 != 0) {
                    FUN_1814d0830(lVar22,uVar6,uVar13,DAT_182245cb8);
                  }
                }
                goto LAB_180478354;
              }
            }
          }
        }
      }
    }
  }
  FUN_180237af0();
LAB_18047833f:
  FUN_180237af0();
LAB_180478345:
  FUN_180237af0();
LAB_18047834a:
  FUN_180237af0();
LAB_18047834f:
  FUN_180237af0();
LAB_180478354:
  FUN_180237af0();
LAB_180478359:
  uVar6 = FUN_180237af0();
  FUN_180237ac0(uVar6,0);
  pcVar1 = (code *)swi(3);
  uVar13 = (*pcVar1)();
  return uVar13;
}



/====================================================================/
/* UseItemData
 ===================================================================/

/********************************************************************/
/* UseItemData$$CreateGroup
 * RVA: 0x41D110
 * Address: 0x18041D110
 *******************************************************************/


longlong FUN_18041d110(undefined8 param_1,ulonglong param_2)

{
  code *pcVar1;
  char cVar2;
  longlong lVar3;
  longlong lVar4;
  longlong lVar5;
  undefined8 uVar6;
  ulonglong uVar7;
  uint uVar8;
  ulonglong uVar10;
  ulonglong local_res20;
  ulonglong uVar9;
  
  param_2 = param_2 & 0xffffffff;
  if (DAT_181f6ef12 == '\0') {
    thunk_FUN_1801fef70(DAT_1817666f0);
    DAT_181f6ef12 = '\x01';
  }
  lVar3 = thunk_FUN_180203bc0(DAT_182239560);
  FUN_180f858b0(lVar3,DAT_18223d008);
  if (lVar3 != 0) {
    FUN_181483420(lVar3,param_2,DAT_18223cf90);
    uVar10 = 0;
    uVar9 = uVar10;
    while( true ) {
      if (DAT_181f6ef11 == '\0') {
        thunk_FUN_1801fef70(DAT_181766710);
        DAT_181f6ef11 = '\x01';
      }
      lVar4 = thunk_FUN_180203bc0(DAT_182247a10);
      FUN_1802698f0(lVar4,0);
      if (lVar4 == 0) break;
      *(int *)(lVar4 + 0x10) = (int)param_2;
      if (((*(byte *)(DAT_18227cdc8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227cdc8 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar5 = FUN_18086da70(0);
      if (lVar5 == 0) break;
      lVar5 = *(longlong *)(lVar5 + 0x78);
      uVar7 = uVar10;
      if (lVar5 != 0) {
        uVar6 = thunk_FUN_180203bc0(DAT_18227cda0);
        FUN_1802a4990(uVar6,lVar4,DAT_182265470,DAT_182231570);
        lVar5 = FUN_1803fd610(lVar5,uVar6,DAT_18223ca38);
        if ((lVar5 != 0) && (lVar5 = FUN_18075d910(lVar5,DAT_182239f90), lVar5 != 0)) {
          local_res20 = 0;
          FUN_180f44000(&local_res20,*(undefined4 *)(lVar5 + 0x14),DAT_1822295d0);
          uVar7 = local_res20;
        }
      }
      param_2 = uVar7 & 0xffffffff;
      if ((char)(uVar7 >> 0x20) == '\0') {
        param_2 = uVar10;
      }
      if (((int)param_2 == 0) &&
         (param_2 = (ulonglong)*(uint *)(lVar4 + 0x10), *(uint *)(lVar4 + 0x10) == 0)) {
        return lVar3;
      }
      cVar2 = FUN_181483690(lVar3,param_2,DAT_18224e380);
      if (cVar2 == '\0') {
        FUN_181483420(lVar3,param_2,DAT_18223cf90);
      }
      uVar8 = (int)uVar9 + 1;
      uVar9 = (ulonglong)uVar8;
      if (0xf < (int)uVar8) {
        return lVar3;
      }
    }
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  lVar3 = (*pcVar1)();
  return lVar3;
}



/********************************************************************/
/* UseItemData$$GetNeXTLevelAbilityId
 * RVA: 0x41D2F0
 * Address: 0x18041D2F0
 *******************************************************************/


ulonglong FUN_18041d2f0(undefined8 param_1,undefined4 param_2)

{
  code *pcVar1;
  longlong lVar2;
  longlong lVar3;
  undefined8 uVar4;
  ulonglong uVar5;
  ulonglong local_res20;
  
  if (DAT_181f6ef11 == '\0') {
    thunk_FUN_1801fef70(DAT_181766710);
    DAT_181f6ef11 = '\x01';
  }
  lVar2 = thunk_FUN_180203bc0(DAT_182247a10);
  FUN_1802698f0(lVar2,0);
  if (lVar2 == 0) {
LAB_18041d415:
    FUN_180237af0();
    pcVar1 = (code *)swi(3);
    uVar5 = (*pcVar1)();
    return uVar5;
  }
  *(undefined4 *)(lVar2 + 0x10) = param_2;
  if (((*(byte *)(DAT_18227cdc8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227cdc8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar3 = FUN_18086da70(0);
  if (lVar3 == 0) goto LAB_18041d415;
  lVar3 = *(longlong *)(lVar3 + 0x78);
  if (lVar3 != 0) {
    uVar4 = thunk_FUN_180203bc0(DAT_18227cda0);
    FUN_1802a4990(uVar4,lVar2,DAT_182265470,DAT_182231570);
    lVar3 = FUN_1803fd610(lVar3,uVar4,DAT_18223ca38);
    if ((lVar3 != 0) && (lVar3 = FUN_18075d910(lVar3,DAT_182239f90), lVar3 != 0)) {
      local_res20 = 0;
      FUN_180f44000(&local_res20,*(undefined4 *)(lVar3 + 0x14),DAT_1822295d0);
      goto LAB_18041d3f2;
    }
  }
  local_res20 = 0;
LAB_18041d3f2:
  uVar5 = local_res20 & 0xffffffff;
  if ((char)(local_res20 >> 0x20) == '\0') {
    uVar5 = 0;
  }
  if ((int)uVar5 == 0) {
    uVar5 = (ulonglong)*(uint *)(lVar2 + 0x10);
  }
  return uVar5;
}



/********************************************************************/
/* UseItemData$$IsUseLearningAbility
 * RVA: 0x41D420
 * Address: 0x18041D420
 *******************************************************************/


ulonglong UseItemData_IsUseLearningAbility(longlong param_1,undefined4 param_2,undefined4 param_3)

{
  code *pcVar1;
  longlong lVar2;
  char cVar3;
  ushort uVar4;
  undefined4 uVar5;
  longlong lVar6;
  longlong lVar7;
  ulonglong uVar8;
  ulonglong uVar9;
  undefined8 uVar10;
  undefined8 uVar11;
  ulonglong uVar12;
  undefined8 *puVar13;
  longlong *plVar14;
  int aiStack_68 [4];
  undefined4 uStack_58;
  int *piStack_48;
  longlong *plStack_40;
  
  if (DAT_181f6ef10 == '\0') {
    thunk_FUN_1801fef70(DAT_18176671c);
    DAT_181f6ef10 = '\x01';
  }
  piStack_48 = aiStack_68;
  uStack_58 = 0xffffffff;
  lVar6 = thunk_FUN_180203bc0(DAT_182247ac8);
  FUN_1802698f0(lVar6,0);
  if (lVar6 != 0) {
    *(undefined4 *)(lVar6 + 0x10) = param_3;
    if (((*(byte *)(DAT_18227f820 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f820 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar2 = DAT_182247f28;
    lVar7 = *(longlong *)(DAT_182247f28 + 0x18);
    if ((*(byte *)(lVar7 + 0x12e) & 1) == 0) {
      FUN_1801fd890(lVar7);
    }
    lVar7 = **(longlong **)(lVar7 + 0xc0);
    if ((*(byte *)(lVar7 + 0x12e) & 1) == 0) {
      FUN_1801fd890(lVar7);
    }
    if ((*(byte *)(lVar7 + 0x12f) & 2) != 0) {
      lVar7 = *(longlong *)(lVar2 + 0x18);
      if ((*(byte *)(lVar7 + 0x12e) & 1) == 0) {
        FUN_1801fd890(lVar7);
      }
      lVar7 = **(longlong **)(lVar7 + 0xc0);
      if ((*(byte *)(lVar7 + 0x12e) & 1) == 0) {
        FUN_1801fd890(lVar7);
      }
      if (*(int *)(lVar7 + 0xe0) == 0) {
        lVar7 = *(longlong *)(lVar2 + 0x18);
        if ((*(byte *)(lVar7 + 0x12e) & 1) == 0) {
          FUN_1801fd890(lVar7);
        }
        lVar7 = **(longlong **)(lVar7 + 0xc0);
        if ((*(byte *)(lVar7 + 0x12e) & 1) == 0) {
          FUN_1801fd890(lVar7);
        }
        il2cpp_runtime_class_init(lVar7);
      }
    }
    lVar7 = *(longlong *)(lVar2 + 0x18);
    if ((*(byte *)(lVar7 + 0x12e) & 1) == 0) {
      FUN_1801fd890(lVar7);
    }
    lVar7 = **(longlong **)(lVar7 + 0xc0);
    if ((*(byte *)(lVar7 + 0x12e) & 1) == 0) {
      FUN_1801fd890(lVar7);
    }
    uVar9 = *(ulonglong *)(lVar7 + 0xb8);
    if (*(char *)(*(ulonglong *)(lVar7 + 0xb8) + 8) == '\0') goto LAB_18041dab2;
    if (((*(byte *)(DAT_18227f820 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f820 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar7 = FUN_1810e8a40(DAT_182263760);
    if (lVar7 != 0) {
      uVar8 = FUN_1808dfd60(lVar7,param_2,DAT_182274708);
      uVar9 = uVar8;
      if ((uVar8 == 0) || (uVar9 = FUN_180a17fc0(uVar8,0), (int)uVar9 != 1)) goto LAB_18041dab2;
      if (((*(byte *)(DAT_18227f820 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f820 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar7 = FUN_1810e8a40(DAT_182263760);
      uVar5 = FUN_180a18040(uVar8,0);
      if (lVar7 != 0) {
        uVar9 = FUN_1808dfd60(lVar7,uVar5,DAT_182274490);
        if (uVar9 == 0) goto LAB_18041dab2;
        if (((*(byte *)(DAT_18227f820 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f820 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar7 = FUN_1810e8a40(DAT_182263760);
        uVar5 = FUN_180a264b0(uVar9,0);
        if (lVar7 != 0) {
          uVar9 = FUN_1808dfd60(lVar7,uVar5,DAT_182274600);
          if (uVar9 == 0) goto LAB_18041dab2;
          if (((*(byte *)(DAT_18227f820 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f820 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          lVar7 = FUN_1810e8a40(DAT_182263760);
          uVar5 = FUN_180a18040(uVar9,0);
          if (lVar7 != 0) {
            uVar8 = FUN_1808dfd60(lVar7,uVar5,DAT_182274918);
            uVar9 = uVar8;
            if (uVar8 == 0) goto LAB_18041dab2;
            if (((*(byte *)(DAT_18227e2b0 + 0x12f) & 2) != 0) &&
               (*(int *)(DAT_18227e2b0 + 0xe0) == 0)) {
              il2cpp_runtime_class_init();
            }
            lVar7 = FUN_1805e5510(0);
            if (lVar7 != 0) {
              uVar10 = FUN_1805e4920(lVar7,0,0);
              uVar11 = thunk_FUN_180203bc0(DAT_18227f3d8);
              FUN_1802a4990(uVar11,lVar6,DAT_1822654a0,DAT_182232f70);
              uVar10 = FUN_1803fd610(uVar10,uVar11,DAT_18223d520);
              uVar12 = FUN_18075d910(uVar10,DAT_18223b110);
              uVar9 = uVar12;
              if (uVar12 == 0) goto LAB_18041dab2;
              if (((*(byte *)(DAT_18227f820 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18227f820 + 0xe0) == 0)) {
                il2cpp_runtime_class_init();
              }
              lVar6 = FUN_1810e8a40(DAT_182263760);
              if (lVar6 != 0) {
                uVar9 = FUN_1808dfd60(lVar6,*(undefined4 *)(param_1 + 0x10),DAT_182274770);
                if (uVar9 == 0) {
LAB_18041dab2:
                  return uVar9 & 0xffffffffffffff00;
                }
                if (((*(byte *)(DAT_18227f820 + 0x12f) & 2) != 0) &&
                   (*(int *)(DAT_18227f820 + 0xe0) == 0)) {
                  il2cpp_runtime_class_init();
                }
                uVar10 = FUN_1810e8a40(DAT_182263760);
                uVar10 = FUN_1808f4380(uVar10,uVar9,*(undefined8 *)(uVar12 + 0x18),0,0);
                if (((*(byte *)(DAT_182247ab8 + 0x12f) & 2) != 0) &&
                   (*(int *)(DAT_182247ab8 + 0xe0) == 0)) {
                  il2cpp_runtime_class_init(DAT_182247ab8);
                }
                lVar6 = *(longlong *)(*(longlong *)(DAT_182247ab8 + 0xb8) + 8);
                if (lVar6 == 0) {
                  if (((*(byte *)(DAT_182247ab8 + 0x12f) & 2) != 0) &&
                     (*(int *)(DAT_182247ab8 + 0xe0) == 0)) {
                    il2cpp_runtime_class_init(DAT_182247ab8);
                  }
                  uVar11 = **(undefined8 **)(DAT_182247ab8 + 0xb8);
                  lVar6 = thunk_FUN_180203bc0(DAT_18227ce90);
                  FUN_1802a4990(lVar6,uVar11,DAT_1822654d0,DAT_1822330c8);
                  plVar14 = (longlong *)(*(longlong *)(DAT_182247ab8 + 0xb8) + 8);
                  *plVar14 = lVar6;
                  thunk_FUN_180234e20(plVar14,lVar6);
                }
                lVar6 = FUN_1803fd610(uVar10,lVar6,DAT_18223d570);
                uVar9 = FUN_180bb03c0(lVar6,DAT_182279c90);
                if (*(int *)(param_1 + 0x14) <= (int)uVar9) goto LAB_18041dab2;
                uVar5 = FUN_180a17d10(uVar8,0);
                lVar7 = FUN_18041d110(param_1,uVar5,0);
                if (lVar6 != 0) {
                  plVar14 = (longlong *)FUN_1800dcbe0(0,DAT_182247a58,lVar6);
                  plStack_40 = plVar14;
                  while (plVar14 != (longlong *)0x0) {
                    cVar3 = FUN_1800dcbe0(0,DAT_18223c7c8,plVar14);
                    if (cVar3 == '\0') {
                      aiStack_68[0] = 0x154;
                      goto LAB_18041da68;
                    }
                    lVar6 = *plVar14;
                    uVar4 = 0;
                    if (*(ushort *)(lVar6 + 0x126) != 0) {
                      do {
                        if (*(longlong *)(*(longlong *)(lVar6 + 0xb0) + (ulonglong)uVar4 * 0x10) ==
                            DAT_182247a40) {
                          puVar13 = (undefined8 *)
                                    (((ulonglong)
                                      *(uint *)(*(longlong *)(lVar6 + 0xb0) + 8 +
                                               (ulonglong)uVar4 * 0x10) + 0x13) * 0x10 + lVar6);
                          goto LAB_18041d9d5;
                        }
                        uVar4 = uVar4 + 1;
                      } while (uVar4 < *(ushort *)(lVar6 + 0x126));
                    }
                    puVar13 = (undefined8 *)FUN_1801f5470(plVar14,DAT_182247a40,0);
LAB_18041d9d5:
                    lVar6 = (*(code *)*puVar13)(plVar14,puVar13[1]);
                    if (lVar6 == 0) goto LAB_18041dac7;
                    if (*(longlong *)(lVar6 + 0x10) == 0) goto LAB_18041dac2;
                    uVar5 = FUN_180a17d10(*(longlong *)(lVar6 + 0x10),0);
                    if (lVar7 == 0) goto LAB_18041dabc;
                    cVar3 = FUN_181483690(lVar7,uVar5,DAT_18224e380);
                    if (cVar3 != '\0') {
                      aiStack_68[0] = 0x156;
LAB_18041da68:
                      uStack_58 = 0;
                      FUN_1800dcbe0(0,DAT_18223c790,plVar14);
                      if (aiStack_68[0] == 0x156) {
                        return 0;
                      }
                      return 1;
                    }
                  }
                  goto LAB_18041dacc;
                }
              }
            }
          }
        }
      }
    }
  }
  FUN_180237af0();
LAB_18041dabc:
  FUN_180237af0();
LAB_18041dac2:
  FUN_180237af0();
LAB_18041dac7:
  FUN_180237af0();
LAB_18041dacc:
  FUN_180237af0();
  FUN_180237ac0(0,0);
  pcVar1 = (code *)swi(3);
  uVar9 = (*pcVar1)();
  return uVar9;
}

