/*
 * FF2 Decompiled Functions - Skill Level Calculation
 * Generated by Ghidra headless analysis
 * Program: GameAssembly.dll
 * Image Base: 0x180000000
 * IL2CPP types applied: True
 *
 * Purpose: Understanding how FF2 converts raw SkillLevel to display level
 *
 * Problem: OwnedAbility.SkillLevel appears to store raw exp, not actual level
 *          Cure shows 'lv3' when it should be 'lv1', then 'lv6' after one cast
 *          Need to find the formula: actualLevel = f(rawSkillLevel)
 *
 * Key functions:
 *   - SkillLevelProvider.SettingSkillLevel: Converts raw data to text/gauge
 *   - ParameterProvider.GetSkillLevel: Converts exp to level (private)
 *   - BattleUtility.GetSkillLevel: Reference (works for weapons)
 *   - UpdateAbilitySkillLevel: UI update methods
 */


/====================================================================/
/* BattleUtility
 ===================================================================/

/********************************************************************/
/* BattleUtility$$GetSkillLevel
 * RVA: 0x913900
 * Address: 0x180913900
 *******************************************************************/


ulonglong FUN_180913900(longlong param_1,int param_2)

{
  code *pcVar1;
  int iVar2;
  char cVar3;
  ulonglong uVar4;
  int local_res10 [2];
  
  if (DAT_181f73ae9 == '\0') {
    thunk_FUN_1801fef70(DAT_1817e733c);
    DAT_181f73ae9 = '\x01';
  }
  local_res10[0] = 0;
  if (param_2 - 8U < 2) {
    if (param_1 != 0) {
      if (*(longlong *)(param_1 + 0x58) == 0) goto LAB_180913a9a;
      cVar3 = FUN_1813c22b0(*(longlong *)(param_1 + 0x58),param_2,local_res10,DAT_182258028);
      if (cVar3 != '\0') {
        if (local_res10[0] == 0) {
          return 1;
        }
        return (ulonglong)(local_res10[0] / 100 + 1);
      }
    }
  }
  else {
    if (param_2 - 10U < 2) {
      if (param_1 != 0) {
        if (*(longlong *)(param_1 + 0x58) == 0) {
LAB_180913a9a:
          FUN_180237af0();
          pcVar1 = (code *)swi(3);
          uVar4 = (*pcVar1)();
          return uVar4;
        }
        FUN_1813c22b0(*(longlong *)(param_1 + 0x58),param_2,local_res10,DAT_182258028);
      }
      iVar2 = local_res10[0];
      if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      uVar4 = FUN_180382120(1,iVar2,0xc9);
      return uVar4;
    }
    if (param_1 != 0) {
      if (*(longlong *)(param_1 + 0x58) == 0) goto LAB_180913a9a;
      cVar3 = FUN_1813c22b0(*(longlong *)(param_1 + 0x58),param_2,local_res10,DAT_182258028);
      iVar2 = local_res10[0];
      if (cVar3 != '\0') {
        if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar4 = FUN_180382120(1,iVar2,1,0);
        return uVar4;
      }
    }
  }
  return 0;
}



/====================================================================/
/* CommonGauge
 ===================================================================/

/********************************************************************/
/* CommonGauge$$GetFillAmount
 * RVA: 0x3D6090
 * Address: 0x1803D6090
 *******************************************************************/


void CommonGauge_GetFillAmount(longlong param_1,undefined8 param_2,undefined8 param_3)

{
  uint uVar1;
  undefined8 uVar2;
  code *pcVar3;
  undefined4 uVar4;
  char cVar5;
  longlong lVar6;
  undefined8 uVar7;
  longlong lVar8;
  undefined4 *puVar9;
  longlong *plVar10;
  longlong unaff_RBX;
  undefined4 *unaff_RBP;
  int unaff_ESI;
  longlong unaff_RDI;
  longlong unaff_R14;
  longlong unaff_R15;
  undefined4 extraout_XMM0_Da;
  undefined4 uVar11;
  undefined4 uVar12;
  
  do {
    FUN_1806bd3a0(param_1,param_2,param_3);
    FUN_1806bd530(unaff_RBX,0);
    do {
      cVar5 = FUN_180a42760(unaff_RBP + 4);
      if (cVar5 == '\0') {
        *(undefined4 *)(unaff_R15 + 4 + (longlong)unaff_ESI * 4) = 0x7d;
        FUN_1802698f0(unaff_RBP + 4,DAT_182249f90);
        uVar7 = *(undefined8 *)(unaff_RDI + 0x90);
        if (((*(byte *)(DAT_1822466b8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822466b8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        lVar6 = *(longlong *)(*(longlong *)(DAT_1822466b8 + 0xb8) + 0x20);
        if (lVar6 == 0) {
          if (((*(byte *)(DAT_1822466b8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822466b8 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init();
          }
          uVar2 = **(undefined8 **)(DAT_1822466b8 + 0xb8);
          lVar6 = thunk_FUN_180203bc0(DAT_18224fac8);
          FUN_1802a4990(lVar6,uVar2,DAT_182284fc0,DAT_18222e630);
          plVar10 = (longlong *)(*(longlong *)(DAT_1822466b8 + 0xb8) + 0x20);
          *plVar10 = lVar6;
          thunk_FUN_180234e20(plVar10,lVar6);
        }
        uVar7 = FUN_1803f9860(uVar7,lVar6,DAT_18223a378);
        if (((*(byte *)(DAT_1822466b8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822466b8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_1822466b8);
        }
        lVar6 = *(longlong *)(*(longlong *)(DAT_1822466b8 + 0xb8) + 0x28);
        if (lVar6 == 0) {
          if (((*(byte *)(DAT_1822466b8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822466b8 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_1822466b8);
          }
          uVar2 = **(undefined8 **)(DAT_1822466b8 + 0xb8);
          lVar6 = thunk_FUN_180203bc0(DAT_18224fa90);
          FUN_1802a4990(lVar6,uVar2,DAT_182264870,DAT_182234bc8);
          plVar10 = (longlong *)(*(longlong *)(DAT_1822466b8 + 0xb8) + 0x28);
          *plVar10 = lVar6;
          thunk_FUN_180234e20(plVar10,lVar6);
        }
        uVar7 = FUN_1803fd610(uVar7,lVar6,DAT_18223dfb8);
        if (((*(byte *)(DAT_1822466b8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822466b8 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_1822466b8);
        }
        lVar6 = *(longlong *)(*(longlong *)(DAT_1822466b8 + 0xb8) + 0x30);
        if (lVar6 == 0) {
          if (((*(byte *)(DAT_1822466b8 + 0x12f) & 2) != 0) && (*(int *)(DAT_1822466b8 + 0xe0) == 0)
             ) {
            il2cpp_runtime_class_init(DAT_1822466b8);
          }
          uVar2 = **(undefined8 **)(DAT_1822466b8 + 0xb8);
          lVar6 = thunk_FUN_180203bc0(DAT_18224fa78);
          FUN_1802a4990(lVar6,uVar2,DAT_182227e50,DAT_182234b78);
          plVar10 = (longlong *)(*(longlong *)(DAT_1822466b8 + 0xb8) + 0x30);
          *plVar10 = lVar6;
          thunk_FUN_180234e20(plVar10,lVar6);
        }
        uVar7 = FUN_1803f8f90(uVar7,lVar6,DAT_18223b718);
        uVar12 = FUN_18075ca80(uVar7,DAT_182239558);
        lVar6 = *(longlong *)(unaff_RDI + 0x90);
        if (*(longlong *)(unaff_RDI + 0xa0) != 0) {
          uVar1 = *(uint *)(*(longlong *)(unaff_RDI + 0xa0) + 0x18);
          if (lVar6 != 0) {
            if (*(uint *)(lVar6 + 0x18) <= uVar1) {
              FUN_180d2bc30(0);
            }
            lVar6 = *(longlong *)(*(longlong *)(lVar6 + 0x10) + 0x20 + (longlong)(int)uVar1 * 8);
            if ((lVar6 == 0) || (*(longlong *)(lVar6 + 0x48) == 0)) {
              if (*(longlong *)(unaff_RDI + 0xa0) == 0) goto LAB_1803d663b;
              *(undefined4 *)(*(longlong *)(unaff_RDI + 0xa0) + 0x18) = uVar12;
            }
            lVar6 = *(longlong *)(unaff_RDI + 0xa0);
            if (lVar6 != 0) {
              uVar12 = *(undefined4 *)(lVar6 + 0x18);
              if (DAT_181f6ebaf == '\0') {
                thunk_FUN_1801fef70(DAT_1817e68d4);
                DAT_181f6ebaf = '\x01';
              }
              if (((*(byte *)(DAT_18222f850 + 0x12f) & 2) != 0) &&
                 (*(int *)(DAT_18222f850 + 0xe0) == 0)) {
                il2cpp_runtime_class_init();
              }
              cVar5 = FUN_180fa6b10(lVar6,0,0);
              uVar11 = extraout_XMM0_Da;
              if (cVar5 == '\0') {
                lVar8 = *(longlong *)(unaff_RDI + 0x90);
                if (lVar8 == 0) goto LAB_1803d663b;
                if (*(int *)(lVar6 + 0x18) < *(int *)(lVar8 + 0x18)) {
                  lVar8 = FUN_18075a990(lVar8,uVar12,DAT_18223c840);
                  *(undefined4 *)(lVar6 + 0x18) = uVar12;
                  if (lVar8 == 0) goto LAB_1803d663b;
                  uVar7 = FUN_1802cf190(lVar8,0);
                  uVar11 = FUN_1804e2f10(lVar6,uVar7,1,0);
                }
              }
              if (*(longlong *)(unaff_RDI + 0xa0) != 0) {
                FUN_1803d5af0(uVar11,*(undefined4 *)(*(longlong *)(unaff_RDI + 0xa0) + 0x18),0);
                *(undefined *)(unaff_RDI + 0xc0) = 0;
                FUN_180c9ce30(*(undefined8 *)(unaff_RDI + 0xa0),1,0);
                uVar7 = thunk_FUN_180203bc0(DAT_182251cb8);
                FUN_1802a4990(uVar7);
                *(undefined8 *)(unaff_RDI + 0x88) = uVar7;
                thunk_FUN_180234e20((undefined8 *)(unaff_RDI + 0x88),uVar7);
                if (*(longlong *)(unaff_RDI + 0x60) != 0) {
                  unaff_R14 = *(longlong *)(*(longlong *)(unaff_RDI + 0x60) + 0x18);
                }
                if (((*(byte *)(DAT_18222f850 + 0x12f) & 2) != 0) &&
                   (*(int *)(DAT_18222f850 + 0xe0) == 0)) {
                  il2cpp_runtime_class_init();
                }
                cVar5 = FUN_180fa6d50(unaff_R14,0,0);
                if (cVar5 == '\0') {
LAB_1803d65f2:
                  uVar7 = thunk_FUN_180203bc0(DAT_182235fe8);
                  FUN_1802a4990(uVar7);
                  *(undefined8 *)(unaff_RDI + 0xb8) = uVar7;
                  thunk_FUN_180234e20((undefined8 *)(unaff_RDI + 0xb8),uVar7);
                  return;
                }
                if (unaff_R14 != 0) {
                  uVar7 = *(undefined8 *)(unaff_R14 + 0x18);
                  if (((*(byte *)(DAT_18222f850 + 0x12f) & 2) != 0) &&
                     (*(int *)(DAT_18222f850 + 0xe0) == 0)) {
                    il2cpp_runtime_class_init();
                  }
                  cVar5 = FUN_180fa6d50(uVar7,0,0);
                  if (cVar5 == '\0') goto LAB_1803d65f2;
                  if ((*(longlong *)(unaff_RDI + 0x58) != 0) &&
                     (lVar6 = *(longlong *)(*(longlong *)(unaff_RDI + 0x58) + 0x10), lVar6 != 0)) {
                    uVar12 = FUN_180a263f0(lVar6,0);
                    cVar5 = FUN_180379d80(uVar12,0);
                    if (*(longlong *)(unaff_R14 + 0x18) != 0) {
                      uVar12 = FUN_180f08ea0(*(longlong *)(unaff_R14 + 0x18),cVar5 != '\0',0);
                      uVar7 = *(undefined8 *)(unaff_R14 + 0x20);
                      if (cVar5 != '\0') {
                        if (((*(byte *)(DAT_18227f680 + 0x12f) & 2) != 0) &&
                           (*(int *)(DAT_18227f680 + 0xe0) == 0)) {
                          uVar12 = il2cpp_runtime_class_init(DAT_18227f680);
                        }
                        uVar11 = **(undefined4 **)(DAT_18227f680 + 0xb8);
                      }
                      else {
                        if (((*(byte *)(DAT_18227f680 + 0x12f) & 2) != 0) &&
                           (*(int *)(DAT_18227f680 + 0xe0) == 0)) {
                          uVar12 = il2cpp_runtime_class_init(DAT_18227f680);
                        }
                        uVar11 = *(undefined4 *)(*(longlong *)(DAT_18227f680 + 0xb8) + 0x10);
                      }
                      puVar9 = (undefined4 *)FUN_1810cb520(uVar12,uVar11,0);
                      uVar12 = puVar9[1];
                      uVar11 = puVar9[2];
                      uVar4 = puVar9[3];
                      *unaff_RBP = *puVar9;
                      unaff_RBP[1] = uVar12;
                      unaff_RBP[2] = uVar11;
                      unaff_RBP[3] = uVar4;
                      FUN_180c9cfc0(uVar7);
                      goto LAB_1803d65f2;
                    }
                  }
                }
              }
            }
          }
        }
LAB_1803d663b:
        FUN_180237af0();
        pcVar3 = (code *)swi(3);
        (*pcVar3)();
        return;
      }
      param_1 = *(longlong *)(unaff_RBP + 8);
      if (param_1 == 0) {
        uVar12 = FUN_180237af0();
        FUN_180237ac0(uVar12,0);
        pcVar3 = (code *)swi(3);
        (*pcVar3)();
        return;
      }
    } while (*(longlong *)(param_1 + 0x48) == 0);
    param_3 = 0;
    param_2 = 0;
    unaff_RBX = param_1;
  } while( true );
}



/********************************************************************/
/* CommonGauge$$SetFillAmount
 * RVA: 0x3D6100
 * Address: 0x1803D6100
 *******************************************************************/

/* DECOMPILATION FAILED: Could not create function at 0x1803D6100 */

/====================================================================/
/* KeyInput_AbilityContentListController
 ===================================================================/

/********************************************************************/
/* KeyInput_AbilityContentListController$$UpdateAbilitySkillLevel
 * RVA: 0x4DDCE0
 * Address: 0x1804DDCE0
 *******************************************************************/


ulonglong KeyInput_AbilityContentListController_UpdateAbilitySkillLevel(void)

{
  code *pcVar1;
  longlong lVar2;
  undefined8 uVar3;
  ulonglong uVar4;
  uint unaff_EBX;
  longlong unaff_RSI;
  longlong unaff_RDI;
  longlong unaff_R14;
  longlong unaff_R15;
  undefined in_ZF;
  
  while ((!(bool)in_ZF && (lVar2 = *(longlong *)(unaff_RSI + 0x10), unaff_RDI != 0))) {
    uVar3 = FUN_180fa6aa0(unaff_RDI,0);
    if (lVar2 == 0) break;
    uVar4 = FUN_1812b1d40(lVar2,uVar3,DAT_182254578);
    if ((char)uVar4 == '\0') {
      lVar2 = *(longlong *)(unaff_RSI + 0x10);
      uVar3 = FUN_180fa6aa0(unaff_RDI,0);
      if (lVar2 == 0) break;
      uVar4 = FUN_1812b1b00(lVar2,uVar3,unaff_RDI,DAT_1822504d0);
    }
    do {
      unaff_EBX = unaff_EBX + 1;
      if ((int)*(uint *)(unaff_R15 + 0x18) <= (int)unaff_EBX) {
        if (*(longlong *)(unaff_R14 + 0x30) != 0) {
          uVar4 = FUN_18155f810(*(longlong *)(unaff_R14 + 0x30),0);
          if (uVar4 != 0) {
            uVar4 = FUN_18155ff80(uVar4,0,0);
          }
        }
        return uVar4 & 0xffffffffffffff00;
      }
      if (*(uint *)(unaff_R15 + 0x18) <= unaff_EBX) {
        uVar3 = thunk_FUN_1801f53e0();
        FUN_180237ac0(uVar3,0);
        pcVar1 = (code *)swi(3);
        uVar4 = (*pcVar1)();
        return uVar4;
      }
      if (*(longlong *)(unaff_R14 + 0x30) == 0) goto LAB_1804ddd8d;
      lVar2 = FUN_18155f810(*(longlong *)(unaff_R14 + 0x30),0);
      if (lVar2 == 0) goto LAB_1804ddd8d;
      unaff_RDI = FUN_180758700(lVar2);
      if (((*(byte *)(DAT_18222f850 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f850 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      uVar4 = FUN_180fa6d50(unaff_RDI);
    } while ((char)uVar4 == '\0');
    in_ZF = unaff_RSI == 0;
  }
LAB_1804ddd8d:
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  uVar4 = (*pcVar1)();
  return uVar4;
}



/====================================================================/
/* KeyInput_BattleAbilityInfomationContentController
 ===================================================================/

/********************************************************************/
/* KeyInput_BattleAbilityInfomationContentController$$SetSkillLevel
 * RVA: 0x4E14C0
 * Address: 0x1804E14C0
 *******************************************************************/


void KeyInput_BattleAbilityInfomationContentController_SetSkillLevel
               (longlong param_1,undefined8 param_2)

{
  if (*(longlong *)(param_1 + 0x30) != 0) {
    FUN_180c9d330(*(undefined8 *)(*(longlong *)(param_1 + 0x30) + 0x50),param_2,0);
    return;
  }
  return;
}



/********************************************************************/
/* KeyInput_BattleAbilityInfomationContentController$$SetSkillLevelGauge
 * RVA: 0x4E14A0
 * Address: 0x1804E14A0
 *******************************************************************/


void KeyInput_BattleAbilityInfomationContentController_SetSkillLevelGauge
               (longlong param_1,undefined8 param_2)

{
  if (*(longlong *)(param_1 + 0x38) != 0) {
    FUN_1805335a0(*(longlong *)(param_1 + 0x38),param_2,0);
    return;
  }
  return;
}



/********************************************************************/
/* KeyInput_BattleAbilityInfomationContentController$$UpdateAbilitySkillLevel
 * RVA: 0x4E1500
 * Address: 0x1804E1500
 *******************************************************************/


void FUN_1804e1500(longlong param_1,longlong param_2)

{
  undefined4 uVar1;
  longlong lVar2;
  
  if (param_2 != 0) {
    uVar1 = FUN_18067aea0(param_2,0);
    lVar2 = *(longlong *)(param_1 + 0x30);
    if (lVar2 != 0) {
      lVar2 = *(longlong *)(lVar2 + 0x50);
    }
    FUN_1806fc630(uVar1,lVar2,*(undefined8 *)(param_1 + 0x38),0);
  }
  return;
}



/********************************************************************/
/* KeyInput_BattleAbilityInfomationContentController$$UpdateView_OwnedAbility
 * RVA: 0x4E1640
 * Address: 0x1804E1640
 *******************************************************************/


void FUN_1804e1640(longlong param_1,longlong param_2,undefined param_3)

{
  longlong lVar1;
  code *pcVar2;
  longlong lVar3;
  undefined8 uVar4;
  undefined8 uVar5;
  undefined4 local_res8 [2];
  
  if (DAT_181f6f7c2 == '\0') {
    thunk_FUN_1801fef70(DAT_1817de908);
    DAT_181f6f7c2 = '\x01';
  }
  uVar5 = 0;
  *(longlong *)(param_1 + 0x18) = param_2;
  local_res8[0] = 0;
  thunk_FUN_180234e20((longlong *)(param_1 + 0x18),param_2);
  if (param_2 != 0) {
    if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar3 = FUN_1810e8a40(DAT_182263388);
    lVar1 = *(longlong *)(param_1 + 0x30);
    if (lVar1 != 0) {
      uVar4 = FUN_18067ae50(param_2,0);
      if (lVar3 == 0) {
        FUN_180237af0();
        pcVar2 = (code *)swi(3);
        (*pcVar2)();
        return;
      }
      uVar4 = FUN_1804d9ab0(lVar3,uVar4,1,0);
      FUN_1804e1ac0(lVar1,uVar4,0);
      lVar1 = *(longlong *)(param_1 + 0x30);
      if (lVar1 != 0) {
        FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x40),param_3,0);
        FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x48),param_3,0);
        lVar1 = *(longlong *)(param_1 + 0x30);
        if (lVar1 != 0) {
          if (*(longlong *)(param_2 + 0x10) != 0) {
            local_res8[0] = FUN_180a18610(*(longlong *)(param_2 + 0x10),0);
            uVar5 = FUN_180d7cc10(local_res8,0);
          }
          FUN_180c9d330(*(undefined8 *)(lVar1 + 0x48),uVar5,0);
        }
      }
    }
  }
  return;
}



/====================================================================/
/* OwnedAbilitySaveData
 ===================================================================/

/********************************************************************/
/* OwnedAbilitySaveData$$get_SkillLevel
 * RVA: 0x67B080
 * Address: 0x18067B080
 *******************************************************************/

/* DECOMPILATION FAILED: Could not create function at 0x18067B080 */

/********************************************************************/
/* OwnedAbilitySaveData$$set_SkillLevel
 * RVA: 0x67B0A0
 * Address: 0x18067B0A0
 *******************************************************************/


undefined8 OwnedAbilitySaveData_set_SkillLevel(void)

{
  code *pcVar1;
  longlong lVar2;
  undefined8 uVar3;
  undefined8 uVar4;
  longlong *plVar5;
  longlong *unaff_RSI;
  
  lVar2 = FUN_1810e8a40();
  if (lVar2 == 0) {
    FUN_180237af0();
    pcVar1 = (code *)swi(3);
    uVar3 = (*pcVar1)();
    return uVar3;
  }
  uVar3 = FUN_180a7fdc0(lVar2,DAT_18223f680);
  uVar4 = thunk_FUN_180203bc0(DAT_182272bb0);
  FUN_1802a4990(uVar4);
  uVar3 = FUN_1803fc530(uVar3,uVar4,DAT_18223c3b8);
  uVar4 = thunk_FUN_180203bc0(DAT_182272bb0);
  FUN_1802a4990(uVar4);
  uVar3 = FUN_1803fc530(uVar3,uVar4,DAT_18223c3b8);
  if (((*(byte *)(DAT_182272df8 + 0x12f) & 2) != 0) && (*(int *)(DAT_182272df8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_182272df8);
  }
  lVar2 = *(longlong *)(*(longlong *)(DAT_182272df8 + 0xb8) + 0x20);
  if (lVar2 == 0) {
    if (((*(byte *)(DAT_182272df8 + 0x12f) & 2) != 0) && (*(int *)(DAT_182272df8 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_182272df8);
    }
    uVar4 = **(undefined8 **)(DAT_182272df8 + 0xb8);
    lVar2 = thunk_FUN_180203bc0(DAT_182272b78);
    FUN_1802a4990(lVar2,uVar4,DAT_182281288,DAT_182230598);
    plVar5 = (longlong *)(*(longlong *)(DAT_182272df8 + 0xb8) + 0x20);
    *plVar5 = lVar2;
    thunk_FUN_180234e20(plVar5,lVar2);
  }
  uVar3 = FUN_1803f8040(uVar3,lVar2,DAT_182239a00);
  lVar2 = FUN_18075d910(uVar3,DAT_18223b488);
  *unaff_RSI = lVar2;
  thunk_FUN_180234e20();
  if (*unaff_RSI != 0) {
    uVar3 = FUN_180a18000(*unaff_RSI,0);
    return uVar3;
  }
  return 0;
}



/====================================================================/
/* ParameterProvider
 ===================================================================/

/********************************************************************/
/* ParameterProvider$$GetSkillLevel
 * RVA: 0x6A0570
 * Address: 0x1806A0570
 *******************************************************************/


void FUN_1806a0570(undefined8 param_1,undefined4 param_2)

{
  if (DAT_181f71e9a == '\0') {
    thunk_FUN_1801fef70(DAT_1817dee04);
    DAT_181f71e9a = '\x01';
  }
  if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  FUN_180382120(1,param_2,1,0);
  return;
}



/====================================================================/
/* SkillLevelProvider
 ===================================================================/

/********************************************************************/
/* SkillLevelProvider$$SettingSkillLevel
 * RVA: 0x6FC630
 * Address: 0x1806FC630
 *******************************************************************/


void FUN_1806fc630(undefined4 param_1,undefined8 param_2,longlong param_3)

{
  code *pcVar1;
  undefined8 uVar2;
  undefined8 uVar3;
  char cVar4;
  int iVar5;
  int iVar6;
  float fVar7;
  undefined4 local_res8 [2];
  
  if (DAT_181f7223a == '\0') {
    thunk_FUN_1801fef70(DAT_1817695b4);
    DAT_181f7223a = '\x01';
  }
  if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  local_res8[0] = FUN_180382120(1,param_1,1,0);
  uVar2 = FUN_180d7cc10(local_res8,0);
  iVar5 = FUN_180382d30(1,param_1,1,0);
  fVar7 = 0.0;
  if ((float)iVar5 != 0.0) {
    if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    iVar6 = FUN_180381c40(1,param_1,1,0);
    if ((float)iVar6 != 0.0) {
      fVar7 = DAT_1818398d4 - (float)iVar5 / (float)iVar6;
    }
  }
  if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  local_res8[0] = FUN_180383970(DAT_1822628e8,0);
  uVar3 = FUN_180d7cc10(local_res8,0);
  cVar4 = FUN_1810236d0(uVar2,uVar3,0);
  if (cVar4 != '\0') {
    fVar7 = DAT_1818398d4;
  }
  FUN_180c9d330(param_2,uVar2,0);
  if (param_3 == 0) {
    FUN_180237af0();
    pcVar1 = (code *)swi(3);
    (*pcVar1)();
    return;
  }
  FUN_1805335a0(param_3,fVar7,0);
  return;
}



/====================================================================/
/* Touch_AbilityContentListController
 ===================================================================/

/********************************************************************/
/* Touch_AbilityContentListController$$UpdateAbilitySkillLevel
 * RVA: 0x6EBE90
 * Address: 0x1806EBE90
 *******************************************************************/


void Touch_AbilityContentListController_UpdateAbilitySkillLevel(undefined8 param_1)

{
  code *pcVar1;
  char cVar2;
  longlong in_RAX;
  longlong lVar3;
  undefined8 uVar4;
  longlong unaff_RDI;
  
  FUN_18110b090(param_1,*(undefined4 *)(in_RAX + 0x10),DAT_182276ec0);
  cVar2 = FUN_1810c42a0();
  if (cVar2 != '\0') {
    if (*(char *)(unaff_RDI + 0x1c) == '\0') {
      if (((*(byte *)(DAT_18227ec30 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227ec30 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar3 = FUN_1810e8a40(DAT_182263668);
      if (((*(byte *)(DAT_18227ec18 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227ec18 + 0xe0) == 0)) {
        il2cpp_runtime_class_init(DAT_18227ec18);
      }
      if (lVar3 == 0) {
        FUN_180237af0();
        pcVar1 = (code *)swi(3);
        (*pcVar1)();
        return;
      }
      FUN_1808feb70(lVar3,*(undefined4 *)(*(longlong *)(DAT_18227ec18 + 0xb8) + 4),0,0,0);
    }
    uVar4 = thunk_FUN_180203bc0(DAT_182235fe8);
    FUN_1802a4990(uVar4);
    if (DAT_181f7219d == '\0') {
      thunk_FUN_1801fef70(DAT_181776b8c);
      DAT_181f7219d = '\x01';
    }
    lVar3 = thunk_FUN_180203bc0(DAT_18224cd98);
    FUN_1802698f0(lVar3,0);
    *(undefined8 *)(lVar3 + 0x20) = uVar4;
    *(undefined4 *)(lVar3 + 0x10) = 0;
    thunk_FUN_180234e20((undefined8 *)(lVar3 + 0x20),uVar4);
    FUN_180fa45a0();
  }
  return;
}



/====================================================================/
/* Touch_BattleAbilityInfomationContentController
 ===================================================================/

/********************************************************************/
/* Touch_BattleAbilityInfomationContentController$$UpdateAbilitySkillLevel
 * RVA: 0x6F0B70
 * Address: 0x1806F0B70
 *******************************************************************/


void FUN_1806f0b70(longlong param_1,longlong param_2)

{
  longlong lVar1;
  code *pcVar2;
  char cVar3;
  undefined4 uVar4;
  int iVar5;
  int iVar6;
  undefined8 uVar7;
  undefined8 uVar8;
  undefined8 uVar9;
  float fVar10;
  undefined4 local_res10 [2];
  
  if (param_2 != 0) {
    uVar4 = FUN_18067aea0(param_2,0);
    if (*(longlong *)(param_1 + 0x38) == 0) {
      uVar9 = 0;
    }
    else {
      uVar9 = *(undefined8 *)(*(longlong *)(param_1 + 0x38) + 0x58);
    }
    lVar1 = *(longlong *)(param_1 + 0x30);
    if (DAT_181f7223a == '\0') {
      thunk_FUN_1801fef70(DAT_1817695b4);
      DAT_181f7223a = '\x01';
    }
    if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    local_res10[0] = FUN_180382120(1,uVar4,1,0);
    uVar7 = FUN_180d7cc10(local_res10,0);
    iVar5 = FUN_180382d30(1,uVar4,1,0);
    fVar10 = 0.0;
    if ((float)iVar5 != 0.0) {
      if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      iVar6 = FUN_180381c40(1,uVar4,1,0);
      if ((float)iVar6 != 0.0) {
        fVar10 = DAT_1818398d4 - (float)iVar5 / (float)iVar6;
      }
    }
    if (((*(byte *)(DAT_18227e378 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e378 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    local_res10[0] = FUN_180383970(DAT_1822628e8,0);
    uVar8 = FUN_180d7cc10(local_res10,0);
    cVar3 = FUN_1810236d0(uVar7,uVar8,0);
    if (cVar3 != '\0') {
      fVar10 = DAT_1818398d4;
    }
    FUN_180c9d330(uVar9,uVar7,0);
    if (lVar1 == 0) {
      FUN_180237af0();
      pcVar2 = (code *)swi(3);
      (*pcVar2)();
      return;
    }
    FUN_1805335a0(lVar1,fVar10,0);
  }
  return;
}



/********************************************************************/
/* Touch_BattleAbilityInfomationContentController$$UpdateView_OwnedAbility
 * RVA: 0x6F0D30
 * Address: 0x1806F0D30
 *******************************************************************/


void FUN_1806f0d30(longlong param_1,longlong param_2,char param_3)

{
  code *pcVar1;
  longlong lVar2;
  undefined8 uVar3;
  longlong lVar4;
  undefined8 uVar5;
  undefined4 local_res8 [2];
  
  if (DAT_181f72262 == '\0') {
    thunk_FUN_1801fef70(DAT_1817de8c8);
    DAT_181f72262 = '\x01';
  }
  uVar5 = 0;
  *(longlong *)(param_1 + 0x18) = param_2;
  local_res8[0] = 0;
  thunk_FUN_180234e20((longlong *)(param_1 + 0x18),param_2);
  if (param_2 != 0) {
    if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar2 = FUN_1810e8a40(DAT_182263388);
    lVar4 = *(longlong *)(param_1 + 0x38);
    if (lVar4 != 0) {
      uVar3 = FUN_18067ae50(param_2,0);
      if (lVar2 == 0) {
        FUN_180237af0();
        pcVar1 = (code *)swi(3);
        (*pcVar1)();
        return;
      }
      uVar3 = FUN_1804d9ab0(lVar2,uVar3,1,0);
      FUN_1806f1230(lVar4,uVar3,0);
      lVar4 = *(longlong *)(param_1 + 0x38);
    }
    if (param_3 == '\0') {
      if (lVar4 != 0) {
        FUN_180c9ce30(*(undefined8 *)(lVar4 + 0x48),1,0);
        FUN_180c9ce30(*(undefined8 *)(lVar4 + 0x50),1,0);
        lVar4 = *(longlong *)(param_1 + 0x38);
        if (lVar4 != 0) {
          if (*(longlong *)(param_2 + 0x10) != 0) {
            local_res8[0] = FUN_180a18610(*(longlong *)(param_2 + 0x10),0);
            uVar5 = FUN_180d7cc10(local_res8,0);
          }
          FUN_180c9d330(*(undefined8 *)(lVar4 + 0x50),uVar5,0);
        }
      }
    }
    else if (lVar4 != 0) {
      FUN_180c9ce30(*(undefined8 *)(lVar4 + 0x48),0,0);
      FUN_180c9ce30(*(undefined8 *)(lVar4 + 0x50),0,0);
    }
  }
  return;
}

