/*
 * FF2 Decompiled Functions - Status Screen UI System
 * Generated by Ghidra headless analysis
 * Program: GameAssembly.dll
 * Image Base: 0x180000000
 * IL2CPP types applied: True
 *
 * Purpose: Understanding FF2's status screen UI for screen reader accessibility
 *
 * Key Classes:
 *   - SkillLevelContentController: Displays weapon skill level + progress bar
 *   - SkillLevelContentView: Contains levelText (0x20), gauge (0x28)
 *   - ParameterContentController: Displays combat stats (Accuracy, Evasion, etc.)
 *   - ParameterContentView: Contains multipliedValueText (0x28), percentText (0x38)
 *   - StatusDetailsController: Main status screen, owns skillLevelContentList
 *   - CommonGauge: Progress bar with gaugeImage.fillAmount (0.0-1.0)
 *   - BattleUtility: Static methods for stat calculations
 *
 * Memory Offsets (from dump.cs):
 *   SkillLevelContentController: view=0x18, weaponType=0x20
 *   SkillLevelContentView: iconText=0x18, levelText=0x20, gauge=0x28
 *   ParameterContentController: type=0x18, subType=0x1C, view=0x20
 *   ParameterContentView: fixedText=0x18, multipliedText=0x20,
 *                         multipliedValueText=0x28, parameterValueText=0x30, percentText=0x38
 *   CommonGauge: gaugeImage=0x18
 *
 * ParameterType enum values:
 *   AccuracyCount=202, EvasionCount=204, MagicDefenseCount=24
 *   AccuracyRate=16, EvasionRate=17, AbilityEvasionRate=13
 *
 * SkillLevelTarget enum values:
 *   Sword=0, Knife=1, Spear=2, Axe=3, Cane=4, Bow=5, Shield=6, Wrestle=7
 */


/====================================================================/
/* BattleUtility
 ===================================================================/

/********************************************************************/
/* BattleUtility$$GetDominationAttack
 * RVA: 0x911410
 * Address: 0x180911410
 *******************************************************************/


undefined8 FUN_180911410(longlong *param_1,int param_2)

{
  longlong *plVar1;
  longlong lVar2;
  longlong lVar3;
  code *pcVar4;
  int iVar5;
  undefined8 uVar6;
  
  if (DAT_181f73aea == '\0') {
    thunk_FUN_1801fef70(DAT_1817e7160);
    DAT_181f73aea = '\x01';
  }
  if (param_1 == (longlong *)0x0) {
    return 1;
  }
  if (*(byte *)(*param_1 + 0x128) < *(byte *)(DAT_18227d5a8 + 0x128)) {
    return 1;
  }
  if (*(longlong *)
       (*(longlong *)(*param_1 + 200) + -8 + (ulonglong)*(byte *)(DAT_18227d5a8 + 0x128) * 8) !=
      DAT_18227d5a8) {
    return 1;
  }
  if ((param_1[5] != 0) && (plVar1 = *(longlong **)(param_1[5] + 0x18), plVar1 != (longlong *)0x0))
  {
    if ((*(byte *)(DAT_18227d468 + 0x128) <= *(byte *)(*plVar1 + 0x128)) &&
       ((*(longlong *)
          (*(longlong *)(*plVar1 + 200) + -8 + (ulonglong)*(byte *)(DAT_18227d468 + 0x128) * 8) ==
         DAT_18227d468 && (plVar1[0xe] != 0)))) {
      lVar2 = *(longlong *)(plVar1[0xe] + 0x20);
      if ((lVar2 != 0) && (iVar5 = FUN_180a17fc0(lVar2,0), iVar5 == 1)) {
        if (plVar1[0xf] == 0) goto LAB_180911601;
        lVar2 = *(longlong *)(plVar1[0xf] + 0x20);
        if (lVar2 == 0) {
          return 1;
        }
        iVar5 = FUN_180a17fc0(lVar2,0);
        if (iVar5 == 2) {
          return 1;
        }
      }
      if (plVar1[0xe] != 0) {
        lVar2 = *(longlong *)(plVar1[0xe] + 0x20);
        if ((lVar2 == 0) || (iVar5 = FUN_180a17fc0(lVar2,0), iVar5 == 2)) {
          if (plVar1[0xf] == 0) goto LAB_180911601;
          lVar2 = *(longlong *)(plVar1[0xf] + 0x20);
          if ((lVar2 != 0) && (iVar5 = FUN_180a17fc0(lVar2,0), iVar5 == 1)) {
            return 2;
          }
        }
        if ((plVar1[0xe] != 0) && (plVar1[0xf] != 0)) {
          lVar2 = *(longlong *)(plVar1[0xe] + 0x20);
          lVar3 = *(longlong *)(plVar1[0xf] + 0x20);
          if (lVar3 == 0 && lVar2 != 0) {
            return 1;
          }
          if (lVar3 == 0 || lVar2 != 0) {
            if (param_1[7] == 0) goto LAB_180911601;
            iVar5 = FUN_18067b000(param_1[7],0);
            if (iVar5 != 1) {
              if (iVar5 == 2) {
                if (param_2 == 0) {
                  return 2;
                }
                return 1;
              }
              if (iVar5 != 3) {
                return 0;
              }
            }
            if (param_2 == 0) {
              return 1;
            }
          }
          return 2;
        }
      }
    }
  }
LAB_180911601:
  FUN_180237af0();
  pcVar4 = (code *)swi(3);
  uVar6 = (*pcVar4)();
  return uVar6;
}



/********************************************************************/
/* BattleUtility$$GetJobLevel
 * RVA: 0x911F70
 * Address: 0x180911F70
 *******************************************************************/


undefined8 FUN_180911f70(undefined8 param_1)

{
  longlong lVar1;
  code *pcVar2;
  undefined4 uVar3;
  longlong lVar4;
  undefined8 uVar5;
  
  if (DAT_181f73ae8 == '\0') {
    thunk_FUN_1801fef70(DAT_1817e7208);
    DAT_181f73ae8 = '\x01';
  }
  lVar4 = thunk_FUN_180203bc0(DAT_1822799b0);
  FUN_1802698f0(lVar4,0);
  if (lVar4 != 0) {
    *(undefined8 *)(lVar4 + 0x10) = param_1;
    thunk_FUN_180234e20(lVar4 + 0x10,param_1);
    if ((*(longlong *)(lVar4 + 0x10) != 0) &&
       (lVar1 = *(longlong *)(*(longlong *)(lVar4 + 0x10) + 0x28), lVar1 != 0)) {
      uVar5 = thunk_FUN_180203bc0(DAT_182279988);
      FUN_1802a4990(uVar5,lVar4,DAT_18227c5e8,DAT_182232e48);
      uVar5 = FUN_1803fd610(lVar1,uVar5,DAT_18223d4b0);
      lVar4 = FUN_18075d910(uVar5,DAT_18223b058);
      if (lVar4 != 0) {
        uVar3 = FUN_180679720(lVar4,0);
        if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar5 = FUN_180382120(1,uVar3,0x65);
        return uVar5;
      }
    }
    return 0;
  }
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  uVar5 = (*pcVar2)();
  return uVar5;
}



/********************************************************************/
/* BattleUtility$$GetSkillLevel
 * RVA: 0x913900
 * Address: 0x180913900
 *******************************************************************/


ulonglong FUN_180913900(longlong param_1,int param_2)

{
  code *pcVar1;
  int iVar2;
  char cVar3;
  ulonglong uVar4;
  int local_res10 [2];
  
  if (DAT_181f73ae9 == '\0') {
    thunk_FUN_1801fef70(DAT_1817e733c);
    DAT_181f73ae9 = '\x01';
  }
  local_res10[0] = 0;
  if (param_2 - 8U < 2) {
    if (param_1 != 0) {
      if (*(longlong *)(param_1 + 0x58) == 0) goto LAB_180913a9a;
      cVar3 = FUN_1813c22b0(*(longlong *)(param_1 + 0x58),param_2,local_res10,DAT_182258028);
      if (cVar3 != '\0') {
        if (local_res10[0] == 0) {
          return 1;
        }
        return (ulonglong)(local_res10[0] / 100 + 1);
      }
    }
  }
  else {
    if (param_2 - 10U < 2) {
      if (param_1 != 0) {
        if (*(longlong *)(param_1 + 0x58) == 0) {
LAB_180913a9a:
          FUN_180237af0();
          pcVar1 = (code *)swi(3);
          uVar4 = (*pcVar1)();
          return uVar4;
        }
        FUN_1813c22b0(*(longlong *)(param_1 + 0x58),param_2,local_res10,DAT_182258028);
      }
      iVar2 = local_res10[0];
      if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      uVar4 = FUN_180382120(1,iVar2,0xc9);
      return uVar4;
    }
    if (param_1 != 0) {
      if (*(longlong *)(param_1 + 0x58) == 0) goto LAB_180913a9a;
      cVar3 = FUN_1813c22b0(*(longlong *)(param_1 + 0x58),param_2,local_res10,DAT_182258028);
      iVar2 = local_res10[0];
      if (cVar3 != '\0') {
        if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init();
        }
        uVar4 = FUN_180382120(1,iVar2,1,0);
        return uVar4;
      }
    }
  }
  return 0;
}



/====================================================================/
/* CommonGauge
 ===================================================================/

/********************************************************************/
/* CommonGauge$$SetValue
 * RVA: 0x5335A0
 * Address: 0x1805335A0
 *******************************************************************/


void FUN_1805335a0(longlong param_1,undefined4 param_2)

{
  undefined8 uVar1;
  code *pcVar2;
  char cVar3;
  
  if (DAT_181f6fa9c == '\0') {
    thunk_FUN_1801fef70(DAT_18176c9e4);
    DAT_181f6fa9c = '\x01';
  }
  uVar1 = *(undefined8 *)(param_1 + 0x18);
  if (((*(byte *)(DAT_18222f850 + 0x12f) & 2) != 0) && (*(int *)(DAT_18222f850 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  cVar3 = FUN_180fa6b10(uVar1,0,0);
  if (cVar3 == '\0') {
    if (*(longlong *)(param_1 + 0x18) == 0) {
      FUN_180237af0();
      pcVar2 = (code *)swi(3);
      (*pcVar2)();
      return;
    }
    FUN_180e87960(*(longlong *)(param_1 + 0x18),param_2,0);
  }
  return;
}



/====================================================================/
/* KeyInput_ParameterContentController
 ===================================================================/

/********************************************************************/
/* KeyInput_ParameterContentController$$Initialize
 * RVA: 0x5B07D0
 * Address: 0x1805B07D0
 *******************************************************************/


void FUN_1805b07d0(longlong param_1)

{
  longlong lVar1;
  longlong *plVar2;
  code *pcVar3;
  longlong lVar4;
  undefined8 uVar5;
  
  lVar1 = *(longlong *)(param_1 + 0x20);
  if (lVar1 == 0) {
    return;
  }
  FUN_1805b0a30(lVar1,0);
  FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x18),1,0);
  FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x30),1,0);
  if (DAT_181f716ed == '\0') {
    thunk_FUN_1801fef70(DAT_1817deb2c);
    DAT_181f716ed = '\x01';
  }
  FUN_180c9d330(*(undefined8 *)(lVar1 + 0x38),DAT_182245380,0);
  FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x38),1,0);
  if (DAT_181f716ec == '\0') {
    thunk_FUN_1801fef70(DAT_1817deb10);
    DAT_181f716ec = '\x01';
  }
  if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar4 = FUN_1810e8a40(DAT_182263388);
  plVar2 = *(longlong **)(lVar1 + 0x20);
  if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_18227eb78);
  }
  if ((lVar4 != 0) &&
     (uVar5 = FUN_1804d97f0(lVar4,*(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0x618),0),
     plVar2 != (longlong *)0x0)) {
    (**(code **)(*plVar2 + 0x5e0))(plVar2,uVar5,*(undefined8 *)(*plVar2 + 0x5e8));
    FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x28),1,0);
    return;
  }
  FUN_180237af0();
  pcVar3 = (code *)swi(3);
  (*pcVar3)();
  return;
}



/********************************************************************/
/* KeyInput_ParameterContentController$$SetCountValue
 * RVA: 0x5B0930
 * Address: 0x1805B0930
 *******************************************************************/


void FUN_1805b0930(longlong param_1,undefined4 param_2)

{
  longlong lVar1;
  undefined8 uVar2;
  undefined4 local_res10 [6];
  
  lVar1 = *(longlong *)(param_1 + 0x20);
  if (lVar1 != 0) {
    local_res10[0] = param_2;
    uVar2 = FUN_180d7cc10(local_res10,0);
    FUN_180c9d330(*(undefined8 *)(lVar1 + 0x28),uVar2,0);
  }
  return;
}



/********************************************************************/
/* KeyInput_ParameterContentController$$SetData
 * RVA: 0x5B0970
 * Address: 0x1805B0970
 *******************************************************************/


void FUN_1805b0970(longlong param_1,undefined8 param_2,undefined4 param_3)

{
  longlong lVar1;
  undefined8 uVar2;
  undefined4 local_res18 [4];
  
  if (*(longlong *)(param_1 + 0x20) != 0) {
    local_res18[0] = param_3;
    FUN_180c9d330(*(undefined8 *)(*(longlong *)(param_1 + 0x20) + 0x18),param_2,0);
    lVar1 = *(longlong *)(param_1 + 0x20);
    if (lVar1 != 0) {
      uVar2 = FUN_180d7cc10(local_res18,0);
      FUN_180c9d330(*(undefined8 *)(lVar1 + 0x30),uVar2,0);
    }
  }
  return;
}



/********************************************************************/
/* KeyInput_ParameterContentController$$SetEnableCountText
 * RVA: 0x5B09D0
 * Address: 0x1805B09D0
 *******************************************************************/


void FUN_1805b09d0(longlong param_1,ulonglong param_2)

{
  longlong lVar1;
  
  lVar1 = *(longlong *)(param_1 + 0x20);
  if (lVar1 != 0) {
    FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x20),param_2,0);
    FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x28),param_2 & 0xff,0);
  }
  return;
}



/********************************************************************/
/* KeyInput_ParameterContentController$$SetEnablePercentText
 * RVA: 0x5B0A10
 * Address: 0x1805B0A10
 *******************************************************************/


void FUN_1805b0a10(longlong param_1,undefined8 param_2)

{
  if (*(longlong *)(param_1 + 0x20) != 0) {
    FUN_180c9ce30(*(undefined8 *)(*(longlong *)(param_1 + 0x20) + 0x38),param_2,0);
    return;
  }
  return;
}



/====================================================================/
/* KeyInput_ParameterContentView
 ===================================================================/

/********************************************************************/
/* KeyInput_ParameterContentView$$Initialize
 * RVA: 0x5B0CA0
 * Address: 0x1805B0CA0
 *******************************************************************/


void FUN_1805b0ca0(longlong param_1)

{
  longlong *plVar1;
  code *pcVar2;
  longlong lVar3;
  undefined8 uVar4;
  
  FUN_1805b0a30(param_1,0);
  FUN_180c9ce30(*(undefined8 *)(param_1 + 0x18),1,0);
  FUN_180c9ce30(*(undefined8 *)(param_1 + 0x30),1,0);
  if (DAT_181f716ed == '\0') {
    thunk_FUN_1801fef70(DAT_1817deb2c);
    DAT_181f716ed = '\x01';
  }
  FUN_180c9d330(*(undefined8 *)(param_1 + 0x38),DAT_182245380,0);
  FUN_180c9ce30(*(undefined8 *)(param_1 + 0x38),1,0);
  if (DAT_181f716ec == '\0') {
    thunk_FUN_1801fef70(DAT_1817deb10);
    DAT_181f716ec = '\x01';
  }
  if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar3 = FUN_1810e8a40(DAT_182263388);
  plVar1 = *(longlong **)(param_1 + 0x20);
  if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_18227eb78);
  }
  if (lVar3 != 0) {
    uVar4 = FUN_1804d97f0(lVar3,*(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0x618),0);
    if (plVar1 != (longlong *)0x0) {
      (**(code **)(*plVar1 + 0x5e0))(plVar1,uVar4,*(undefined8 *)(*plVar1 + 0x5e8));
      FUN_180c9ce30(*(undefined8 *)(param_1 + 0x28),1,0);
      return;
    }
  }
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/********************************************************************/
/* KeyInput_ParameterContentView$$SetCountText
 * RVA: 0x3CD360
 * Address: 0x1803CD360
 *******************************************************************/


void FUN_1803cd360(longlong param_1,undefined8 param_2)

{
  FUN_180c9d330(*(undefined8 *)(param_1 + 0x28),param_2,0);
  return;
}



/********************************************************************/
/* KeyInput_ParameterContentView$$SetParameterText
 * RVA: 0x2C9D10
 * Address: 0x1802C9D10
 *******************************************************************/


void FUN_1802c9d10(longlong param_1,undefined8 param_2)

{
  FUN_180c9d330(*(undefined8 *)(param_1 + 0x30),param_2,0);
  return;
}



/********************************************************************/
/* KeyInput_ParameterContentView$$UseMultipliedText
 * RVA: 0x5B0E30
 * Address: 0x1805B0E30
 *******************************************************************/


void FUN_1805b0e30(longlong param_1)

{
  longlong *plVar1;
  code *pcVar2;
  longlong lVar3;
  undefined8 uVar4;
  
  if (DAT_181f716ec == '\0') {
    thunk_FUN_1801fef70(DAT_1817deb10);
    DAT_181f716ec = '\x01';
  }
  if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar3 = FUN_1810e8a40(DAT_182263388);
  plVar1 = *(longlong **)(param_1 + 0x20);
  if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_18227eb78);
  }
  if (lVar3 != 0) {
    uVar4 = FUN_1804d97f0(lVar3,*(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0x618),0);
    if (plVar1 != (longlong *)0x0) {
                    /* WARNING: Could not recover jumptable at 0x0001805b0eee. Too many branches */
                    /* WARNING: Treating indirect jump as call */
      (**(code **)(*plVar1 + 0x5e0))(plVar1,uVar4,*(undefined8 *)(*plVar1 + 0x5e8));
      return;
    }
  }
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/********************************************************************/
/* KeyInput_ParameterContentView$$UseMultipliedValueText
 * RVA: 0x3CD9A0
 * Address: 0x1803CD9A0
 *******************************************************************/


void KeyInput_ParameterContentView_UseMultipliedValueText(longlong param_1)

{
  FUN_180c9ce30(*(undefined8 *)(param_1 + 0x28),1,0);
  return;
}



/********************************************************************/
/* KeyInput_ParameterContentView$$UsePercentText
 * RVA: 0x5B0F00
 * Address: 0x1805B0F00
 *******************************************************************/


void FUN_1805b0f00(longlong param_1)

{
  if (DAT_181f716ed == '\0') {
    thunk_FUN_1801fef70(DAT_1817deb2c);
    DAT_181f716ed = '\x01';
  }
  FUN_180c9d330(*(undefined8 *)(param_1 + 0x38),DAT_182245380,0);
  FUN_180c9ce30(*(undefined8 *)(param_1 + 0x38),1,0);
  return;
}



/====================================================================/
/* KeyInput_StatusDetailsController
 ===================================================================/

/********************************************************************/
/* KeyInput_StatusDetailsController$$InitDisplay
 * RVA: 0x3DCA20
 * Address: 0x1803DCA20
 *******************************************************************/


void FUN_1803dca20(longlong param_1)

{
  undefined8 uVar1;
  
  if (DAT_181f6eb43 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c048);
    DAT_181f6eb43 = '\x01';
  }
  if (*(longlong *)(param_1 + 0x78) != 0) {
    FUN_18040b360(*(longlong *)(param_1 + 0x78),1,0);
  }
  uVar1 = thunk_FUN_180203bc0(DAT_1822725f0);
  FUN_1802a4990(uVar1,param_1,DAT_1822254a0,DAT_182275388);
  *(undefined8 *)(param_1 + 0x20) = uVar1;
  thunk_FUN_180234e20((undefined8 *)(param_1 + 0x20),uVar1);
  return;
}



/********************************************************************/
/* KeyInput_StatusDetailsController$$Initialize
 * RVA: 0x3DCAA0
 * Address: 0x1803DCAA0
 *******************************************************************/


void FUN_1803dcaa0(longlong param_1,undefined8 param_2)

{
  code *pcVar1;
  longlong lVar2;
  char cVar3;
  undefined4 uVar4;
  undefined4 local_40;
  undefined4 uStack_3c;
  undefined4 uStack_38;
  undefined4 uStack_34;
  longlong local_30;
  undefined4 local_28;
  undefined4 uStack_24;
  undefined4 uStack_20;
  undefined4 uStack_1c;
  longlong local_18;
  
  if (DAT_181f6eb40 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c0bc);
    DAT_181f6eb40 = '\x01';
  }
  FUN_1804fbc20(param_1,param_2,0);
  if (*(longlong *)(param_1 + 0x70) != 0) {
    FUN_1803dd840(*(longlong *)(param_1 + 0x70),0);
  }
  if (*(longlong *)(param_1 + 0x78) != 0) {
    FUN_18040b300(*(longlong *)(param_1 + 0x78),0);
  }
  if (*(longlong *)(param_1 + 0x80) != 0) {
    FUN_1813a5750(&local_28,*(longlong *)(param_1 + 0x80),DAT_182233778);
    local_40 = local_28;
    uStack_3c = uStack_24;
    uStack_38 = uStack_20;
    uStack_34 = uStack_1c;
    local_30 = local_18;
    while( true ) {
      cVar3 = FUN_180a42760(&local_40,DAT_182250180);
      lVar2 = local_30;
      if (cVar3 == '\0') {
        FUN_1802698f0(&local_40,DAT_182249868);
        return;
      }
      if (local_30 == 0) break;
      FUN_1803dbda0(local_30,0);
      FUN_1803dc460(lVar2,0);
    }
    uVar4 = FUN_180237af0();
    FUN_180237ac0(uVar4,0);
    pcVar1 = (code *)swi(3);
    (*pcVar1)();
    return;
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* KeyInput_StatusDetailsController$$UpdateDisplay
 * RVA: 0x3DCE90
 * Address: 0x1803DCE90
 *******************************************************************/


void FUN_1803dce90(longlong *param_1)

{
  undefined4 uVar1;
  code *pcVar2;
  char cVar3;
  longlong lVar4;
  uint in_stack_ffffffffffffffe8;
  
  if (DAT_181f6eb44 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c130);
    DAT_181f6eb44 = '\x01';
  }
  if (((*(byte *)(DAT_18227dd48 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227dd48 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar4 = FUN_1810e8a40(DAT_182262dc8);
  if (((*(byte *)(DAT_18227e250 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e250 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  if (lVar4 == 0) goto LAB_1803dd1a8;
  in_stack_ffffffffffffffe8 = in_stack_ffffffffffffffe8 & 0xffffff00;
  cVar3 = FUN_180a545c0(lVar4,*(undefined8 *)(*(longlong *)(DAT_18227e250 + 0xb8) + 0x48),3,0,
                        in_stack_ffffffffffffffe8,0);
  if (cVar3 == '\0') {
    if (((*(byte *)(DAT_18227dd48 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227dd48 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    lVar4 = FUN_1810e8a40(DAT_182262dc8);
    if (((*(byte *)(DAT_18227e250 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e250 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    if (lVar4 == 0) goto LAB_1803dd1a8;
    in_stack_ffffffffffffffe8 = in_stack_ffffffffffffffe8 & 0xffffff00;
    cVar3 = FUN_180a545c0(lVar4,*(undefined8 *)(*(longlong *)(DAT_18227e250 + 0xb8) + 0x50),3,0,
                          in_stack_ffffffffffffffe8,0);
    if (cVar3 == '\0') {
      if (((*(byte *)(DAT_18227dd48 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227dd48 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar4 = FUN_1810e8a40(DAT_182262dc8);
      if (((*(byte *)(DAT_18227e250 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e250 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      if (lVar4 == 0) goto LAB_1803dd1a8;
      cVar3 = FUN_180a545c0(lVar4,*(undefined8 *)(*(longlong *)(DAT_18227e250 + 0xb8) + 0x10),3,0,
                            in_stack_ffffffffffffffe8 & 0xffffff00,0);
      if (cVar3 == '\0') {
        return;
      }
      (**(code **)(*param_1 + 0x210))(param_1,*(undefined8 *)(*param_1 + 0x218));
      if (param_1[6] != 0) {
        FUN_1810e1c00(param_1[6],0,DAT_182245870);
      }
      if (((*(byte *)(DAT_18227ec30 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227ec30 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      lVar4 = FUN_1810e8a40(DAT_182263668);
      if (((*(byte *)(DAT_18227ec18 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227ec18 + 0xe0) == 0)) {
        il2cpp_runtime_class_init(DAT_18227ec18);
      }
      if (lVar4 == 0) goto LAB_1803dd1a8;
      uVar1 = *(undefined4 *)(*(longlong *)(DAT_18227ec18 + 0xb8) + 8);
      goto LAB_1803dd0f1;
    }
    (**(code **)(*param_1 + 0x250))(param_1,*(undefined8 *)(*param_1 + 600));
  }
  else {
    (**(code **)(*param_1 + 0x260))(param_1,*(undefined8 *)(*param_1 + 0x268));
  }
  if (((*(byte *)(DAT_18227ec30 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227ec30 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar4 = FUN_1810e8a40(DAT_182263668);
  if (((*(byte *)(DAT_18227ec18 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227ec18 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_18227ec18);
  }
  if (lVar4 == 0) {
LAB_1803dd1a8:
    FUN_180237af0();
    pcVar2 = (code *)swi(3);
    (*pcVar2)();
    return;
  }
  uVar1 = **(undefined4 **)(DAT_18227ec18 + 0xb8);
LAB_1803dd0f1:
  FUN_1808feb70(lVar4,uVar1,0,0,0,0);
  return;
}



/********************************************************************/
/* KeyInput_StatusDetailsController$$UpdateView
 * RVA: 0x3DD1B0
 * Address: 0x1803DD1B0
 *******************************************************************/


void KeyInput_StatusDetailsController_UpdateView(longlong *param_1)

{
  longlong lVar1;
  code *pcVar2;
  char cVar3;
  undefined4 uVar4;
  longlong lVar5;
  undefined8 uVar6;
  undefined8 uVar7;
  undefined4 auStackX_8 [2];
  undefined4 uStack_50;
  undefined4 uStack_4c;
  undefined4 uStack_48;
  undefined4 uStack_44;
  longlong lStack_40;
  undefined4 uStack_38;
  undefined4 uStack_34;
  undefined4 uStack_30;
  undefined4 uStack_2c;
  longlong lStack_28;
  
  if (DAT_181f6eb42 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c15c);
    DAT_181f6eb42 = '\x01';
  }
  auStackX_8[0] = 0;
  if (((*(byte *)(DAT_18227e2b0 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e2b0 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar5 = FUN_1805e5510(0);
  if (lVar5 != 0) {
    lVar5 = FUN_1805e3300(lVar5,*(undefined4 *)(param_1 + 5),0);
    if (param_1[0xf] != 0) {
      FUN_18040b790(param_1[0xf],lVar5,1,0);
    }
    (**(code **)(*param_1 + 0x3a0))(param_1,lVar5,*(undefined8 *)(*param_1 + 0x3a8));
    lVar1 = param_1[0xe];
    if (lVar1 != 0) {
      if (lVar5 == 0) goto LAB_1803dd400;
      auStackX_8[0] = FUN_18067f4b0(lVar5,0);
      uVar6 = FUN_180d7cc10(auStackX_8,0);
      FUN_180c9d330(*(undefined8 *)(lVar1 + 0x30),uVar6,0);
      lVar1 = param_1[0xe];
      if (lVar1 != 0) {
        if (lVar5 == 0) goto LAB_1803dd400;
        auStackX_8[0] = FUN_18067b480(lVar5,0);
        uVar6 = FUN_180d7cc10(auStackX_8,0);
        FUN_180c9d330(*(undefined8 *)(lVar1 + 0x40),uVar6,0);
        if (param_1[0xe] != 0) {
          FUN_1803ddab0(param_1[0xe],lVar5,0);
        }
      }
    }
    if (param_1[0x10] != 0) {
      FUN_1813a5750(&uStack_38,param_1[0x10],DAT_182233778);
      uStack_50 = uStack_38;
      uStack_4c = uStack_34;
      uStack_48 = uStack_30;
      uStack_44 = uStack_2c;
      lStack_40 = lStack_28;
      while( true ) {
        cVar3 = FUN_180a42760(&uStack_50,DAT_182250180);
        lVar1 = lStack_40;
        if (cVar3 == '\0') {
          FUN_1802698f0(&uStack_50,DAT_182249868);
          return;
        }
        if (lStack_40 == 0) goto LAB_1803dd3f2;
        if (DAT_181f6eb5d == '\0') {
          thunk_FUN_1801fef70(DAT_181769588);
          DAT_181f6eb5d = '\x01';
        }
        if (lVar5 == 0) break;
        if (*(longlong *)(lVar5 + 0x58) == 0) {
          FUN_180237af0();
          break;
        }
        uVar4 = FUN_1813c8070(*(longlong *)(lVar5 + 0x58),*(undefined4 *)(lVar1 + 0x20),
                              DAT_182228338);
        lVar1 = *(longlong *)(lVar1 + 0x18);
        if (lVar1 == 0) {
          uVar6 = 0;
          uVar7 = 0;
        }
        else {
          uVar6 = *(undefined8 *)(lVar1 + 0x28);
          uVar7 = *(undefined8 *)(lVar1 + 0x20);
        }
        FUN_1806fc630(uVar4,uVar7,uVar6,0);
      }
      FUN_180237af0();
LAB_1803dd3f2:
      uVar4 = FUN_180237af0();
      FUN_180237ac0(uVar4,0);
      pcVar2 = (code *)swi(3);
      (*pcVar2)();
      return;
    }
  }
LAB_1803dd400:
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/====================================================================/
/* SkillLevelContentController
 ===================================================================/

/********************************************************************/
/* SkillLevelContentController$$Initialize
 * RVA: 0x3DBDA0
 * Address: 0x1803DBDA0
 *******************************************************************/


void FUN_1803dbda0(longlong param_1)

{
  longlong lVar1;
  longlong lVar2;
  undefined4 *puVar3;
  undefined4 local_18;
  undefined4 uStack_14;
  undefined4 uStack_10;
  undefined4 uStack_c;
  
  lVar1 = *(longlong *)(param_1 + 0x18);
  if (lVar1 == 0) {
    return;
  }
  if (*(longlong *)(lVar1 + 0x18) != 0) {
    FUN_1804ec990(*(longlong *)(lVar1 + 0x18),0);
  }
  if (DAT_181f6eb5f == '\0') {
    thunk_FUN_1801fef70(DAT_1817695ac);
    DAT_181f6eb5f = '\x01';
  }
  if (*(longlong *)(lVar1 + 0x20) != 0) {
    FUN_180c9ce30(*(longlong *)(lVar1 + 0x20),0,0);
    if (*(longlong *)(lVar1 + 0x20) != 0) {
      FUN_180c9d330(*(longlong *)(lVar1 + 0x20),**(undefined8 **)(DAT_18223c718 + 0xb8),0);
      lVar2 = *(longlong *)(lVar1 + 0x20);
      if (lVar2 != 0) {
        if (((*(byte *)(DAT_18227f680 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f680 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18227f680);
        }
        puVar3 = (undefined4 *)FUN_1810cb520(&local_18,**(undefined4 **)(DAT_18227f680 + 0xb8),0);
        local_18 = *puVar3;
        uStack_14 = puVar3[1];
        uStack_10 = puVar3[2];
        uStack_c = puVar3[3];
        FUN_180c9cfc0(lVar2,&local_18,0);
      }
    }
  }
  FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x20),1,0);
  return;
}



/********************************************************************/
/* SkillLevelContentController$$SetAbilityIcon
 * RVA: 0x3DBEA0
 * Address: 0x1803DBEA0
 *******************************************************************/


void FUN_1803dbea0(longlong param_1,longlong param_2)

{
  code *pcVar1;
  longlong lVar2;
  undefined8 uVar3;
  
  if (DAT_181f6eb5b == '\0') {
    thunk_FUN_1801fef70(DAT_18176952c);
    DAT_181f6eb5b = '\x01';
  }
  if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar2 = FUN_1810e8a40(DAT_182263388);
  if (param_2 != 0) {
    uVar3 = FUN_18067ae50(param_2,0);
    if (lVar2 != 0) {
      uVar3 = FUN_1804d9ab0(lVar2,uVar3,1,0);
      lVar2 = *(longlong *)(param_1 + 0x18);
      if (lVar2 != 0) {
        lVar2 = *(longlong *)(lVar2 + 0x18);
      }
      if (((*(byte *)(DAT_18227f700 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f700 + 0xe0) == 0)) {
        il2cpp_runtime_class_init();
      }
      FUN_1804ec680(lVar2,uVar3,0,0);
      return;
    }
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* SkillLevelContentController$$SetSkillLevelTargetType
 * RVA: 0x3DC1F0
 * Address: 0x1803DC1F0
 *******************************************************************/


ulonglong FUN_1803dc1f0(longlong param_1,longlong param_2)

{
  longlong lVar1;
  int iVar2;
  uint uVar3;
  ulonglong in_RAX;
  ulonglong uVar4;
  
  if (param_2 == 0) {
    *(undefined4 *)(param_1 + 0x20) = 7;
  }
  else {
    if (*(longlong *)(param_2 + 0x50) == 0) {
      lVar1 = *(longlong *)(param_2 + 0x58);
      *(uint *)(param_1 + 0x20) = 7 - (uint)(lVar1 != 0);
      return -lVar1;
    }
    uVar4 = FUN_180a18040(*(longlong *)(param_2 + 0x50),0);
    iVar2 = (int)uVar4;
    if (iVar2 == 1) {
      *(undefined4 *)(param_1 + 0x20) = 0;
      return uVar4;
    }
    uVar3 = iVar2 - 5;
    in_RAX = (ulonglong)uVar3;
    if (uVar3 < 8) {
      in_RAX = (ulonglong)(int)uVar3;
      switch(uVar3) {
      case 0:
        *(undefined4 *)(param_1 + 0x20) = 1;
        return in_RAX;
      case 1:
        *(undefined4 *)(param_1 + 0x20) = 2;
        return in_RAX;
      case 3:
        *(undefined4 *)(param_1 + 0x20) = 3;
        return in_RAX;
      case 5:
        *(undefined4 *)(param_1 + 0x20) = 4;
        return in_RAX;
      case 7:
        *(undefined4 *)(param_1 + 0x20) = 5;
        return in_RAX;
      }
    }
    else if (iVar2 == 0x2b) {
      *(undefined4 *)(param_1 + 0x20) = 7;
      return in_RAX;
    }
  }
  return in_RAX;
}



/********************************************************************/
/* SkillLevelContentController$$SetSkillLevelUpColor
 * RVA: 0x3DC2E0
 * Address: 0x1803DC2E0
 *******************************************************************/


void FUN_1803dc2e0(longlong param_1,longlong param_2,longlong param_3)

{
  longlong lVar1;
  undefined8 uVar2;
  code *pcVar3;
  undefined4 uVar4;
  int iVar5;
  int iVar6;
  undefined4 *puVar7;
  undefined4 local_18;
  undefined4 uStack_14;
  undefined4 uStack_10;
  undefined4 uStack_c;
  
  if (DAT_181f6eb5e == '\0') {
    thunk_FUN_1801fef70(DAT_181769558);
    DAT_181f6eb5e = '\x01';
  }
  if ((param_2 != 0) && (*(longlong *)(param_2 + 0x58) != 0)) {
    uVar4 = FUN_1813c8070(*(longlong *)(param_2 + 0x58),*(undefined4 *)(param_1 + 0x20),
                          DAT_182228338);
    if (((*(byte *)(DAT_182279950 + 0x12f) & 2) != 0) && (*(int *)(DAT_182279950 + 0xe0) == 0)) {
      il2cpp_runtime_class_init();
    }
    iVar5 = FUN_180382120(1,uVar4,1,0);
    if ((param_3 != 0) && (*(longlong *)(param_3 + 0x58) != 0)) {
      uVar4 = FUN_1813c8070(*(longlong *)(param_3 + 0x58),*(undefined4 *)(param_1 + 0x20),
                            DAT_182228338);
      iVar6 = FUN_180382120(1,uVar4,1,0);
      lVar1 = *(longlong *)(param_1 + 0x18);
      if (iVar5 < iVar6) {
        if (((*(byte *)(DAT_18227f680 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f680 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18227f680);
        }
        if (lVar1 == 0) goto LAB_1803dc458;
        uVar4 = *(undefined4 *)(*(longlong *)(DAT_18227f680 + 0xb8) + 0x18);
      }
      else {
        if (((*(byte *)(DAT_18227f680 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f680 + 0xe0) == 0))
        {
          il2cpp_runtime_class_init(DAT_18227f680);
        }
        if (lVar1 == 0) goto LAB_1803dc458;
        uVar4 = **(undefined4 **)(DAT_18227f680 + 0xb8);
      }
      uVar2 = *(undefined8 *)(lVar1 + 0x20);
      puVar7 = (undefined4 *)FUN_1810cb520(&local_18,uVar4,0);
      local_18 = *puVar7;
      uStack_14 = puVar7[1];
      uStack_10 = puVar7[2];
      uStack_c = puVar7[3];
      FUN_180c9cfc0(uVar2,&local_18,0);
      return;
    }
  }
LAB_1803dc458:
  FUN_180237af0();
  pcVar3 = (code *)swi(3);
  (*pcVar3)();
  return;
}



/********************************************************************/
/* SkillLevelContentController$$SetWeaponIcon
 * RVA: 0x3DC460
 * Address: 0x1803DC460
 *******************************************************************/


void FUN_1803dc460(longlong param_1)

{
  code *pcVar1;
  longlong lVar2;
  undefined8 uVar3;
  
  if (DAT_181f6eb5a == '\0') {
    thunk_FUN_1801fef70(DAT_181769570);
    DAT_181f6eb5a = '\x01';
  }
  if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar2 = FUN_1810e8a40(DAT_182263388);
  switch(*(undefined4 *)(param_1 + 0x20)) {
  case 0:
    if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18227eb78);
    }
    if (lVar2 == 0) {
LAB_1803dc747:
      FUN_180237af0();
      pcVar1 = (code *)swi(3);
      (*pcVar1)();
      return;
    }
    uVar3 = *(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0xb20);
    break;
  case 1:
    if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18227eb78);
    }
    if (lVar2 == 0) goto LAB_1803dc747;
    uVar3 = *(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0xb18);
    break;
  case 2:
    if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18227eb78);
    }
    if (lVar2 == 0) goto LAB_1803dc747;
    uVar3 = *(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0xb38);
    break;
  case 3:
    if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18227eb78);
    }
    if (lVar2 == 0) goto LAB_1803dc747;
    uVar3 = *(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0xb30);
    break;
  case 4:
    if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18227eb78);
    }
    if (lVar2 == 0) goto LAB_1803dc747;
    uVar3 = *(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0xb28);
    break;
  case 5:
    if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18227eb78);
    }
    if (lVar2 == 0) goto LAB_1803dc747;
    uVar3 = *(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0xb40);
    break;
  case 6:
    if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18227eb78);
    }
    if (lVar2 == 0) goto LAB_1803dc747;
    uVar3 = *(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0xb48);
    break;
  default:
    if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
      il2cpp_runtime_class_init(DAT_18227eb78);
    }
    if (lVar2 == 0) goto LAB_1803dc747;
    uVar3 = *(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0xb10);
  }
  uVar3 = FUN_1804d97f0(lVar2,uVar3,0);
  lVar2 = *(longlong *)(param_1 + 0x18);
  if (lVar2 != 0) {
    lVar2 = *(longlong *)(lVar2 + 0x18);
  }
  if (((*(byte *)(DAT_18227f700 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227f700 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  FUN_1804ec680(lVar2,uVar3,0,0);
  return;
}



/********************************************************************/
/* SkillLevelContentController$$UpdateView_OwnedCharacterData
 * RVA: 0x3DC7D0
 * Address: 0x1803DC7D0
 *******************************************************************/


void FUN_1803dc7d0(longlong param_1,longlong param_2)

{
  longlong lVar1;
  code *pcVar2;
  undefined4 uVar3;
  undefined8 uVar4;
  undefined8 uVar5;
  
  if (DAT_181f6eb5d == '\0') {
    thunk_FUN_1801fef70(DAT_181769588);
    DAT_181f6eb5d = '\x01';
  }
  if ((param_2 != 0) && (*(longlong *)(param_2 + 0x58) != 0)) {
    uVar3 = FUN_1813c8070(*(longlong *)(param_2 + 0x58),*(undefined4 *)(param_1 + 0x20),
                          DAT_182228338);
    lVar1 = *(longlong *)(param_1 + 0x18);
    if (lVar1 == 0) {
      uVar4 = 0;
      uVar5 = 0;
    }
    else {
      uVar4 = *(undefined8 *)(lVar1 + 0x20);
      uVar5 = *(undefined8 *)(lVar1 + 0x28);
    }
    FUN_1806fc630(uVar3,uVar4,uVar5,0);
    return;
  }
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/====================================================================/
/* Touch_ParameterContentController
 ===================================================================/

/********************************************************************/
/* Touch_ParameterContentController$$Initialize
 * RVA: 0x927A70
 * Address: 0x180927A70
 *******************************************************************/


void FUN_180927a70(longlong param_1)

{
  longlong lVar1;
  longlong *plVar2;
  code *pcVar3;
  longlong lVar4;
  undefined8 uVar5;
  
  lVar1 = *(longlong *)(param_1 + 0x20);
  if (lVar1 == 0) {
    return;
  }
  FUN_180927c20(lVar1,0);
  FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x18),1,0);
  FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x30),1,0);
  if (DAT_181f73ba8 == '\0') {
    thunk_FUN_1801fef70(DAT_1817deb40);
    DAT_181f73ba8 = '\x01';
  }
  FUN_180c9d330(*(undefined8 *)(lVar1 + 0x38),DAT_182245380,0);
  FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x38),1,0);
  if (DAT_181f73ba7 == '\0') {
    thunk_FUN_1801fef70(DAT_1817deb04);
    DAT_181f73ba7 = '\x01';
  }
  if (((*(byte *)(DAT_18227eba8 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eba8 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar4 = FUN_1810e8a40(DAT_182263388);
  plVar2 = *(longlong **)(lVar1 + 0x20);
  if (((*(byte *)(DAT_18227eb78 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227eb78 + 0xe0) == 0)) {
    il2cpp_runtime_class_init(DAT_18227eb78);
  }
  if ((lVar4 != 0) &&
     (uVar5 = FUN_1804d97f0(lVar4,*(undefined8 *)(*(longlong *)(DAT_18227eb78 + 0xb8) + 0x618),0),
     plVar2 != (longlong *)0x0)) {
    (**(code **)(*plVar2 + 0x5e0))(plVar2,uVar5,*(undefined8 *)(*plVar2 + 0x5e8));
    FUN_180c9ce30(*(undefined8 *)(lVar1 + 0x28),1,0);
    return;
  }
  FUN_180237af0();
  pcVar3 = (code *)swi(3);
  (*pcVar3)();
  return;
}



/********************************************************************/
/* Touch_ParameterContentController$$SetCountValue
 * RVA: 0x927BD0
 * Address: 0x180927BD0
 *******************************************************************/


void FUN_180927bd0(longlong param_1,undefined4 param_2)

{
  longlong lVar1;
  longlong *plVar2;
  code *pcVar3;
  undefined8 uVar4;
  undefined4 local_res10 [6];
  
  lVar1 = *(longlong *)(param_1 + 0x20);
  if (lVar1 != 0) {
    local_res10[0] = param_2;
    uVar4 = FUN_180d7cc10(local_res10,0);
    plVar2 = *(longlong **)(lVar1 + 0x28);
    if (plVar2 == (longlong *)0x0) {
      FUN_180237af0();
      pcVar3 = (code *)swi(3);
      (*pcVar3)();
      return;
    }
    (**(code **)(*plVar2 + 0x5e0))(plVar2,uVar4,*(undefined8 *)(*plVar2 + 0x5e8));
  }
  return;
}



/====================================================================/
/* Touch_StatusDetailsController
 ===================================================================/

/********************************************************************/
/* Touch_StatusDetailsController$$InitDisplay
 * RVA: 0x6A3560
 * Address: 0x1806A3560
 *******************************************************************/


void FUN_1806a3560(longlong *param_1)

{
  code *pcVar1;
  longlong lVar2;
  longlong lVar3;
  
  if (DAT_181f71e70 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c070);
    DAT_181f71e70 = '\x01';
  }
  lVar3 = param_1[10];
  if (((*(byte *)(DAT_18227e2b0 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e2b0 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar2 = FUN_1805e5510(0);
  if (lVar2 != 0) {
    lVar2 = FUN_1805e3420(lVar2,0);
    if ((lVar2 != 0) && (lVar3 != 0)) {
      FUN_1809274e0(lVar3,*(undefined4 *)(lVar2 + 0x18),0);
      if (param_1[10] != 0) {
        FUN_180927670(param_1[10],*(undefined4 *)(param_1 + 5),0);
        (**(code **)(*param_1 + 0x240))(param_1,*(undefined8 *)(*param_1 + 0x248));
        lVar3 = thunk_FUN_180203bc0(DAT_1822725f0);
        FUN_1802a4990(lVar3,param_1,DAT_182285b88,DAT_182275388);
        param_1[4] = lVar3;
        thunk_FUN_180234e20(param_1 + 4,lVar3);
        return;
      }
    }
  }
  FUN_180237af0();
  pcVar1 = (code *)swi(3);
  (*pcVar1)();
  return;
}



/********************************************************************/
/* Touch_StatusDetailsController$$Initialize
 * RVA: 0x6A3740
 * Address: 0x1806A3740
 *******************************************************************/


void Touch_StatusDetailsController_Initialize(longlong param_1,undefined8 param_2)

{
  longlong lVar1;
  code *pcVar2;
  char cVar3;
  undefined8 uVar4;
  undefined4 uVar5;
  undefined4 uStack_50;
  undefined4 uStack_4c;
  undefined4 uStack_48;
  undefined4 uStack_44;
  longlong lStack_40;
  undefined4 uStack_38;
  undefined4 uStack_34;
  undefined4 uStack_30;
  undefined4 uStack_2c;
  longlong lStack_28;
  
  if (DAT_181f71e6d == '\0') {
    thunk_FUN_1801fef70(DAT_18176c098);
    DAT_181f71e6d = '\x01';
  }
  FUN_1803e9540(param_1,param_2,0);
  if (*(longlong *)(param_1 + 0x70) != 0) {
    FUN_1806a4240(*(longlong *)(param_1 + 0x70),0);
  }
  if (DAT_181f71e71 == '\0') {
    thunk_FUN_1801fef70(DAT_18176c07c);
    DAT_181f71e71 = '\x01';
  }
  if (*(longlong *)(param_1 + 0x70) != 0) {
    lVar1 = *(longlong *)(*(longlong *)(param_1 + 0x70) + 0x48);
    if (lVar1 == 0) goto LAB_1806a3944;
    lVar1 = *(longlong *)(lVar1 + 0xf8);
    uVar4 = thunk_FUN_180203bc0(DAT_18222f700);
    FUN_1802a4990(uVar4,param_1,DAT_182285b68,0);
    if (lVar1 == 0) goto LAB_1806a3944;
    FUN_1810d6660(lVar1,uVar4,0);
    if (*(longlong *)(param_1 + 0x70) != 0) {
      lVar1 = *(longlong *)(*(longlong *)(param_1 + 0x70) + 0x50);
      if (lVar1 == 0) goto LAB_1806a3944;
      lVar1 = *(longlong *)(lVar1 + 0xf8);
      uVar4 = thunk_FUN_180203bc0(DAT_18222f700);
      FUN_1802a4990(uVar4,param_1,DAT_182285b28,0);
      if (lVar1 == 0) goto LAB_1806a3944;
      FUN_1810d6660(lVar1,uVar4,0);
    }
  }
  if (*(longlong *)(param_1 + 0x80) != 0) {
    FUN_1803cbd30(*(longlong *)(param_1 + 0x80),0);
  }
  if (*(longlong *)(param_1 + 0x78) != 0) {
    FUN_1813a5750(&uStack_38,*(longlong *)(param_1 + 0x78),DAT_182233778);
    uStack_50 = uStack_38;
    uStack_4c = uStack_34;
    uStack_48 = uStack_30;
    uStack_44 = uStack_2c;
    lStack_40 = lStack_28;
    while( true ) {
      cVar3 = FUN_180a42760(&uStack_50,DAT_182250180);
      lVar1 = lStack_40;
      if (cVar3 == '\0') {
        FUN_1802698f0(&uStack_50,DAT_182249868);
        return;
      }
      if (lStack_40 == 0) break;
      FUN_1803dbda0(lStack_40,0);
      FUN_1803dc460(lVar1,0);
    }
    uVar5 = FUN_180237af0();
    FUN_180237ac0(uVar5,0);
    pcVar2 = (code *)swi(3);
    (*pcVar2)();
    return;
  }
LAB_1806a3944:
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}



/********************************************************************/
/* Touch_StatusDetailsController$$UpdateView
 * RVA: 0x6A3BA0
 * Address: 0x1806A3BA0
 *******************************************************************/


void Touch_StatusDetailsController_UpdateView(longlong *param_1)

{
  longlong lVar1;
  code *pcVar2;
  char cVar3;
  longlong lVar4;
  undefined8 uVar5;
  undefined4 uVar6;
  undefined4 auStackX_8 [2];
  undefined4 uStack_50;
  undefined4 uStack_4c;
  undefined4 uStack_48;
  undefined4 uStack_44;
  longlong lStack_40;
  undefined4 uStack_38;
  undefined4 uStack_34;
  undefined4 uStack_30;
  undefined4 uStack_2c;
  longlong lStack_28;
  
  if (DAT_181f71e6f == '\0') {
    thunk_FUN_1801fef70(DAT_18176c13c);
    DAT_181f71e6f = '\x01';
  }
  auStackX_8[0] = 0;
  if (((*(byte *)(DAT_18227e2b0 + 0x12f) & 2) != 0) && (*(int *)(DAT_18227e2b0 + 0xe0) == 0)) {
    il2cpp_runtime_class_init();
  }
  lVar4 = FUN_1805e5510(0);
  if (lVar4 != 0) {
    lVar4 = FUN_1805e3300(lVar4,*(undefined4 *)(param_1 + 5),0);
    if (param_1[10] != 0) {
      FUN_180927670(param_1[10],*(undefined4 *)(param_1 + 5),0);
      if (param_1[0x10] != 0) {
        FUN_1803cc010(param_1[0x10],lVar4,1,0);
      }
      (**(code **)(*param_1 + 0x370))(param_1,lVar4,*(undefined8 *)(*param_1 + 0x378));
      lVar1 = param_1[0xe];
      if (lVar1 != 0) {
        if (lVar4 == 0) goto LAB_1806a3dab;
        auStackX_8[0] = FUN_18067f4b0(lVar4,0);
        uVar5 = FUN_180d7cc10(auStackX_8,0);
        FUN_180c9d330(*(undefined8 *)(lVar1 + 0x30),uVar5,0);
        lVar1 = param_1[0xe];
        if (lVar1 != 0) {
          if (lVar4 == 0) goto LAB_1806a3dab;
          auStackX_8[0] = FUN_18067b480(lVar4,0);
          uVar5 = FUN_180d7cc10(auStackX_8,0);
          FUN_180c9d330(*(undefined8 *)(lVar1 + 0x40),uVar5,0);
          if (param_1[0xe] != 0) {
            FUN_1806a44b0(param_1[0xe],lVar4,0);
          }
        }
      }
      if (param_1[0xf] != 0) {
        FUN_1813a5750(&uStack_38,param_1[0xf],DAT_182233778);
        uStack_50 = uStack_38;
        uStack_4c = uStack_34;
        uStack_48 = uStack_30;
        uStack_44 = uStack_2c;
        lStack_40 = lStack_28;
        while( true ) {
          cVar3 = FUN_180a42760(&uStack_50,DAT_182250180);
          if (cVar3 == '\0') {
            FUN_1802698f0(&uStack_50,DAT_182249868);
            return;
          }
          if (lStack_40 == 0) break;
          FUN_1803dc7d0(lStack_40,lVar4,0);
        }
        uVar6 = FUN_180237af0();
        FUN_180237ac0(uVar6,0);
        pcVar2 = (code *)swi(3);
        (*pcVar2)();
        return;
      }
    }
  }
LAB_1806a3dab:
  FUN_180237af0();
  pcVar2 = (code *)swi(3);
  (*pcVar2)();
  return;
}

